import type { WeekSixRecordsPythonRun } from './weekSixRecordsPythonRunner';
import { parseWeekSixRecordsPython } from './weekSixRecordsPythonGrammar';
import { hasExactKeys,isPlainRecord,sameData } from './strictData';
import { createEmptyWeekSixArchiveInput,isWeekSixArchiveSource,parseWeekSixArchiveInput,runWeekSixArchiveCore,WEEK_SIX_ARCHIVE_CLAIM_IDS,WEEK_SIX_ARCHIVE_FACT_IDS } from './weekSixArchiveCore';
export { createEmptyWeekSixArchiveInput,deriveWeekSixArchiveSource,isWeekSixArchiveSource,parseWeekSixArchiveInput,runWeekSixArchiveCore } from './weekSixArchiveCore';
export type { WeekSixArchiveBriefInput,WeekSixArchiveClaimId,WeekSixArchiveConstraintId,WeekSixArchiveCoreRunResult,WeekSixArchiveDisposition,WeekSixArchiveEvidenceId,WeekSixArchiveFactId,WeekSixArchiveFailureSnapshot,WeekSixArchiveFormat,WeekSixArchiveInput,WeekSixArchiveReviewInput,WeekSixArchiveScope,WeekSixArchiveSource,WeekSixArchiveState,WeekSixArchiveVerdict } from './weekSixArchiveCore';
import type { WeekSixArchiveClaimId,WeekSixArchiveConstraintId,WeekSixArchiveDisposition,WeekSixArchiveEvidenceId,WeekSixArchiveInput,WeekSixArchiveScope,WeekSixArchiveState,WeekSixArchiveVerdict } from './weekSixArchiveCore';
export const WEEK_SIX_ARCHIVE_CLAIMS:ReadonlyArray<{id:WeekSixArchiveClaimId;text:string}>=[{id:'first-and-third',text:'一调得到假扇、火势更旺；三调最终借得真扇并灭火通行。'},{id:'second-therefore-passed',text:'二调取得真扇，所以当次已经灭火通行。'},{id:'exactly-thirty-minutes',text:'三次借扇的整个过程恰好用了三十分钟。'}];
export const WEEK_SIX_ARCHIVE_EVIDENCE:ReadonlyArray<{id:WeekSixArchiveEvidenceId;text:string;source:string}>=[{id:'run-first',text:'本次程序第1行：一调得到假扇，火势更旺。',source:'当前实际 Python 运行结果'},{id:'run-second',text:'本次程序第2行：二调取得真扇，随后被骗回。',source:'当前实际 Python 运行结果'},{id:'run-third',text:'本次程序第3行：三调最终借得真扇，灭火通行。',source:'当前实际 Python 运行结果'},{id:'m2-second-not-passed',text:'M2 正式分类作品：二调当次没有完成灭火通行。',source:'W6-M2 正式作品'},{id:'provided-material-scope',text:'本页有限材料没有提供三次借扇整个过程的具体分钟数。',source:'本题给出的有限材料范围'},{id:'teacher-says-so',text:'教师练习句里这样写了。',source:'待核验练习自身'}];
export type WeekSixArchiveDraft={format:'event-table';rows:Array<{attempt:string;story:string}>;scope:WeekSixArchiveScope;constraints:WeekSixArchiveConstraintId[]}|{format:'step-list';steps:string[];scope:WeekSixArchiveScope;constraints:WeekSixArchiveConstraintId[]}|null;
export interface WeekSixArchiveReviewRow{claimId:WeekSixArchiveClaimId;originalClaim:string;verdict:WeekSixArchiveVerdict;evidence:Array<{id:WeekSixArchiveEvidenceId;text:string;source:string}>;disposition:WeekSixArchiveDisposition;revision:string|null}
export interface WeekSixArchiveRunResult{state:WeekSixArchiveState;completed:boolean;pythonRun:WeekSixRecordsPythonRun|null;draft:WeekSixArchiveDraft;reviewReport:{authorship:'teacher-authored-practice';rows:WeekSixArchiveReviewRow[]};failureSnapshots:import('./weekSixArchiveCore').WeekSixArchiveFailureSnapshot[];penalty:{livesLost:0;resourcesLost:0;starsLost:0}}
const revisions:Record<Exclude<WeekSixArchiveDisposition,null>,string>={'keep-original':WEEK_SIX_ARCHIVE_CLAIMS[0]!.text,'revise-second-result':'二调取得真扇、随后被骗回，所以当次没有完成灭火通行。','cannot-confirm':'本页给出的材料不足以确认整个过程的具体分钟数，暂不能确认是否恰好用了三十分钟。','mark-false':'三次借扇的整个过程不是三十分钟。'};
function draft(input:WeekSixArchiveInput,actual:WeekSixRecordsPythonRun|null):WeekSixArchiveDraft{if(!input.brief.format||!actual)return null;const rows=WEEK_SIX_ARCHIVE_FACT_IDS.flatMap((id,index)=>input.brief.factIds.includes(id)?[structuredClone(actual.run.rows[index]!)]:[]);return input.brief.format==='event-table'?{format:'event-table',rows,scope:input.brief.scope,constraints:[...input.brief.constraintIds]}:{format:'step-list',steps:rows.map((row,index)=>`第${index+1}步：${row.attempt}｜${row.story}`),scope:input.brief.scope,constraints:[...input.brief.constraintIds]}}
function report(input:WeekSixArchiveInput,actual:WeekSixRecordsPythonRun|null):WeekSixArchiveRunResult['reviewReport']{return{authorship:'teacher-authored-practice',rows:input.reviews.map(review=>{const originalClaim=WEEK_SIX_ARCHIVE_CLAIMS.find(item=>item.id===review.claimId)!.text;return{claimId:review.claimId,originalClaim,verdict:review.verdict,evidence:WEEK_SIX_ARCHIVE_EVIDENCE.filter(item=>review.evidenceIds.includes(item.id)).map(item=>{const index=item.id==='run-first'?0:item.id==='run-second'?1:item.id==='run-third'?2:-1,row=index>=0?actual?.run.rows[index]:null;return row?{...item,text:`本次程序第${index+1}行：${row.attempt}｜${row.story}`}:{...item}}),disposition:review.disposition,revision:review.disposition==='keep-original'?originalClaim:review.disposition?revisions[review.disposition]:null}})}}
export function runWeekSixArchive(code:unknown,workerValue:unknown,inputValue:unknown,sourceValue:unknown):WeekSixArchiveRunResult{const input=parseWeekSixArchiveInput(inputValue)??createEmptyWeekSixArchiveInput(),core=runWeekSixArchiveCore(code,workerValue,inputValue,sourceValue);let actual:WeekSixRecordsPythonRun|null=null;try{const parsed=parseWeekSixRecordsPython(code);if(!('state'in parsed)&&isPlainRecord(workerValue)&&hasExactKeys(workerValue,['trace','run'])){const candidate=workerValue as unknown as WeekSixRecordsPythonRun;if(sameData(candidate.trace,parsed.trace)&&sameData(candidate.run,parsed.run))actual=structuredClone(candidate)}}catch{/* Invalid drafts have no current runtime output. */}return{...core,pythonRun:actual,draft:draft(input,actual),reviewReport:report(input,actual)}}
export function toWeekSixArchiveCoreRun(run:WeekSixArchiveRunResult){return{state:run.state,completed:run.completed,failureSnapshots:structuredClone(run.failureSnapshots),penalty:structuredClone(run.penalty)}}
