import { compileHeavenlySignalBossDraft, isHeavenlySignalBossBlockType, runHeavenlySignalBoss, validateHeavenlySignalBossDraft, type HeavenlySignalBossInstruction, type HeavenlySignalBossWorkspaceDraftV1 } from '../blockly/weekTwoHeavenlySignalBossContract';
import type { HeavenlySignalBossMissionSession, MissionSession } from './types';

const object = (value: unknown, field: string): Record<string, unknown> => { if (typeof value !== 'object' || value === null || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) throw new Error(`${field}必须是对象`); return value as Record<string, unknown>; };
const exact = (value: Record<string, unknown>, keys: readonly string[], field: string) => { if (Object.keys(value).length !== keys.length || keys.some((key) => !(key in value))) throw new Error(`${field}字段无效`); };
const count = (value: unknown, field: string) => { if (!Number.isSafeInteger(value) || (value as number) < 0) throw new Error(`${field}必须是非负安全整数`); return value as number; };
const date = (value: unknown, field: string) => { if (typeof value !== 'string' || Number.isNaN(new Date(value).getTime()) || new Date(value).toISOString() !== value) throw new Error(`${field}必须是ISO日期`); return value; };
const same = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
function workspace(value: unknown): HeavenlySignalBossWorkspaceDraftV1 {
  const source = object(value, 'sessions.w2-m5.workspace'); exact(source, ['version', 'missionId', 'blocks'], 'sessions.w2-m5.workspace');
  if (source.version !== 1 || source.missionId !== 'w2-m5' || !Array.isArray(source.blocks)) throw new Error('sessions.w2-m5.workspace无效');
  const blocks = source.blocks.map((value, index) => { const block = object(value, `sessions.w2-m5.workspace.blocks[${index}]`); exact(block, ['id', 'type', 'previousId', 'nextId', 'parentBlockId', 'handlerBlockId', 'repeatCount', 'conditionBlockId', 'x', 'y'], `sessions.w2-m5.workspace.blocks[${index}]`); if (typeof block.id !== 'string' || !isHeavenlySignalBossBlockType(String(block.type)) || typeof block.handlerBlockId !== 'string' || (block.previousId !== null && typeof block.previousId !== 'string') || (block.nextId !== null && typeof block.nextId !== 'string') || (block.parentBlockId !== null && typeof block.parentBlockId !== 'string') || (block.repeatCount !== null && (!Number.isSafeInteger(block.repeatCount) || (block.repeatCount as number) < 1)) || (block.conditionBlockId !== null && typeof block.conditionBlockId !== 'string') || !Number.isFinite(block.x) || !Number.isFinite(block.y)) throw new Error('sessions.w2-m5.workspace积木无效'); return block as unknown as HeavenlySignalBossWorkspaceDraftV1['blocks'][number]; });
  const parsed = { version: 1 as const, missionId: 'w2-m5' as const, blocks }; validateHeavenlySignalBossDraft(parsed); return parsed;
}
function trace(value: unknown, draft: HeavenlySignalBossWorkspaceDraftV1): HeavenlySignalBossInstruction[] {
  if (!Array.isArray(value)) throw new Error('sessions.w2-m5.lastTrace必须是数组');
  const parsed = value.map((value, index) => { const item = object(value, `sessions.w2-m5.lastTrace[${index}]`); exact(item, ['instructionId', 'kind', 'eventId', 'eventType', 'dispatchIndex', 'handlerBlockId', 'sourceBlockId', 'parentBlockId', 'opcode', 'iteration', 'repeatCount', 'conditionSourceBlockId', 'conditionKind', 'elapsedDays'], `sessions.w2-m5.lastTrace[${index}]`); if (item.conditionKind !== null && item.conditionKind !== 'red-eyes' && item.conditionKind !== 'furnace-open' && item.conditionKind !== 'smoke-clears') throw new Error('sessions.w2-m5.lastTrace条件类型无效'); return item as unknown as HeavenlySignalBossInstruction; });
  if (parsed.length > 0 && !same(parsed, compileHeavenlySignalBossDraft(draft))) throw new Error('sessions.w2-m5.lastTrace必须由workspace重新编译'); return parsed;
}
export function parseHeavenlySignalBossSession(value: unknown): HeavenlySignalBossMissionSession {
  const source = object(value, 'sessions.w2-m5'); exact(source, ['workspace', 'lastTrace', 'lastRun', 'totalRuns', 'runtimeFailures', 'compileFailures', 'usedHintTiers', 'conceptFailures', 'lastRunAt', 'savedAt'], 'sessions.w2-m5');
  const parsedWorkspace = workspace(source.workspace); const lastTrace = trace(source.lastTrace, parsedWorkspace); const totalRuns = count(source.totalRuns, 'sessions.w2-m5.totalRuns'); const runtimeFailures = count(source.runtimeFailures, 'sessions.w2-m5.runtimeFailures'); const compileFailures = count(source.compileFailures, 'sessions.w2-m5.compileFailures');
  if (!Array.isArray(source.usedHintTiers) || source.usedHintTiers.some((tier) => tier !== 'observe' && tier !== 'think' && tier !== 'partial') || new Set(source.usedHintTiers).size !== source.usedHintTiers.length) throw new Error('sessions.w2-m5.usedHintTiers无效');
  const failures = object(source.conceptFailures, 'sessions.w2-m5.conceptFailures'); exact(failures, ['programStructure', 'loopCount', 'eventRouting', 'handlerSequence', 'sequencePrecondition', 'loopCondition', 'conditionNeverMet', 'completeness'], 'sessions.w2-m5.conceptFailures'); const conceptFailures = { programStructure: count(failures.programStructure, 'sessions.w2-m5.programStructure'), loopCount: count(failures.loopCount, 'sessions.w2-m5.loopCount'), eventRouting: count(failures.eventRouting, 'sessions.w2-m5.eventRouting'), handlerSequence: count(failures.handlerSequence, 'sessions.w2-m5.handlerSequence'), sequencePrecondition: count(failures.sequencePrecondition, 'sessions.w2-m5.sequencePrecondition'), loopCondition: count(failures.loopCondition, 'sessions.w2-m5.loopCondition'), conditionNeverMet: count(failures.conditionNeverMet, 'sessions.w2-m5.conditionNeverMet'), completeness: count(failures.completeness, 'sessions.w2-m5.completeness') };
  if (compileFailures !== conceptFailures.programStructure || runtimeFailures !== conceptFailures.loopCount + conceptFailures.eventRouting + conceptFailures.handlerSequence + conceptFailures.sequencePrecondition + conceptFailures.loopCondition + conceptFailures.conditionNeverMet + conceptFailures.completeness) throw new Error('sessions.w2-m5累计失败证据不一致');
  const lastRunAt = source.lastRunAt === null ? null : date(source.lastRunAt, 'sessions.w2-m5.lastRunAt');
  if (totalRuns === 0 && (source.lastRun !== null || lastTrace.length !== 0 || lastRunAt !== null)) throw new Error('sessions.w2-m5零次运行不得有运行证据');
  const hasEvidence = source.lastRun !== null || lastTrace.length > 0 || lastRunAt !== null;
  if (totalRuns > 0 && hasEvidence && (source.lastRun === null || lastTrace.length === 0 || lastRunAt === null)) throw new Error('sessions.w2-m5运行证据不完整');
  const lastRun = source.lastRun === null ? null : runHeavenlySignalBoss(lastTrace); if (source.lastRun !== null && !same(source.lastRun, lastRun)) throw new Error('sessions.w2-m5.lastRun必须由lastTrace确定性重放');
  return { workspace: parsedWorkspace, lastTrace, lastRun, totalRuns, runtimeFailures, compileFailures, usedHintTiers: source.usedHintTiers as MissionSession['usedHintTiers'], conceptFailures, lastRunAt, savedAt: date(source.savedAt, 'sessions.w2-m5.savedAt') };
}
