import { deriveWeekSixArchiveSource,runWeekSixArchiveCore } from '../engine/weekSixArchiveCore';
import { parseWeekSixRecordsDraftEnvelope } from '../engine/weekSixRecordsPythonGrammar';
import { hasExactKeys,isLegacyReplayEvidence,isPlainRecord,isSafeCount,isUtcIso,sameData } from '../engine/strictData';
import type { MissionProgress,WeekSixArchiveCompletionEvidence,WeekSixArchiveWorkV1,WeekSixFactCheckWorkV1 } from './types';
import type { WeekSixArchiveMissionSession } from './weekSixArchiveSession';

const bad=():never=>{throw Error('W6-M5 data invalid')};
function obj(value:unknown):Record<string,unknown>{if(!isPlainRecord(value))bad();return value as Record<string,unknown>}
function iso(value:unknown):string{if(!isUtcIso(value))bad();return value as string}
function count(value:unknown):number{if(!isSafeCount(value))bad();return value as number}
function canonical(session:Record<string,unknown>){const worker=session.workerTrace===null&&session.workerRun===null?null:{trace:session.workerTrace,run:session.workerRun};return runWeekSixArchiveCore(session.pythonCode,worker,session.input,session.source)}
const seal=(value:Record<string,unknown>,run:unknown)=>[value.source,value.pythonCode,value.workerTrace,value.workerRun,value.input,run];

export function parseWeekSixArchiveSession(value:unknown):WeekSixArchiveMissionSession{const session=obj(value);if(!hasExactKeys(session,['kind','source','pythonCode','workerTrace','workerRun','workerRunAt','input','lastRun','failureSnapshot','totalRuns','pythonFailures','briefFailures','reviewFailures','usedHintTiers','firstBlockingStage','lastRunAt','savedAt'])||session.kind!=='python-ai-archive-v1'||typeof session.pythonCode!=='string')bad();try{parseWeekSixRecordsDraftEnvelope(session.pythonCode)}catch{return bad()}const source=obj(session.source),sourceAt=iso(source.factCheckVerifiedAt),savedAt=iso(session.savedAt);if(sourceAt>savedAt)bad();const run=canonical(session);if(run.state==='source-invalid'||run.state==='input-invalid'||run.state==='python-worker-stale')bad();const counts=[session.pythonFailures,session.briefFailures,session.reviewFailures].map(count),total=count(session.totalRuns),failures=counts.reduce((a,b)=>a+b,0),first=session.firstBlockingStage;if(failures>total||!Array.isArray(session.usedHintTiers)||session.usedHintTiers.some(value=>typeof value!=='string'||!['observe','think','partial'].includes(value))||new Set(session.usedHintTiers).size!==session.usedHintTiers.length||![null,'python','brief','review'].includes(first as never)||(first===null)!==(failures===0))bad();if(typeof first==='string'&&!({python:counts[0],brief:counts[1],review:counts[2]} as Record<string,number>)[first])bad();const hasWorker=session.workerTrace!==null||session.workerRun!==null||session.workerRunAt!==null;if(hasWorker){if(session.workerTrace===null||session.workerRun===null||['python-structure-invalid','python-worker-missing','python-worker-stale'].includes(run.state))bad();const workerAt=iso(session.workerRunAt);if(workerAt<sourceAt||workerAt>savedAt||run.state==='python-worker-missing')bad()}else if(session.workerTrace!==null||session.workerRun!==null||session.workerRunAt!==null)bad();if(session.lastRun===null){if(session.failureSnapshot!==null||session.lastRunAt!==null)bad()}else{const runAt=iso(session.lastRunAt);if((!hasWorker&&run.state!=='python-structure-invalid')||runAt<sourceAt||runAt>savedAt||!total||!sameData(session.lastRun,run)||(run.completed?session.failureSnapshot!==null:!isPlainRecord(session.failureSnapshot)||session.failureSnapshot.result!==run.state))bad()}return structuredClone(session) as unknown as WeekSixArchiveMissionSession}
export function parseWeekSixArchiveWork(value:unknown):WeekSixArchiveWorkV1{const work=obj(value);if(!hasExactKeys(work,['kind','workId','missionId','title','source','pythonCode','workerTrace','workerRun','input','run','createdAt','verifiedAt'])||work.kind!=='python-ai-archive-v1'||work.workId!=='w6-m5-journey-archive'||work.missionId!=='w6-m5'||typeof work.title!=='string'||!work.title||work.title.length>100||typeof work.pythonCode!=='string')bad();const sourceAt=iso(obj(work.source).factCheckVerifiedAt),createdAt=iso(work.createdAt),verifiedAt=iso(work.verifiedAt),run=runWeekSixArchiveCore(work.pythonCode,{trace:work.workerTrace,run:work.workerRun},work.input,work.source);if(!run.completed||!sameData(run,work.run)||sourceAt>createdAt||createdAt>verifiedAt)bad();return structuredClone(work) as unknown as WeekSixArchiveWorkV1}
export function parseWeekSixArchiveEvidence(value:unknown,input:{mission:MissionProgress|undefined;formalWeekSixFactCheck:boolean;session:WeekSixArchiveMissionSession|undefined;work:WeekSixArchiveWorkV1|undefined;sourceWork:WeekSixFactCheckWorkV1|undefined}):WeekSixArchiveCompletionEvidence{const evidence=obj(value),mission=input.mission;if(!mission)return bad();if(evidence.kind==='legacy-replay-only'){if(!isLegacyReplayEvidence(evidence,mission,input.work,22))bad();return structuredClone(evidence) as WeekSixArchiveCompletionEvidence}if(!hasExactKeys(evidence,['kind','completedAt','verifiedAt','workId']))bad();const completedAt=iso(evidence.completedAt),verifiedAt=iso(evidence.verifiedAt),session=input.session,work=input.work,sourceWork=input.sourceWork;if(evidence.kind!=='formal-v3'||!input.formalWeekSixFactCheck||!session||!work||!sourceWork||evidence.workId!==work.workId||completedAt!==mission.completedAt||!sameData(work.source,deriveWeekSixArchiveSource(sourceWork))||!sameData(seal(work as unknown as Record<string,unknown>,work.run),seal(session as unknown as Record<string,unknown>,session.lastRun))||session.lastRunAt===null||completedAt>work.createdAt||session.savedAt>work.createdAt||work.createdAt>verifiedAt||work.verifiedAt!==verifiedAt)bad();return structuredClone(evidence) as WeekSixArchiveCompletionEvidence}
