import { runWeekSixClassification } from '../engine/weekSixClassificationContract';
import type { MissionProgress, WeekSixClassificationCompletionEvidence, WeekSixClassificationWorkV1, WeekSixRecordsWorkV1 } from './types';
import type { WeekSixClassificationMissionSession } from './weekSixClassificationSession';

const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b),UTC=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
function obj(v:unknown,l:string):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.getPrototypeOf(v)!==Object.prototype)throw Error('W6-M2 数据无效');return v as Record<string,unknown>}
function exact(v:Record<string,unknown>,keys:string[],l:string){const a=Reflect.ownKeys(v);if(a.length!==keys.length||a.some(k=>typeof k!=='string'||!keys.includes(k)))throw Error('W6-M2 数据无效')}
function iso(v:unknown,l:string){if(typeof v!=='string'||!UTC.test(v)||new Date(v).toISOString()!==v)throw Error('W6-M2 数据无效');return v}
function count(v:unknown,l:string){if(!Number.isSafeInteger(v)||(v as number)<0)throw Error('W6-M2 数据无效');return v as number}
function validInput(input:unknown,rows:unknown){const run=runWeekSixClassification(input,rows);if(run.state==='source-invalid'||run.state==='input-invalid')throw Error('W6-M2 数据无效');return run}

export function parseWeekSixClassificationSession(value:unknown):WeekSixClassificationMissionSession{
 const s=obj(value,'W6-M2 session');exact(s,['kind','sourceWorkId','sourceVerifiedAt','sourceRows','input','groupingDimension','lastRun','failureSnapshot','totalChecks','incompleteChecks','labelFailures','evidenceFailures','practiceFailures','usedHintTiers','firstBlockingConcept','lastCheckedAt','savedAt'],'W6-M2 session');
 if(s.kind!=='ai-evidence-classification-v1'||s.sourceWorkId!=='w6-m1-structured-records-table'||!['authenticity','passage'].includes(String(s.groupingDimension)))throw Error('W6-M2 数据无效');
 const sourceVerifiedAt=iso(s.sourceVerifiedAt,'sourceVerifiedAt'),savedAt=iso(s.savedAt,'savedAt');if(sourceVerifiedAt>savedAt)throw Error('W6-M2 数据无效');
 const canonical=validInput(s.input,s.sourceRows);const total=count(s.totalChecks,'totalChecks'),inc=count(s.incompleteChecks,'incompleteChecks'),labels=count(s.labelFailures,'labelFailures'),evidence=count(s.evidenceFailures,'evidenceFailures'),practice=count(s.practiceFailures,'practiceFailures');if(inc+labels+evidence+practice>total)throw Error('W6-M2 数据无效');
 if(!Array.isArray(s.usedHintTiers)||s.usedHintTiers.some(v=>!['observe','think','partial'].includes(String(v)))||new Set(s.usedHintTiers).size!==s.usedHintTiers.length)throw Error('W6-M2 数据无效');
 if(![null,'selection','label','evidence','practice'].includes(s.firstBlockingConcept as never))throw Error('W6-M2 数据无效');const none=inc===0&&labels===0&&evidence===0&&practice===0;if((s.firstBlockingConcept===null)!==none||(s.firstBlockingConcept==='selection'&&inc===0)||(s.firstBlockingConcept==='label'&&labels===0)||(s.firstBlockingConcept==='evidence'&&evidence===0)||(s.firstBlockingConcept==='practice'&&practice===0))throw Error('W6-M2 数据无效');
 if(s.lastRun===null){if(s.failureSnapshot!==null||s.lastCheckedAt!==null)throw Error('W6-M2 数据无效');}else{const at=iso(s.lastCheckedAt,'lastCheckedAt');if(at<sourceVerifiedAt||at>savedAt||total<1||!same(s.lastRun,canonical)||!same(s.failureSnapshot,canonical.failureSnapshots[0]??null))throw Error('W6-M2 数据无效');}
 return structuredClone(s) as unknown as WeekSixClassificationMissionSession;
}

export function parseWeekSixClassificationWork(value:unknown):WeekSixClassificationWorkV1{
 const s=obj(value,'W6-M2 work');exact(s,['kind','workId','missionId','title','sourceWorkId','sourceVerifiedAt','sourceRows','input','run','createdAt','verifiedAt'],'W6-M2 work');const run=validInput(s.input,s.sourceRows);if(s.kind!=='ai-evidence-classification-v1'||s.workId!=='w6-m2-fan-evidence-classification'||s.missionId!=='w6-m2'||s.sourceWorkId!=='w6-m1-structured-records-table'||typeof s.title!=='string'||!s.title||s.title.length>100||!run.completed||run.state!=='classification-proven'||!same(s.run,run))throw Error('W6-M2 数据无效');const sourceAt=iso(s.sourceVerifiedAt,'sourceVerifiedAt'),created=iso(s.createdAt,'createdAt'),verified=iso(s.verifiedAt,'verifiedAt');if(sourceAt>created||created>verified)throw Error('W6-M2 数据无效');return structuredClone(s) as unknown as WeekSixClassificationWorkV1;
}

export function parseWeekSixClassificationEvidence(value:unknown,input:{mission:MissionProgress|undefined;formalWeekSixRecords:boolean;session:WeekSixClassificationMissionSession|undefined;work:WeekSixClassificationWorkV1|undefined;sourceWork:WeekSixRecordsWorkV1|undefined}):WeekSixClassificationCompletionEvidence{
 const s=obj(value,'W6-M2 evidence');if(!input.mission)throw Error('W6-M2 数据无效');if(s.kind==='legacy-replay-only'){exact(s,['kind','completedAt','sourceVersion','sourceSchemaRevision'],'W6-M2 legacy');const ok=(s.sourceVersion===1&&s.sourceSchemaRevision===null)||(s.sourceVersion===2&&s.sourceSchemaRevision===1)||(s.sourceVersion===3&&Number.isInteger(s.sourceSchemaRevision)&&(s.sourceSchemaRevision as number)>=1&&(s.sourceSchemaRevision as number)<=18);if(!ok||s.completedAt!==input.mission.completedAt||input.work)throw Error('W6-M2 数据无效');iso(s.completedAt,'completedAt');return structuredClone(s) as WeekSixClassificationCompletionEvidence}
 exact(s,['kind','completedAt','verifiedAt','sourceWorkId','sourceVerifiedAt','sourceRows','input','run','workId'],'W6-M2 formal');const run=validInput(s.input,s.sourceRows),completed=iso(s.completedAt,'completedAt'),verified=iso(s.verifiedAt,'verifiedAt');const session=input.session,work=input.work,source=input.sourceWork;
 if(s.kind!=='formal-v3'||!input.formalWeekSixRecords||!session||!work||!source||s.workId!==work.workId||s.sourceWorkId!==source.workId||s.sourceVerifiedAt!==source.verifiedAt||!same(s.sourceRows,source.run.rows)||completed!==input.mission.completedAt||completed>work.createdAt||!run.completed||!same(s.run,run)||session.lastCheckedAt===null||session.lastCheckedAt>session.savedAt||session.savedAt>work.createdAt||work.createdAt>verified||work.verifiedAt!==verified||!same(session.input,s.input)||!same(session.sourceRows,s.sourceRows)||session.sourceVerifiedAt!==s.sourceVerifiedAt||!same(session.lastRun,run)||!same(work.input,s.input)||!same(work.sourceRows,s.sourceRows)||work.sourceVerifiedAt!==s.sourceVerifiedAt||!same(work.run,run))throw Error('W6-M2 数据无效');return structuredClone(s) as WeekSixClassificationCompletionEvidence;
}
