import { describe,expect,it,vi } from 'vitest';
import { formalW6M4Completion,formalW6M5Completion } from '../../e2e/support/w6m1Prerequisite';
import { parseWeekSixRecordsPython,SOLVED_WEEK_SIX_RECORDS_PYTHON } from '../engine/weekSixRecordsPythonGrammar';
import { runWeekSixArchive,type WeekSixArchiveInput } from '../engine/weekSixArchiveContract';
import { completeMission,getWeekSixArchiveAccess,hasValidFormalWeekSixArchiveCompletion,serializeProgress } from './progress';
import { migrateProgress,parseProgress } from './schema';
import { getWeeklyReport } from './weeklyReport';
import { createWeekSixArchiveSession,recordWeekSixArchiveRun,updateWeekSixArchiveCode,updateWeekSixArchiveInput } from './weekSixArchiveSession';
const at=(s:number)=>`2030-01-02T04:05:${String(s).padStart(2,'0')}.000Z`;
const solved:WeekSixArchiveInput={brief:{scope:'all-three',factIds:['attempt-one','attempt-two','attempt-three'],constraintIds:['provided-only','mark-insufficient'],format:'event-table'},reviews:[{claimId:'first-and-third',verdict:'supported',evidenceIds:['run-first','run-third'],disposition:'keep-original'},{claimId:'second-therefore-passed',verdict:'conflicting',evidenceIds:['m2-second-not-passed'],disposition:'revise-second-result'},{claimId:'exactly-thirty-minutes',verdict:'insufficient',evidenceIds:['provided-material-scope'],disposition:'cannot-confirm'}]};
describe('W6-M5 formal archive progress',()=>{
  it('seals the actual Worker run, brief and review as the terminal formal work',()=>{const base=parseProgress(formalW6M4Completion()),source=base.works['w6-m4-second-attempt-review']!;let session=createWeekSixArchiveSession(source,at(10));session=updateWeekSixArchiveCode(session,SOLVED_WEEK_SIX_RECORDS_PYTHON,at(11));session=updateWeekSixArchiveInput(session,solved,at(11));const parsed=parseWeekSixRecordsPython(session.pythonCode);if('state'in parsed)throw Error('fixture');const worker={trace:parsed.trace,run:parsed.run};session=recordWeekSixArchiveRun(session,worker,runWeekSixArchive(session.pythonCode,worker,solved,session.source),at(12));vi.setSystemTime(new Date(at(13)));const completed=completeMission({...base,sessions:{...base.sessions,'w6-m5':session},savedAt:at(12)},'w6-m5',{stars:3,hintsUsed:0});expect(completed).toMatchObject({schemaRevision:22,missions:{'w6-m5':{status:'completed'}},missionCompletionEvidence:{'w6-m5':{kind:'formal-v3',workId:'w6-m5-journey-archive'}},works:{'w6-m5-journey-archive':{kind:'python-ai-archive-v1'}}});expect(hasValidFormalWeekSixArchiveCompletion(completed)).toBe(true);expect(parseProgress(serializeProgress(completed))).toEqual(completed);expect(getWeeklyReport(completed,6).weekSixArchive).toMatchObject({runs:1,workSaved:true,proof:'formal-v3'});expect(completeMission(completed,'w6-m5',{stars:1,hintsUsed:3})).toBe(completed)});
  it('preserves an old placeholder only as history',()=>{const raw=JSON.parse(formalW6M4Completion());raw.schemaRevision=21;raw.missions['w6-m5']={status:'completed',stars:2,attempts:1,hintsUsed:0,completedAt:at(9)};const migrated=parseProgress(JSON.stringify(raw));expect(migrated.schemaRevision).toBe(22);expect(migrated.missionCompletionEvidence['w6-m5']).toMatchObject({kind:'legacy-replay-only',sourceSchemaRevision:21});expect(migrated.sessions['w6-m5']).toBeUndefined();expect(getWeekSixArchiveAccess(migrated)).toEqual({kind:'formal',upgradingLegacy:true})});
  it('persists a review disposition failure through the complete progress schema',()=>{const base=parseProgress(formalW6M4Completion()),source=base.works['w6-m4-second-attempt-review']!,stamp=(offset:number)=>new Date(new Date(source.verifiedAt).getTime()+offset).toISOString();const wrong=structuredClone(solved);wrong.reviews[1]!.disposition='keep-original';let session=createWeekSixArchiveSession(source,stamp(1));session=updateWeekSixArchiveCode(session,SOLVED_WEEK_SIX_RECORDS_PYTHON,stamp(2));session=updateWeekSixArchiveInput(session,wrong,stamp(3));const parsed=parseWeekSixRecordsPython(session.pythonCode);if('state'in parsed)throw Error('fixture');const worker={trace:parsed.trace,run:parsed.run};session=recordWeekSixArchiveRun(session,worker,runWeekSixArchive(session.pythonCode,worker,wrong,session.source),stamp(4));const persisted=migrateProgress({...base,sessions:{...base.sessions,'w6-m5':session},savedAt:stamp(4)});expect(persisted.sessions['w6-m5']?.lastRun?.state).toBe('review-disposition-conflict');expect(parseProgress(serializeProgress(persisted))).toEqual(persisted)});
  it('round-trips the complete fixture and rejects source/proof tampering',()=>{const completed=parseProgress(formalW6M5Completion('step-list'));expect(hasValidFormalWeekSixArchiveCompletion(completed)).toBe(true);for(const mutate of [(p:any)=>p.sessions['w6-m5'].pythonCode+='\n# changed',(p:any)=>p.works['w6-m5-journey-archive'].run.completed=false,(p:any)=>p.missionCompletionEvidence['w6-m5'].sourceVerifiedAt=at(1)]){const raw=JSON.parse(serializeProgress(completed));mutate(raw);expect(()=>parseProgress(JSON.stringify(raw))).toThrow()}});
});
