import { parseWeekSixRecordsPython } from '../engine/weekSixRecordsPythonGrammar';
import { hasExactKeys,isPlainRecord,isSafeCount,isUtcIso,sameData } from '../engine/strictData';
import type { MissionProgress, WeekSixRecordsCompletionEvidence, WeekSixRecordsWorkV1 } from './types';
import type { WeekSixRecordsMissionSession } from './weekSixRecordsSession';
function bad():never{throw Error('W6-M1 data invalid')}
const same=sameData;
function object(value:unknown):Record<string,unknown>{if(!isPlainRecord(value))bad();return value}
function iso(value:unknown){if(!isUtcIso(value))bad();return value}
function count(value:unknown){if(!isSafeCount(value))bad();return value}
function exact(source:Record<string,unknown>,keys:readonly string[]){if(!hasExactKeys(source,keys))bad();}
function runnable(code:unknown){if(typeof code!=='string')bad();const parsed=parseWeekSixRecordsPython(code);if('state'in parsed)bad();return parsed}
export function parseWeekSixRecordsSession(value:unknown):WeekSixRecordsMissionSession{const source=object(value);const allowed=['kind','pythonCode','lastCanonicalTrace','lastWorkerTrace','lastRun','failureSnapshot','totalRuns','recordFailures','fieldFailures','validationFailures','runnerInfrastructureFailures','conditionObservationUses','usedHintTiers','firstBlockingConcept','lastRunAt','savedAt'];exact(source,allowed);if(source.kind!=='python-structured-records-v1'||typeof source.pythonCode!=='string')bad();const total=count(source.totalRuns),recordFailures=count(source.recordFailures),fieldFailures=count(source.fieldFailures),validationFailures=count(source.validationFailures);count(source.runnerInfrastructureFailures);if(recordFailures+fieldFailures>total)bad();const savedAt=iso(source.savedAt);const parsed=parseWeekSixRecordsPython(source.pythonCode);if(!Array.isArray(source.lastCanonicalTrace)||!Array.isArray(source.lastWorkerTrace)||!Array.isArray(source.conditionObservationUses)||!Array.isArray(source.usedHintTiers)||source.usedHintTiers.some((tier)=>!['observe','think','partial'].includes(String(tier)))||new Set(source.usedHintTiers).size!==source.usedHintTiers.length)bad();if(![null,'record-shape','field-read','python-structure'].includes(source.firstBlockingConcept as never))bad();const noFailure=recordFailures===0&&fieldFailures===0&&validationFailures===0;if((source.firstBlockingConcept===null)!==noFailure||(source.firstBlockingConcept==='record-shape'&&recordFailures===0)||(source.firstBlockingConcept==='field-read'&&fieldFailures===0)||(source.firstBlockingConcept==='python-structure'&&validationFailures===0))bad();if(source.lastRun===null){if(source.lastCanonicalTrace.length||source.lastWorkerTrace.length||source.failureSnapshot!==null||source.lastRunAt!==null)bad();}else{if('state'in parsed)bad();const lastRunAt=iso(source.lastRunAt);if(lastRunAt>savedAt||total<1||!same(source.lastCanonicalTrace,parsed.trace)||!same(source.lastWorkerTrace,parsed.trace)||!same(source.lastRun,parsed.run)||!same(source.failureSnapshot,parsed.run.failureSnapshots[0]??null))bad();}
  for(const raw of source.conditionObservationUses){const use=object(raw);exact(use,['snapshotId','pythonCode','canonicalTrace','workerTrace','run','usedAt']);if(typeof use.snapshotId!=='string'||use.pythonCode!==source.pythonCode||!same(use.canonicalTrace,source.lastCanonicalTrace)||!same(use.workerTrace,source.lastWorkerTrace)||!same(use.run,source.lastRun)||use.snapshotId!==(source.failureSnapshot as any)?.snapshotId||iso(use.usedAt)>savedAt)bad();}
  return structuredClone(source) as unknown as WeekSixRecordsMissionSession;}
export function parseWeekSixRecordsWork(value:unknown):WeekSixRecordsWorkV1{const source=object(value);exact(source,['kind','workId','missionId','title','pythonCode','canonicalTrace','workerTrace','run','createdAt','verifiedAt']);const parsed=runnable(source.pythonCode);if(source.kind!=='python-structured-records-v1'||source.workId!=='w6-m1-structured-records-table'||source.missionId!=='w6-m1'||typeof source.title!=='string'||!source.title||source.title.length>100||!parsed.run.completed||parsed.run.state!=='records-proven'||!same(source.canonicalTrace,parsed.trace)||!same(source.workerTrace,parsed.trace)||!same(source.run,parsed.run))bad();const createdAt=iso(source.createdAt),verifiedAt=iso(source.verifiedAt);if(createdAt>verifiedAt)bad();return structuredClone(source) as unknown as WeekSixRecordsWorkV1;}
export function parseWeekSixRecordsEvidence(value:unknown,input:{mission:MissionProgress|undefined;formalWeekFiveStory:boolean;session:WeekSixRecordsMissionSession|undefined;work:WeekSixRecordsWorkV1|undefined}):WeekSixRecordsCompletionEvidence{const source=object(value);if(!input.mission)bad();if(source.kind==='legacy-replay-only'){exact(source,['kind','completedAt','sourceVersion','sourceSchemaRevision']);const valid=(source.sourceVersion===1&&source.sourceSchemaRevision===null)||(source.sourceVersion===2&&source.sourceSchemaRevision===1)||(source.sourceVersion===3&&Number.isInteger(source.sourceSchemaRevision)&&(source.sourceSchemaRevision as number)>=1&&(source.sourceSchemaRevision as number)<=17);if(!valid||source.completedAt!==input.mission.completedAt||input.work)bad();iso(source.completedAt);return structuredClone(source) as WeekSixRecordsCompletionEvidence;}exact(source,['kind','completedAt','verifiedAt','pythonCode','canonicalTrace','workerTrace','run','workId']);const parsed=runnable(source.pythonCode);const completedAt=iso(source.completedAt),verifiedAt=iso(source.verifiedAt);if(source.kind!=='formal-v3'||!input.formalWeekFiveStory||!input.session||!input.work||source.workId!==input.work.workId||!parsed.run.completed||input.session.failureSnapshot!==null||completedAt!==input.mission.completedAt||completedAt>input.work.createdAt||input.work.createdAt>verifiedAt||input.work.verifiedAt!==verifiedAt||input.session.lastRunAt===null||input.session.lastRunAt>input.session.savedAt||input.session.savedAt>input.work.createdAt||!same(source.canonicalTrace,parsed.trace)||!same(source.workerTrace,parsed.trace)||!same(source.run,parsed.run)||!same(input.session.lastCanonicalTrace,parsed.trace)||!same(input.session.lastWorkerTrace,parsed.trace)||!same(input.session.lastRun,parsed.run)||!same(input.work.canonicalTrace,parsed.trace)||!same(input.work.workerTrace,parsed.trace)||!same(input.work.run,parsed.run)||input.session.pythonCode!==parsed.pythonCode||input.work.pythonCode!==parsed.pythonCode)bad();return structuredClone(source) as WeekSixRecordsCompletionEvidence;}
