import { createEmptyWeekSixFactCheckInput,deriveWeekSixFactCheckSource,runWeekSixFactCheck,type WeekSixFactCheckFailureSnapshot,type WeekSixFactCheckInput,type WeekSixFactCheckRunResult,type WeekSixFactCheckSource } from '../engine/weekSixFactCheckContract';
import type { WeekSixPromptWorkV1 } from './types';

export interface WeekSixFactCheckMissionSession{kind:'ai-fact-check-report-v1';sourceWorkId:'w6-m3-second-attempt-brief';sourceVerifiedAt:string;source:WeekSixFactCheckSource;input:WeekSixFactCheckInput;lastRun:WeekSixFactCheckRunResult|null;failureSnapshot:WeekSixFactCheckFailureSnapshot|null;totalRuns:number;missingFailures:number;verdictFailures:number;evidenceFailures:number;dispositionFailures:number;usedHintTiers:Array<'observe'|'think'|'partial'>;firstBlockingConcept:'verdict'|'evidence'|'disposition'|null;lastRunAt:string|null;savedAt:string}
const UTC=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/,same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
function time(value:string){if(!UTC.test(value)||new Date(value).toISOString()!==value)throw Error('W6-M4 time must be UTC ISO')}
function after(session:WeekSixFactCheckMissionSession,now:string){time(now);if(now<session.savedAt)throw Error('W6-M4 session time cannot go backwards')}
function inc(value:number){if(!Number.isSafeInteger(value)||value<0||value===Number.MAX_SAFE_INTEGER)throw Error('W6-M4 counter invalid');return value+1}
export function createWeekSixFactCheckSession(work:WeekSixPromptWorkV1,now:string):WeekSixFactCheckMissionSession{time(now);const source=deriveWeekSixFactCheckSource(work);if(source.promptVerifiedAt>now)throw Error('W6-M4 source is newer than session');return{kind:'ai-fact-check-report-v1',sourceWorkId:work.workId,sourceVerifiedAt:work.verifiedAt,source,input:createEmptyWeekSixFactCheckInput(),lastRun:null,failureSnapshot:null,totalRuns:0,missingFailures:0,verdictFailures:0,evidenceFailures:0,dispositionFailures:0,usedHintTiers:[],firstBlockingConcept:null,lastRunAt:null,savedAt:now}}
export function updateWeekSixFactCheckInput(session:WeekSixFactCheckMissionSession,input:WeekSixFactCheckInput,now:string):WeekSixFactCheckMissionSession{after(session,now);const preview=runWeekSixFactCheck(input,session.source);if(preview.state==='source-invalid'||preview.state==='input-invalid')throw Error('W6-M4 review input invalid');if(same(input,session.input))return structuredClone(session);return{...structuredClone(session),input:structuredClone(input),lastRun:null,failureSnapshot:null,lastRunAt:null,savedAt:now}}
export function recordWeekSixFactCheckRun(session:WeekSixFactCheckMissionSession,input:WeekSixFactCheckInput,run:WeekSixFactCheckRunResult,now:string):WeekSixFactCheckMissionSession{after(session,now);if(!same(input,session.input))throw Error('W6-M4 run must use current saved review input');const canonical=runWeekSixFactCheck(session.input,session.source);if(canonical.state==='source-invalid'||canonical.state==='input-invalid'||!same(run,canonical))throw Error('W6-M4 run must be deterministically recomputed');const next=structuredClone(session);next.lastRun=structuredClone(canonical);next.failureSnapshot=structuredClone(canonical.failureSnapshots[0]??null);next.totalRuns=inc(next.totalRuns);next.lastRunAt=now;next.savedAt=now;const field=canonical.failureSnapshots[0]?.field,concept=field==='verdict'||field==='evidence'||field==='disposition'?field:null;if(canonical.state.endsWith('-missing'))next.missingFailures=inc(next.missingFailures);else if(concept==='verdict')next.verdictFailures=inc(next.verdictFailures);else if(concept==='evidence')next.evidenceFailures=inc(next.evidenceFailures);else if(concept==='disposition')next.dispositionFailures=inc(next.dispositionFailures);if(next.firstBlockingConcept===null&&concept!==null)next.firstBlockingConcept=concept;return next}
export function recordWeekSixFactCheckHint(session:WeekSixFactCheckMissionSession,tier:'observe'|'think'|'partial',now:string):WeekSixFactCheckMissionSession{after(session,now);if(!['observe','think','partial'].includes(tier))throw Error('W6-M4 hint tier invalid');const next=structuredClone(session);if(!next.usedHintTiers.includes(tier))next.usedHintTiers.push(tier);next.savedAt=now;return next}
