import { deriveWeekSixFactCheckSource,runWeekSixFactCheck } from '../engine/weekSixFactCheckContract';
import type { MissionProgress,WeekSixFactCheckCompletionEvidence,WeekSixFactCheckWorkV1,WeekSixPromptWorkV1 } from './types';
import type { WeekSixFactCheckMissionSession } from './weekSixFactCheckSession';
import { hasExactKeys,isLegacyReplayEvidence,isPlainRecord,isSafeCount,isUtcIso,sameData } from '../engine/strictData';

const bad=():never=>{throw Error('W6-M4 data invalid')};
function obj(value:unknown):Record<string,unknown>{if(!isPlainRecord(value))bad();return value as Record<string,unknown>}
function iso(value:unknown):string{if(!isUtcIso(value))bad();return value as string}
function count(value:unknown){if(!isSafeCount(value))bad();return value as number}
function valid(input:unknown,source:unknown){const run=runWeekSixFactCheck(input,source);if(run.state==='source-invalid'||run.state==='input-invalid')bad();return run}
const seal=(value:Record<string,unknown>,run:unknown)=>[value.sourceWorkId,value.sourceVerifiedAt,value.source,value.input,run];
export function parseWeekSixFactCheckSession(value:unknown):WeekSixFactCheckMissionSession{const session=obj(value);if(!hasExactKeys(session,['kind','sourceWorkId','sourceVerifiedAt','source','input','lastRun','failureSnapshot','totalRuns','missingFailures','verdictFailures','evidenceFailures','dispositionFailures','usedHintTiers','firstBlockingConcept','lastRunAt','savedAt'])||session.kind!=='ai-fact-check-report-v1'||session.sourceWorkId!=='w6-m3-second-attempt-brief')bad();const sourceAt=iso(session.sourceVerifiedAt),savedAt=iso(session.savedAt),source=obj(session.source);if(sourceAt>savedAt||source.promptVerifiedAt!==sourceAt)bad();const canonical=valid(session.input,source),counts=[session.missingFailures,session.verdictFailures,session.evidenceFailures,session.dispositionFailures].map(count),total=count(session.totalRuns),failures=counts.reduce((a,b)=>a+b,0),first=session.firstBlockingConcept;if(failures>total||!Array.isArray(session.usedHintTiers)||session.usedHintTiers.some(value=>typeof value!=='string'||!['observe','think','partial'].includes(value))||new Set(session.usedHintTiers).size!==session.usedHintTiers.length||![null,'verdict','evidence','disposition'].includes(first as never)||(first===null)!==(failures===0))bad();if(first!==null&&!({verdict:counts[1],evidence:counts[2],disposition:counts[3]} as Record<string,number>)[first as string]&&!counts[0])bad();if(session.lastRun===null){if(session.failureSnapshot!==null||session.lastRunAt!==null)bad()}else{const runAt=iso(session.lastRunAt);if(runAt<sourceAt||runAt>savedAt||!total||!sameData(session.lastRun,canonical)||!sameData(session.failureSnapshot,canonical.failureSnapshots[0]??null))bad()}return structuredClone(session) as unknown as WeekSixFactCheckMissionSession}
export function parseWeekSixFactCheckWork(value:unknown):WeekSixFactCheckWorkV1{const work=obj(value);if(!hasExactKeys(work,['kind','workId','missionId','title','sourceWorkId','sourceVerifiedAt','source','input','run','createdAt','verifiedAt']))bad();const run=valid(work.input,work.source),source=obj(work.source),sourceAt=iso(work.sourceVerifiedAt),createdAt=iso(work.createdAt),verifiedAt=iso(work.verifiedAt);if(work.kind!=='ai-fact-check-report-v1'||work.workId!=='w6-m4-second-attempt-review'||work.missionId!=='w6-m4'||work.sourceWorkId!=='w6-m3-second-attempt-brief'||typeof work.title!=='string'||!work.title||work.title.length>100||!run.completed||!sameData(work.run,run)||source.promptVerifiedAt!==sourceAt||sourceAt>createdAt||createdAt>verifiedAt)bad();return structuredClone(work) as unknown as WeekSixFactCheckWorkV1}
export function parseWeekSixFactCheckEvidence(value:unknown,input:{mission:MissionProgress|undefined;formalWeekSixPrompt:boolean;session:WeekSixFactCheckMissionSession|undefined;work:WeekSixFactCheckWorkV1|undefined;sourceWork:WeekSixPromptWorkV1|undefined}):WeekSixFactCheckCompletionEvidence{const evidence=obj(value),mission=input.mission;if(!mission)return bad();if(evidence.kind==='legacy-replay-only'){if(!isLegacyReplayEvidence(evidence,mission,input.work,21))bad();return structuredClone(evidence) as WeekSixFactCheckCompletionEvidence}if(!hasExactKeys(evidence,['kind','completedAt','verifiedAt','sourceWorkId','sourceVerifiedAt','source','input','run','workId']))bad();const run=valid(evidence.input,evidence.source),completedAt=iso(evidence.completedAt),verifiedAt=iso(evidence.verifiedAt),session=input.session,work=input.work,sourceWork=input.sourceWork;if(evidence.kind!=='formal-v3'||!input.formalWeekSixPrompt||!session||!work||!sourceWork||!run.completed||!sameData(evidence.run,run)||evidence.workId!==work.workId||evidence.sourceWorkId!==sourceWork.workId||evidence.sourceVerifiedAt!==sourceWork.verifiedAt||completedAt!==mission.completedAt||!sameData(evidence.source,deriveWeekSixFactCheckSource(sourceWork))||!sameData(seal(evidence,evidence.run),seal(session as unknown as Record<string,unknown>,session.lastRun))||!sameData(seal(evidence,evidence.run),seal(work as unknown as Record<string,unknown>,work.run))||session.lastRunAt===null||completedAt>work.createdAt||session.lastRunAt>session.savedAt||session.savedAt>work.createdAt||work.createdAt>verifiedAt||work.verifiedAt!==verifiedAt)bad();return structuredClone(evidence) as WeekSixFactCheckCompletionEvidence}
