import { DEFAULT_WEEK_SIX_RECORDS_PYTHON,parseWeekSixRecordsDraftEnvelope } from '../engine/weekSixRecordsPythonGrammar';
import { createEmptyWeekSixArchiveInput,deriveWeekSixArchiveSource,runWeekSixArchive,toWeekSixArchiveCoreRun,type WeekSixArchiveCoreRunResult,type WeekSixArchiveFailureSnapshot,type WeekSixArchiveInput,type WeekSixArchiveRunResult,type WeekSixArchiveSource } from '../engine/weekSixArchiveContract';
import type { WeekSixRecordsPythonRun } from '../engine/weekSixRecordsPythonRunner';
import type { WeekSixFactCheckWorkV1 } from './types';

export interface WeekSixArchiveMissionSession{kind:'python-ai-archive-v1';source:WeekSixArchiveSource;pythonCode:string;workerTrace:WeekSixRecordsPythonRun['trace']|null;workerRun:WeekSixRecordsPythonRun['run']|null;workerRunAt:string|null;input:WeekSixArchiveInput;lastRun:WeekSixArchiveCoreRunResult|null;failureSnapshot:WeekSixArchiveFailureSnapshot|null;totalRuns:number;pythonFailures:number;briefFailures:number;reviewFailures:number;usedHintTiers:Array<'observe'|'think'|'partial'>;firstBlockingStage:'python'|'brief'|'review'|null;lastRunAt:string|null;savedAt:string}
const UTC=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/,same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
function time(value:string){if(!UTC.test(value)||new Date(value).toISOString()!==value)throw Error('W6-M5 time must be UTC ISO')}
function after(session:WeekSixArchiveMissionSession,now:string){time(now);if(now<session.savedAt)throw Error('W6-M5 session time cannot go backwards')}
function inc(value:number){if(!Number.isSafeInteger(value)||value<0||value===Number.MAX_SAFE_INTEGER)throw Error('W6-M5 counter invalid');return value+1}
export function createWeekSixArchiveSession(work:WeekSixFactCheckWorkV1,now:string):WeekSixArchiveMissionSession{time(now);const source=deriveWeekSixArchiveSource(work);if(source.factCheckVerifiedAt>now)throw Error('W6-M5 source is newer than session');return{kind:'python-ai-archive-v1',source,pythonCode:DEFAULT_WEEK_SIX_RECORDS_PYTHON,workerTrace:null,workerRun:null,workerRunAt:null,input:createEmptyWeekSixArchiveInput(),lastRun:null,failureSnapshot:null,totalRuns:0,pythonFailures:0,briefFailures:0,reviewFailures:0,usedHintTiers:[],firstBlockingStage:null,lastRunAt:null,savedAt:now}}
export function updateWeekSixArchiveCode(session:WeekSixArchiveMissionSession,code:string,now:string):WeekSixArchiveMissionSession{after(session,now);parseWeekSixRecordsDraftEnvelope(code);if(code===session.pythonCode)return structuredClone(session);return{...structuredClone(session),pythonCode:code,workerTrace:null,workerRun:null,workerRunAt:null,lastRun:null,failureSnapshot:null,lastRunAt:null,savedAt:now}}
export function updateWeekSixArchiveInput(session:WeekSixArchiveMissionSession,input:WeekSixArchiveInput,now:string):WeekSixArchiveMissionSession{after(session,now);const check=runWeekSixArchive(session.pythonCode,null,input,session.source);if(check.state==='input-invalid')throw Error('W6-M5 archive input invalid');if(same(input,session.input))return structuredClone(session);return{...structuredClone(session),input:structuredClone(input),lastRun:null,failureSnapshot:null,lastRunAt:null,savedAt:now}}
export function recordWeekSixArchiveRun(session:WeekSixArchiveMissionSession,worker:WeekSixRecordsPythonRun|null,run:WeekSixArchiveRunResult,now:string):WeekSixArchiveMissionSession{after(session,now);const canonical=runWeekSixArchive(session.pythonCode,worker,session.input,session.source);if(canonical.state==='source-invalid'||canonical.state==='input-invalid'||canonical.state==='python-worker-missing'||canonical.state==='python-worker-stale'||!same(run,canonical))throw Error('W6-M5 run must bind current code, Worker result and choices');const next=structuredClone(session);next.workerTrace=worker?structuredClone(worker.trace):null;next.workerRun=worker?structuredClone(worker.run):null;next.workerRunAt=worker?now:null;next.lastRun=toWeekSixArchiveCoreRun(canonical);next.failureSnapshot=canonical.failureSnapshots[0]??null;next.totalRuns=inc(next.totalRuns);next.lastRunAt=now;next.savedAt=now;const field=canonical.failureSnapshots[0]?.field,stage=field==='python'?'python':field==='scope'||field==='facts'||field==='constraints'||field==='format'?'brief':field?'review':null;if(stage==='python')next.pythonFailures=inc(next.pythonFailures);if(stage==='brief')next.briefFailures=inc(next.briefFailures);if(stage==='review')next.reviewFailures=inc(next.reviewFailures);if(next.firstBlockingStage===null&&stage)next.firstBlockingStage=stage;return next}
export function recordWeekSixArchiveHint(session:WeekSixArchiveMissionSession,tier:'observe'|'think'|'partial',now:string):WeekSixArchiveMissionSession{after(session,now);if(!['observe','think','partial'].includes(tier))throw Error('W6-M5 hint tier invalid');const next=structuredClone(session);if(!next.usedHintTiers.includes(tier))next.usedHintTiers.push(tier);next.savedAt=now;return next}
