import type { WeekSixRecordsFailureSnapshot, WeekSixRecordsRunResult, WeekSixRecordsTraceItem } from '../engine/weekSixRecordsContract';
import { parseWeekSixRecordsDraftEnvelope, parseWeekSixRecordsPython } from '../engine/weekSixRecordsPythonGrammar';
export { createWeekSixRecordsSession } from './weekSixRecordsSessionFactory';

export interface WeekSixRecordsObservationUse { snapshotId:string;pythonCode:string;canonicalTrace:WeekSixRecordsTraceItem[];workerTrace:WeekSixRecordsTraceItem[];run:WeekSixRecordsRunResult;usedAt:string }
export interface WeekSixRecordsMissionSession {
  kind:'python-structured-records-v1';pythonCode:string;lastCanonicalTrace:WeekSixRecordsTraceItem[];lastWorkerTrace:WeekSixRecordsTraceItem[];lastRun:WeekSixRecordsRunResult|null;failureSnapshot:WeekSixRecordsFailureSnapshot|null;
  totalRuns:number;recordFailures:number;fieldFailures:number;validationFailures:number;runnerInfrastructureFailures:number;conditionObservationUses:WeekSixRecordsObservationUse[];usedHintTiers:Array<'observe'|'think'|'partial'>;firstBlockingConcept:'record-shape'|'field-read'|'python-structure'|null;lastRunAt:string|null;savedAt:string;
}
type RunInput={canonicalTrace:WeekSixRecordsTraceItem[];workerTrace:WeekSixRecordsTraceItem[];run:WeekSixRecordsRunResult};
const UTC=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
function time(value:string){if(!UTC.test(value)||new Date(value).toISOString()!==value)throw Error('W6-M1 会话时间必须是标准 UTC ISO。');return value;}
function after(session:WeekSixRecordsMissionSession,now:string){time(now);if(now<session.savedAt)throw Error('W6-M1 会话时间不得倒退。');}
function increment(value:number){if(!Number.isSafeInteger(value)||value<0||value===Number.MAX_SAFE_INTEGER)throw Error('W6-M1 会话计数超出安全范围。');return value+1;}
function runnable(code:string){const parsed=parseWeekSixRecordsPython(code);if('state'in parsed)throw Error('W6-M1 当前 Python 结构无效。');return parsed;}
export function updateWeekSixRecordsCode(session:WeekSixRecordsMissionSession,code:string,now:string):WeekSixRecordsMissionSession{after(session,now);parseWeekSixRecordsDraftEnvelope(code);if(code===session.pythonCode)return structuredClone(session);return{...structuredClone(session),pythonCode:code,lastCanonicalTrace:[],lastWorkerTrace:[],lastRun:null,failureSnapshot:null,conditionObservationUses:[],lastRunAt:null,savedAt:now};}
export function recordWeekSixRecordsRun(session:WeekSixRecordsMissionSession,input:RunInput,now:string):WeekSixRecordsMissionSession{after(session,now);const parsed=runnable(session.pythonCode);if(!input||!same(input.canonicalTrace,parsed.trace)||!same(input.workerTrace,parsed.trace)||!same(input.run,parsed.run))throw Error('W6-M1 运行证据必须来自当前保存的 Python 输入。');const next=structuredClone(session);next.lastCanonicalTrace=structuredClone(parsed.trace);next.lastWorkerTrace=structuredClone(parsed.trace);next.lastRun=structuredClone(parsed.run);next.failureSnapshot=structuredClone(parsed.run.failureSnapshots[0]??null);next.conditionObservationUses=[];next.totalRuns=increment(next.totalRuns);if(parsed.run.state==='record-shape-conflict')next.recordFailures=increment(next.recordFailures);if(parsed.run.state==='field-read-conflict')next.fieldFailures=increment(next.fieldFailures);if(next.firstBlockingConcept===null)next.firstBlockingConcept=parsed.run.state==='record-shape-conflict'?'record-shape':parsed.run.state==='field-read-conflict'?'field-read':null;next.lastRunAt=now;next.savedAt=now;return next;}
export function recordWeekSixRecordsValidationFailure(session:WeekSixRecordsMissionSession,now:string){after(session,now);if(!('state'in parseWeekSixRecordsPython(session.pythonCode)))throw Error('W6-M1 只有无效草稿才能记录验证失败。');const next=structuredClone(session);next.validationFailures=increment(next.validationFailures);if(next.firstBlockingConcept===null)next.firstBlockingConcept='python-structure';next.savedAt=now;return next;}
export function recordWeekSixRecordsInfrastructureFailure(session:WeekSixRecordsMissionSession,input:{executionStarted:boolean},now:string){after(session,now);if(!input||typeof input.executionStarted!=='boolean')throw Error('W6-M1 基础设施失败记录无效。');const next=structuredClone(session);next.runnerInfrastructureFailures=increment(next.runnerInfrastructureFailures);if(input.executionStarted)next.totalRuns=increment(next.totalRuns);next.savedAt=now;return next;}
export function recordWeekSixRecordsObservation(session:WeekSixRecordsMissionSession,now:string){after(session,now);const parsed=runnable(session.pythonCode);const snapshot=session.failureSnapshot;if(!snapshot||!session.lastRun||!same(session.lastCanonicalTrace,parsed.trace)||!same(session.lastWorkerTrace,parsed.trace)||!same(session.lastRun,parsed.run))throw Error('W6-M1 没有绑定当前代码的失败快照。');const next=structuredClone(session);if(!next.conditionObservationUses.some((use)=>use.snapshotId===snapshot.snapshotId))next.conditionObservationUses.push({snapshotId:snapshot.snapshotId,pythonCode:next.pythonCode,canonicalTrace:structuredClone(parsed.trace),workerTrace:structuredClone(parsed.trace),run:structuredClone(parsed.run),usedAt:now});next.savedAt=now;return next;}
export function recordWeekSixRecordsHint(session:WeekSixRecordsMissionSession,tier:'observe'|'think'|'partial',now:string){after(session,now);const next=structuredClone(session);if(!next.usedHintTiers.includes(tier))next.usedHintTiers.push(tier);next.savedAt=now;return next;}
