import { YUNZHAN_DIALOGUE_BLOCK_TYPES, compileYunzhanDialogueDraft, runYunzhanDialogueForDraft, validateYunzhanDialogueDraft, type YunzhanDialogueWorkspaceDraftV1 } from '../blockly/weekThreeYunzhanDialogueContract';
import type { MissionSession, YunzhanDialogueMissionSession } from './types';

const object = (value: unknown, field: string): Record<string, unknown> => { if (typeof value !== 'object' || value === null || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) throw new Error(`${field}必须是对象`); return value as Record<string, unknown>; };
const exact = (value: Record<string, unknown>, keys: readonly string[], field: string) => { if (Object.keys(value).length !== keys.length || keys.some((key) => !Object.prototype.hasOwnProperty.call(value, key))) throw new Error(`${field}字段无效`); };
const count = (value: unknown, field: string) => { if (!Number.isSafeInteger(value) || (value as number) < 0) throw new Error(`${field}必须是非负安全整数`); return value as number; };
const date = (value: unknown, field: string) => { if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) || Number.isNaN(new Date(value).getTime()) || new Date(value).toISOString() !== value) throw new Error(`${field}必须是ISO日期`); return value; };
const same = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);

export function parseYunzhanDialogueWorkspace(value: unknown, field = 'sessions.w3-m3.workspace'): YunzhanDialogueWorkspaceDraftV1 {
  const source = object(value, field); exact(source, ['version', 'missionId', 'blocks'], field);
  if (source.version !== 1 || source.missionId !== 'w3-m3' || !Array.isArray(source.blocks)) throw new Error(`${field}无效`);
  const blocks = source.blocks.map((item, index) => { const block = object(item, `${field}.blocks[${index}]`); exact(block, ['id', 'type', 'previousId', 'nextId', 'parentBlockId', 'conditionBlockId', 'branch', 'x', 'y'], `${field}.blocks[${index}]`); if (typeof block.id !== 'string' || !block.id || block.id.length > 128 || typeof block.type !== 'string' || !YUNZHAN_DIALOGUE_BLOCK_TYPES.includes(block.type as typeof YUNZHAN_DIALOGUE_BLOCK_TYPES[number]) || ![block.previousId, block.nextId, block.parentBlockId, block.conditionBlockId].every((id) => id === null || (typeof id === 'string' && id.length > 0 && id.length <= 128)) || (block.branch !== null && block.branch !== 'then' && block.branch !== 'else') || typeof block.x !== 'number' || !Number.isFinite(block.x) || typeof block.y !== 'number' || !Number.isFinite(block.y)) throw new Error(`${field}积木无效`); return block; });
  const parsed = { version: 1 as const, missionId: 'w3-m3' as const, blocks } as unknown as YunzhanDialogueWorkspaceDraftV1;
  validateYunzhanDialogueDraft(parsed); return parsed;
}

export function parseYunzhanDialogueSession(value: unknown): YunzhanDialogueMissionSession {
  const source = object(value, 'sessions.w3-m3'); exact(source, ['workspace', 'lastTrace', 'lastRun', 'totalRuns', 'runtimeFailures', 'compileFailures', 'usedHintTiers', 'conceptFailures', 'lastRunAt', 'savedAt', 'roundResults', 'failureSnapshot', 'conditionObservationUses'], 'sessions.w3-m3');
  const workspace = parseYunzhanDialogueWorkspace(source.workspace); const trace = compileYunzhanDialogueDraft(workspace);
  if (!Array.isArray(source.lastTrace) || !Array.isArray(source.roundResults) || !Array.isArray(source.usedHintTiers) || source.usedHintTiers.some((tier) => tier !== 'observe' && tier !== 'think' && tier !== 'partial') || new Set(source.usedHintTiers).size !== source.usedHintTiers.length) throw new Error('sessions.w3-m3运行记录无效');
  const totalRuns = count(source.totalRuns, 'sessions.w3-m3.totalRuns'); const runtimeFailures = count(source.runtimeFailures, 'sessions.w3-m3.runtimeFailures'); const compileFailures = count(source.compileFailures, 'sessions.w3-m3.compileFailures'); const failures = object(source.conceptFailures, 'sessions.w3-m3.conceptFailures'); exact(failures, ['programStructure', 'branchRouting', 'completeness'], 'sessions.w3-m3.conceptFailures');
  const conceptFailures = { programStructure: count(failures.programStructure, 'programStructure'), branchRouting: count(failures.branchRouting, 'branchRouting'), completeness: count(failures.completeness, 'completeness') };
  if (compileFailures !== conceptFailures.programStructure || runtimeFailures !== conceptFailures.branchRouting + conceptFailures.completeness || runtimeFailures > totalRuns) throw new Error('sessions.w3-m3累计失败证据不一致');
  if (!Array.isArray(source.conditionObservationUses) || source.conditionObservationUses.length > 1000) throw new Error('sessions.w3-m3.conditionObservationUses无效');
  const uses = source.conditionObservationUses.map((entry, index) => { const use = object(entry, `sessions.w3-m3.conditionObservationUses[${index}]`); exact(use, ['snapshotId', 'usedAt', 'workspace'], `sessions.w3-m3.conditionObservationUses[${index}]`); if (typeof use.snapshotId !== 'string' || !use.snapshotId) throw new Error('sessions.w3-m3.conditionObservationUses快照无效'); const historical = parseYunzhanDialogueWorkspace(use.workspace, `sessions.w3-m3.conditionObservationUses[${index}].workspace`); const replay = runYunzhanDialogueForDraft(historical); if (replay.completed || replay.failureSnapshot?.snapshotId !== use.snapshotId) throw new Error('sessions.w3-m3.conditionObservationUses必须对应可重放失败快照'); return { snapshotId: use.snapshotId, usedAt: date(use.usedAt, `sessions.w3-m3.conditionObservationUses[${index}].usedAt`), workspace: historical }; });
  if (new Set(uses.map((use) => use.snapshotId)).size !== uses.length || runtimeFailures < uses.length) throw new Error('sessions.w3-m3观察记录无效');
  if (totalRuns === 0) { if (source.lastRun !== null || source.lastTrace.length !== 0 || source.roundResults.length !== 0 || source.failureSnapshot !== null || source.lastRunAt !== null || uses.length !== 0) throw new Error('sessions.w3-m3零次运行不得有运行证据'); return { workspace, lastTrace: [], lastRun: null, totalRuns, runtimeFailures, compileFailures, usedHintTiers: source.usedHintTiers as MissionSession['usedHintTiers'], conceptFailures, lastRunAt: null, savedAt: date(source.savedAt, 'sessions.w3-m3.savedAt'), roundResults: [], failureSnapshot: null, conditionObservationUses: uses }; }
  const cleared = source.lastRun === null && source.lastTrace.length === 0 && source.roundResults.length === 0 && source.failureSnapshot === null && source.lastRunAt === null;
  if (cleared) return { workspace, lastTrace: [], lastRun: null, totalRuns, runtimeFailures, compileFailures, usedHintTiers: source.usedHintTiers as MissionSession['usedHintTiers'], conceptFailures, lastRunAt: null, savedAt: date(source.savedAt, 'sessions.w3-m3.savedAt'), roundResults: [], failureSnapshot: null, conditionObservationUses: uses };
  if (source.lastRun === null || source.lastTrace.length !== trace.length || source.lastRunAt === null) throw new Error('sessions.w3-m3运行证据不完整');
  const run = runYunzhanDialogueForDraft(workspace, trace);
  if (!same(source.lastTrace, trace) || !same(source.lastRun, run) || !same(source.roundResults, run.rounds) || !same(source.failureSnapshot, run.failureSnapshot)) throw new Error('sessions.w3-m3运行必须由workspace重新编译并确定性重放');
  return { workspace, lastTrace: trace, lastRun: run, totalRuns, runtimeFailures, compileFailures, usedHintTiers: source.usedHintTiers as MissionSession['usedHintTiers'], conceptFailures, lastRunAt: date(source.lastRunAt, 'sessions.w3-m3.lastRunAt'), savedAt: date(source.savedAt, 'sessions.w3-m3.savedAt'), roundResults: run.rounds, failureSnapshot: run.failureSnapshot, conditionObservationUses: uses };
}
