import { expect,test,type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { formalW6M2Completion,formalW6M3Completion } from './support/w6m1Prerequisite';

const KEY='xiyou-programming-progress-v3',REV='xiyou-programming-progress-revision-v3',MODE='xiyou-test-storage-mode',SEED='w6-m3-e2e-seeded';
async function seed(page:Page,raw=formalW6M2Completion()){await page.addInitScript(({key,rev,value,seed})=>{if(sessionStorage.getItem(seed)!=='1'){localStorage.setItem(key,value);localStorage.setItem(rev,'0');sessionStorage.setItem(seed,'1')}},{key:KEY,rev:REV,value:raw,seed:SEED})}
async function saved(page:Page){return page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),KEY)}
const task='按原著整理二调经过',facts=['悟空变作牛魔王模样，取得真扇','牛魔王变作八戒模样，骗回真扇','二调这次没有完成灭火通行'] as const,constraints=['只按原著和已给材料整理','材料不足时不编造'] as const;
async function waitDraft(page:Page){await expect.poll(async()=>Boolean((await saved(page)).sessions['w6-m3'])).toBe(true)}
async function solve(page:Page,format='事件表'){await page.getByLabel(task).check();for(const fact of facts)await page.getByLabel(fact).check();for(const value of constraints)await page.getByLabel(value).check();await page.getByLabel(format).check()}
async function unlockParent(page:Page){const acknowledge=page.getByRole('button',{name:'我知道了',exact:true}),report=page.getByRole('button',{name:'导出进度',exact:true}),login=page.getByLabel('家长 PIN',{exact:true}),setup=page.getByLabel('设置 4 位家长 PIN',{exact:true});if(!(await saved(page)).privacy.localDataNoticeSeen){await expect(acknowledge).toBeVisible();await acknowledge.click();await expect.poll(async()=>(await saved(page)).privacy.localDataNoticeSeen).toBe(true)}await expect(page.getByTestId('app-background')).not.toHaveAttribute('inert','');await expect(report.or(login).or(setup)).toBeVisible();if(await report.isVisible())return;if(await login.isVisible()){await login.fill('4826');await page.getByRole('button',{name:'进入周报'}).click();await expect(report).toBeVisible();return}const confirm=page.getByLabel('确认家长 PIN');await setup.fill('4826');await confirm.fill('4826');await page.getByRole('button',{name:'创建家长 PIN'}).click();await page.getByLabel('我已安全保存恢复码').check();await page.getByRole('button',{name:'确认已保存并进入'}).click();await expect(report).toBeVisible()}

test('@w6-m3-full child input drives partial output, both formats, first blockers and formal completion',async({page})=>{await seed(page);await page.goto('./#/mission/w6-m3');await expect(page.getByRole('heading',{name:'二调芭蕉扇·任务说明书'})).toBeVisible();await waitDraft(page);for(const name of [task,...facts,...constraints,'事件表','分步列表'])await expect(page.getByLabel(name)).not.toBeChecked();await page.getByRole('button',{name:'运行本地规则模拟'}).click();await expect(page.getByLabel('任务说明书试运行结果')).toContainText('先选择');expect((await saved(page)).sessions['w6-m3'].lastRun.failureSnapshots).toHaveLength(1);
 await page.getByLabel(task).check();await page.getByLabel(facts[0]).check();await page.getByLabel('分步列表').check();await page.getByRole('button',{name:'运行本地规则模拟'}).click();const output=page.getByRole('region',{name:'本地规则模拟输出'});await expect(output.locator('ol')).toContainText('悟空变作牛魔王');await expect(output).not.toContainText('牛魔王变作八戒');await page.getByLabel('事件表').check();await page.getByRole('button',{name:'运行本地规则模拟'}).click();await expect(output.locator('table')).toBeVisible();
 for(const fact of facts.slice(1))await page.getByLabel(fact).check();for(const value of constraints)await page.getByLabel(value).check();await page.getByRole('button',{name:'运行本地规则模拟'}).click();await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible({timeout:30_000});const progress=await saved(page);expect(progress).toMatchObject({schemaRevision:22,missionCompletionEvidence:{'w6-m2':{kind:'formal-v3'},'w6-m3':{kind:'formal-v3',workId:'w6-m3-second-attempt-brief'}},works:{'w6-m3-second-attempt-brief':{kind:'ai-prompt-brief-v1',run:{completed:true}}}});expect(progress.missions['w6-m4']).toBeUndefined();await page.reload();await expect(page.getByRole('heading',{name:'二调芭蕉扇·任务说明书'})).toBeVisible();const before=await page.evaluate(({key,rev})=>[localStorage.getItem(key),localStorage.getItem(rev)],{key:KEY,rev:REV});await page.getByRole('button',{name:'重放已保存说明书'}).click();await expect(page.getByLabel('任务说明书试运行结果')).toContainText('正式证明没有改写');expect(await page.evaluate(({key,rev})=>[localStorage.getItem(key),localStorage.getItem(rev)],{key:KEY,rev:REV})).toEqual(before);});

test('@w6-m3-keyboard focus survives a save and native arrows and Tab continue the form',async({page})=>{await seed(page);await page.goto('./#/mission/w6-m3');await waitDraft(page);const first=page.getByLabel(task),rewrite=page.getByRole('radio',{name:'改写为二调已通行',exact:true}),firstFact=page.getByLabel(facts[0]);await first.focus();await page.keyboard.press('Space');await expect.poll(async()=>(await saved(page)).sessions['w6-m3'].input.task).toBe('organize-second-attempt');await expect(first).toBeFocused();await page.keyboard.press('ArrowDown');await expect.poll(async()=>(await saved(page)).sessions['w6-m3'].input.task).toBe('rewrite-second-attempt');await expect(rewrite).toBeFocused();await page.keyboard.press('Tab');await expect(firstFact).toBeFocused();await page.keyboard.press('Space');await expect.poll(async()=>(await saved(page)).sessions['w6-m3'].input.factIds).toContain('sun-as-bull-gets-fan');await expect(firstFact).toBeFocused();});

test('@w6-m3-external stale tabs preserve the newer prompt draft and can load it explicitly',async({page,context})=>{await seed(page);await page.addInitScript(()=>window.addEventListener('storage',event=>event.stopImmediatePropagation(),true));await page.goto('./#/mission/w6-m3');await waitDraft(page);const second=await context.newPage();await second.goto('./#/mission/w6-m3');await waitDraft(second);await second.getByLabel(task).check();await expect.poll(async()=>(await saved(second)).sessions['w6-m3'].input.task).toBe('organize-second-attempt');await page.getByLabel('分步列表').check();await expect(page.getByRole('button',{name:'载入其他标签页进度'})).toBeVisible();await page.getByRole('button',{name:'载入其他标签页进度'}).click();await expect(page.getByLabel(task)).toBeChecked();expect((await saved(page)).sessions['w6-m3'].input.outputFormat).toBeNull();await second.close()});

test('@w6-m3-corrupt corrupt current data restores the last valid M2 source and M3 draft',async({page})=>{await seed(page);await page.goto('./#/mission/w6-m3');await waitDraft(page);await page.getByLabel(task).check();await expect.poll(async()=>(await saved(page)).sessions['w6-m3'].input.task).toBe('organize-second-attempt');await page.evaluate(key=>{const raw=localStorage.getItem(key)!;localStorage.setItem('xiyou-programming-progress-snapshot-v3',raw);localStorage.setItem(key,'{broken w6-m3 current')},KEY);await page.reload();await expect(page.getByText('学习进度已经安全恢复')).toBeVisible();await page.goto('./#/mission/w6-m3');await expect(page.getByLabel(task)).toBeChecked();const restored=await saved(page);expect(restored.missionCompletionEvidence['w6-m2']?.kind).toBe('formal-v3');expect(restored.works['w6-m2-fan-evidence-classification']).toBeTruthy()});

test('@w6-m3-touch touch-sized inputs compose the same current brief without horizontal overflow',async({page})=>{await seed(page);await page.goto('./#/mission/w6-m3');await waitDraft(page);await page.getByLabel(task).tap();await page.getByLabel(facts[0]).tap();await expect(page.getByRole('region',{name:'我的任务说明书'})).toContainText(facts[0]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);});

test('@w6-m3-storage session and completion failures retry exact transactions without duplicate runs',async({page})=>{await seed(page);await page.goto('./#/mission/w6-m3');await waitDraft(page);await page.evaluate(key=>localStorage.setItem(key,'fail-w6-m3-session'),MODE);await page.getByLabel(task).check();await expect(page.getByRole('button',{name:'重试保存'})).toBeVisible();await page.evaluate(key=>localStorage.setItem(key,'off'),MODE);await page.getByRole('button',{name:'重试保存'}).click();await solve(page);await page.evaluate(key=>localStorage.setItem(key,'fail-w6-m3-completion'),MODE);await page.getByRole('button',{name:'运行本地规则模拟'}).click();await expect(page.getByRole('button',{name:'重试保存'})).toBeVisible();expect((await saved(page)).sessions['w6-m3'].totalRuns).toBe(1);await page.evaluate(key=>localStorage.setItem(key,'off'),MODE);await page.getByRole('button',{name:'重试保存'}).click();await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible();expect((await saved(page)).sessions['w6-m3'].totalRuns).toBe(1);});

test('@w6-m3-assets a successful saved run waits for required scene and seals after asset retry',async({page})=>{await seed(page);await page.route(/flaming-mountain-background\.webp/,route=>route.fulfill({status:503,body:'unavailable'}));await page.goto('./#/mission/w6-m3');await waitDraft(page);await solve(page);await page.getByRole('button',{name:'运行本地规则模拟'}).click();await expect.poll(async()=>(await saved(page)).sessions['w6-m3'].lastRun?.completed).toBe(true);expect((await saved(page)).missions['w6-m3']).toBeUndefined();await page.unroute(/flaming-mountain-background\.webp/);await page.getByRole('button',{name:'重试加载火焰山场景'}).click();await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible({timeout:30_000});expect((await saved(page)).sessions['w6-m3'].totalRuns).toBe(1);});

test('@w6-m3-lazy failed prompt chunk retries locally',async({page})=>{await seed(page);let failed=false;await page.route(/WeekSixPromptExperience-[^/]+\.js/,route=>{if(!failed){failed=true;return route.fulfill({status:503,body:'unavailable'})}return route.continue()});await page.goto('./#/mission/w6-m3');await expect(page.getByText('任务说明书体验加载失败')).toBeVisible({timeout:30_000});await page.unroute(/WeekSixPromptExperience-[^/]+\.js/);await page.getByRole('button',{name:'重新加载页面'}).click();await expect(page.getByRole('heading',{name:'二调芭蕉扇·任务说明书'})).toBeVisible();});

test('@w6-m3-parent export, clear and import restore proof and a non-answer parent summary',async({page})=>{await seed(page,formalW6M3Completion());await page.goto('./#/parent');await unlockParent(page);const summary=page.getByRole('region',{name:'第六周任务说明学习摘要'});await expect(summary).toContainText('任务说明书正式证明与作品已保存');await expect(summary).not.toContainText(/sun-as-bull|follow-canon|identities-reversed|sourceWorkId/);const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出进度'}).click();const bytes=readFileSync((await(await download).path())!);await page.getByRole('button',{name:'清空学习数据'}).click();await page.getByLabel('输入“清空”以确认').fill('清空');const backup=page.waitForEvent('download');await page.getByRole('button',{name:'备份并清空'}).click();await backup;await expect.poll(async()=>(await saved(page)).missionCompletionEvidence['w6-m3']).toBeUndefined();await page.reload();await unlockParent(page);await page.getByLabel('选择进度文件').setInputFiles({name:'w6m3.json',mimeType:'application/json',buffer:bytes});await expect.poll(async()=>(await saved(page)).missionCompletionEvidence['w6-m3']?.kind).toBe('formal-v3');await unlockParent(page);await expect(page.getByRole('region',{name:'第六周任务说明学习摘要'})).toContainText('正式证明');});
