import { expect, test, type Page, type TestInfo } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { completeMission, createInitialProgress, serializeProgress } from '../src/progress/progress';
import { createMissionSession, recordRun, updateWorkspaceDraft } from '../src/progress/session';
import { createDefaultManorHelpDraft, compileManorHelpDraft, runManorHelp } from '../src/blockly/weekThreeManorHelpContract';
import { compileCuilanBooleanDraft, runCuilanBooleanForDraft } from '../src/blockly/weekThreeCuilanBooleanContract';
import { createDefaultYunzhanDialogueDraft, compileYunzhanDialogueDraft, runYunzhanDialogueForDraft } from '../src/blockly/weekThreeYunzhanDialogueContract';
import { WEEK_THREE_BAJIE_JOINING_COLD_LOAD_MAX_BYTES } from '../scripts/budget-limits.mjs';

const CURRENT_KEY = 'xiyou-programming-progress-v3'; const REVISION_KEY = 'xiyou-programming-progress-revision-v3'; const MODE_KEY = 'xiyou-test-storage-mode';
type HealthEvent = { kind: string; url: string; detail: string };
const healthEvents = new WeakMap<Page, HealthEvent[]>(); let expectedFailureUrl: string | null = null;

// The only preload is the legal, replayable W3-M3 formal proof; it never contains W3-M4 state.
function formalW3M3Prerequisite(testInfo: TestInfo) {
  let progress = createInitialProgress(); const standard = /motion parity/i.test(testInfo.title);
  progress = { ...progress, settings: { ...progress.settings, muted: !standard, reducedMotion: !standard, reducedMotionOverride: !standard }, privacy: { localDataNoticeSeen: true } };
  for (const id of ['w1-m1', 'w1-m2', 'w1-m3', 'w1-m4', 'w1-m5', 'w2-m1', 'w2-m2', 'w2-m3', 'w2-m4', 'w2-m5'] as const) progress = completeMission(progress, id, { stars: 3, hintsUsed: 0 });
  const manor = createDefaultManorHelpDraft(); manor.blocks.find((block) => block.id === 'manor-condition')!.type = 'w3_manor_condition_explicit_demon_help';
  const manorTrace = compileManorHelpDraft(manor); const manorSession = recordRun(updateWorkspaceDraft(createMissionSession('w3-m1'), manor, '2026-08-28T00:00:00.000Z'), runManorHelp(manorTrace), manorTrace, '2026-08-28T00:00:01.000Z');
  progress = completeMission({ ...progress, sessions: { ...progress.sessions, 'w3-m1': manorSession } }, 'w3-m1', { stars: 3, hintsUsed: 0 });
  const cuilan = createMissionSession('w3-m2'); const cuilanDraft = structuredClone(cuilan.workspace); cuilanDraft.blocks.find((block) => block.id === 'cuilan-identity-condition')!.type = 'w3_cuilan_condition_identity_is_cuilan'; const cuilanTrace = compileCuilanBooleanDraft(cuilanDraft); const cuilanSession = recordRun(updateWorkspaceDraft(cuilan, cuilanDraft, '2026-08-28T00:00:02.000Z'), runCuilanBooleanForDraft(cuilanDraft, cuilanTrace), cuilanTrace, '2026-08-28T00:00:03.000Z');
  progress = completeMission({ ...progress, sessions: { ...progress.sessions, 'w3-m2': cuilanSession } }, 'w3-m2', { stars: 3, hintsUsed: 0 });
  const yunzhan = createDefaultYunzhanDialogueDraft(); const then = yunzhan.blocks.find((block) => block.id === 'yunzhan-then-action')!; const otherwise = yunzhan.blocks.find((block) => block.id === 'yunzhan-else-action')!; [then.branch, otherwise.branch] = [otherwise.branch, then.branch];
  const yunzhanTrace = compileYunzhanDialogueDraft(yunzhan); const yunzhanSession = recordRun(updateWorkspaceDraft(createMissionSession('w3-m3'), yunzhan, '2026-08-28T00:00:02.000Z'), runYunzhanDialogueForDraft(yunzhan, yunzhanTrace), yunzhanTrace, '2026-08-28T00:00:03.000Z');
  progress = { ...progress, sessions: { ...progress.sessions, 'w3-m3': yunzhanSession } };
  return serializeProgress(completeMission(progress, 'w3-m3', { stars: 3, hintsUsed: 0 }));
}
function expectedFailure(value: string) { return expectedFailureUrl !== null && (value === expectedFailureUrl || value.includes(expectedFailureUrl)); }
function attachHealth(page: Page) { const events: HealthEvent[] = []; healthEvents.set(page, events); page.on('console', (message) => { if (message.type() === 'error' && !expectedFailure(message.location().url) && !expectedFailure(message.text())) events.push({ kind: 'console', url: message.location().url || page.url(), detail: message.text() }); }); page.on('pageerror', (error) => events.push({ kind: 'page', url: page.url(), detail: error.message })); page.on('requestfailed', (request) => { const detail = request.failure()?.errorText ?? ''; if (!expectedFailure(request.url()) && !(request.url() === 'https://static.blockly.com/media/sprites.svg' && /ABORTED|cancelled/i.test(detail))) events.push({ kind: 'request', url: request.url(), detail }); }); page.on('response', (response) => { if (response.status() >= 400 && !expectedFailure(response.url())) events.push({ kind: 'response', url: response.url(), detail: `HTTP ${response.status()}` }); }); }
async function stored(page: Page) { return page.evaluate((key) => JSON.parse(localStorage.getItem(key)!), CURRENT_KEY); }
const workspace = (page: Page) => page.getByRole('region', { name: '八戒归队 Blockly 工作区', exact: true });
async function gotoBajie(page: Page) { await page.goto('./#/mission/w3-m4'); await expect(page.getByText('八戒归队：两个条件要一起核对')).toBeVisible(); await expect(page.getByRole('img', { name: '八戒归队故事画面' })).toHaveAttribute('data-scene-ready', 'true'); await expect(workspace(page).locator('.advanced-blockly-host svg.blocklySvg')).toBeVisible(); }
async function press(page: Page, name: string, key: 'Enter' | 'Space' | null = null) { const button = page.getByRole('button', { name, exact: true }); await expect(button).toBeEnabled(); if (key) { await button.focus(); await button.press(key); } else await button.click(); }
async function setAnd(page: Page, key: 'Enter' | 'Space' = 'Enter', waitForPersistence = true) { const host = page.getByLabel('八戒归队可连接积木图'); await host.focus(); await host.press(key); if (waitForPersistence) await expect.poll(async () => (await stored(page)).sessions['w3-m4']?.workspace.blocks.find((block: { id: string }) => block.id === 'bajie-boolean-operation')?.operator).toBe('and'); }
async function run(page: Page, key: 'Enter' | 'Space' | null = null) { await press(page, '执行入队判断', key); }
async function complete(page: Page) { await setAnd(page); await run(page); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); }
async function attach(page: Page, testInfo: TestInfo, name: string) { const path = testInfo.outputPath(`${name}-${testInfo.project.name}.png`); await page.screenshot({ path, fullPage: true }); await testInfo.attach(`${name}-${testInfo.project.name}.png`, { path, contentType: 'image/png' }); }

test.describe('W3-M4 八戒归队双证据组合', () => {
  test.beforeEach(async ({ page }, testInfo) => { expectedFailureUrl = null; attachHealth(page); await page.addInitScript(({ raw, current, revision }) => { if (localStorage.getItem(current) === null) { localStorage.setItem(current, raw); localStorage.setItem(revision, '0'); } }, { raw: formalW3M3Prerequisite(testInfo), current: CURRENT_KEY, revision: REVISION_KEY }); });
  test.afterEach(async ({ page }) => { expect(healthEvents.get(page), 'unexpected W3-M4 browser health events').toEqual([]); });

  test('@w3-m4-full @w3-m4-narrow default OR fails visibly, observation stays non-answering, AND completes and replay is idempotent', async ({ page }, testInfo) => {
    await gotoBajie(page); await expect(page.getByRole('region', { name: '公开入队陈述卡' }).locator('article')).toHaveCount(3); await expect(workspace(page).locator('.blocklyDraggable[data-id="bajie-boolean-operation"]')).toBeVisible();
    const geometry = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth })); expect(geometry.scroll).toBeLessThanOrEqual(geometry.width); const layout = await page.getByLabel('八戒归队可连接积木图').evaluate((host) => { const bounds = host.getBoundingClientRect(); const blocks = [...host.querySelectorAll<HTMLElement>('.blocklyDraggable[data-id]')].map((block) => { const rect = block.getBoundingClientRect(); return { id: block.dataset.id!, width: rect.width, height: rect.height, overlap: Math.max(0, Math.min(rect.right, bounds.right) - Math.max(rect.left, bounds.left)) * Math.max(0, Math.min(rect.bottom, bounds.bottom) - Math.max(rect.top, bounds.top)) }; }); return { width: bounds.width, height: bounds.height, blocks }; }); expect(layout.height).toBeGreaterThanOrEqual(360); expect(layout.width).toBeGreaterThan(0); expect(layout.blocks.length).toBeGreaterThanOrEqual(7); for (const id of ['bajie-receive-statement', 'bajie-boolean-operation', 'bajie-guanyin-precepts', 'bajie-willing-westward', 'bajie-formally-join-team', 'bajie-continue-verification']) { const block = layout.blocks.find((value) => value.id === id); expect(block, `${id} missing`).toBeDefined(); expect(block!.width, `${id} zero width`).toBeGreaterThan(0); expect(block!.height, `${id} zero height`).toBeGreaterThan(0); expect(block!.overlap, `${id} outside host`).toBeGreaterThan(4); } await attach(page, testInfo, 'bajie-default');
    await run(page); await expect(page.getByRole('alert')).toContainText('没有同时满足两个条件'); await expect(page.getByText('本次错误不会扣除生命、资源或星级。')).toBeVisible(); await expect(page.getByRole('button', { name: '火眼金睛：观察本次判断' })).toBeVisible(); await attach(page, testInfo, 'bajie-failure');
    await press(page, '火眼金睛：观察本次判断'); const observation = page.locator('.week-three-bajie-joining-experience > aside[role="status"]'); await expect(observation).toContainText('当前可见 OR'); await expect(observation).toContainText('组合结果'); await expect(observation).not.toContainText('正确'); await expect(observation).not.toContainText('AND');
    await setAnd(page); await run(page); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); await attach(page, testInfo, 'bajie-success'); const after = await stored(page); expect(after.missionCompletionEvidence['w3-m4'].kind).toBe('formal-v3'); await press(page, '回成长地图'); await expect(page.getByRole('button', { name: '高老庄总试炼', exact: true })).toBeEnabled();
    await page.goto('./#/mission/w3-m4'); const count = (await stored(page)).sessions['w3-m4'].totalRuns; await press(page, '重播上次运行'); await expect.poll(async () => (await stored(page)).sessions['w3-m4'].totalRuns).toBe(count);
  });

  test('@w3-m4-keyboard keyboard changes the same visible Blockly operator and supports commutative sensors', async ({ page }) => { await gotoBajie(page); await setAnd(page, 'Space'); await press(page, '交换两个条件的位置', 'Enter'); await run(page, 'Enter'); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); });
  test('@w3-m4-mouse desktop mouse opens the real Blockly FieldDropdown and selects AND', async ({ page }) => { await gotoBajie(page); const dropdown = workspace(page).getByRole('button', { name: /dropdown:.*OR/ }); await dropdown.click(); const option = page.getByText('同时满足（AND）', { exact: true }).last(); await option.click(); await expect.poll(async () => (await stored(page)).sessions['w3-m4']?.workspace.blocks.find((block: { id: string }) => block.id === 'bajie-boolean-operation')?.operator).toBe('and'); await run(page); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); });
  test('@w3-m4-touch touch opens the same real Blockly FieldDropdown and taps AND', async ({ page }) => { await gotoBajie(page); const dropdown = workspace(page).getByRole('button', { name: /dropdown:.*OR/ }); await dropdown.tap(); const option = page.getByText('同时满足（AND）', { exact: true }).last(); await option.tap(); await expect.poll(async () => (await stored(page)).sessions['w3-m4']?.workspace.blocks.find((block: { id: string }) => block.id === 'bajie-boolean-operation')?.operator).toBe('and'); await run(page); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); });
  for (const mode of ['draft', 'run', 'observation', 'completion'] as const) test(`@w3-m4-storage ${mode} fault fails closed and exposes only visible retry`, async ({ page }) => { await gotoBajie(page); if (mode === 'draft') { await page.evaluate((key) => localStorage.setItem(key, 'fail-bajie-draft'), MODE_KEY); await setAnd(page, 'Enter', false); } else if (mode === 'run') { await setAnd(page); await page.evaluate((key) => localStorage.setItem(key, 'fail-bajie-run'), MODE_KEY); await run(page); } else if (mode === 'observation') { await run(page); await page.evaluate((key) => localStorage.setItem(key, 'fail-bajie-observation'), MODE_KEY); await press(page, '火眼金睛：观察本次判断'); } else { await setAnd(page); await page.evaluate((key) => localStorage.setItem(key, 'fail-bajie-completion'), MODE_KEY); await run(page); } const recovery = page.getByRole('alert').filter({ hasText: /待重试|通关待保存/ }).first(); await expect(recovery).toBeVisible(); await page.evaluate((key) => localStorage.setItem(key, 'off'), MODE_KEY); if (mode === 'completion') await press(page, '重试保存通关'); else await recovery.getByRole('button', { name: '重试保存', exact: true }).click(); if (mode === 'draft') await expect.poll(async () => (await stored(page)).sessions['w3-m4']?.workspace.blocks.find((block: { id: string }) => block.id === 'bajie-boolean-operation')?.operator).toBe('and'); else if (mode === 'run') { await expect.poll(async () => (await stored(page)).sessions['w3-m4']?.totalRuns).toBe(1); await expect.poll(async () => (await stored(page)).sessions['w3-m4']?.lastRun?.completed).toBe(true); } else if (mode === 'observation') { await expect.poll(async () => (await stored(page)).sessions['w3-m4']?.conditionObservationUses.length).toBe(1); await page.reload(); await expect(page.getByRole('button', { name: '火眼金睛：观察本次判断' })).toBeVisible(); } else { await expect.poll(async () => (await stored(page)).missionCompletionEvidence['w3-m4']?.kind).toBe('formal-v3'); await page.goto('./#/'); await expect(page.getByRole('button', { name: '高老庄总试炼', exact: true })).toBeEnabled(); } });
  test('@w3-m4-external stale tab backs up and requires explicit reload', async ({ page, context }) => { await gotoBajie(page); const stale = await context.newPage(); attachHealth(stale); try { await stale.goto('./#/mission/w3-m4'); await setAnd(page); await expect(stale.getByText(/其他标签页已有新的学习进度/)).toBeVisible(); await stale.getByRole('button', { name: '载入其他标签页进度' }).click(); } finally { try { expect(healthEvents.get(stale)).toEqual([]); } finally { await stale.close(); } } });
  test('@w3-m4-corrupt corrupt current preserves bytes and restores a snapshot', async ({ page }) => { await gotoBajie(page); await complete(page); const before = await stored(page); await page.evaluate((key) => localStorage.setItem(key, 'corrupt-bajie-current'), MODE_KEY); await page.reload(); await expect(page.getByText('学习进度已经安全恢复')).toBeVisible(); const recovered = await stored(page); expect(recovered.sessions['w3-m4']).toEqual(before.sessions['w3-m4']); expect(recovered.missionCompletionEvidence['w3-m4']).toEqual(before.missionCompletionEvidence['w3-m4']); await press(page, '成长地图'); await expect(page.getByRole('button', { name: '高老庄总试炼', exact: true })).toBeEnabled(); });
  test('@w3-m4-parent parent export-import restores the formal proof and keeps W3-M5 unlocked', async ({ page }) => { await gotoBajie(page); await complete(page); await press(page, '回成长地图'); await press(page, '家长周报'); await page.getByLabel('设置 4 位家长 PIN').fill('4826'); await page.getByLabel('确认家长 PIN').fill('4826'); await press(page, '创建家长 PIN'); await page.getByLabel('我已安全保存恢复码').check(); await press(page, '确认已保存并进入'); const download = page.waitForEvent('download'); await press(page, '导出进度'); const path = await (await download).path(); expect(path).not.toBeNull(); const exported = JSON.parse(readFileSync(path!, 'utf8')); expect(exported.missionCompletionEvidence['w3-m4'].kind).toBe('formal-v3'); await press(page, '清空学习数据'); await page.getByLabel('输入“清空”以确认').fill('清空'); const cleared = page.waitForEvent('download'); await press(page, '备份并清空'); await cleared; await expect(page.getByRole('button', { name: '我知道了' })).toBeVisible(); const empty = await stored(page); expect(empty.sessions['w3-m4']).toBeUndefined(); expect(empty.missionCompletionEvidence['w3-m4']).toBeUndefined(); await page.getByRole('button', { name: '我知道了' }).click(); await page.goto('./#/'); await expect(page.getByRole('button', { name: '高老庄总试炼，未解锁', exact: true })).toBeDisabled(); await page.goto('./#/parent'); await page.getByLabel('设置 4 位家长 PIN').fill('4826'); await page.getByLabel('确认家长 PIN').fill('4826'); await press(page, '创建家长 PIN'); await page.getByLabel('我已安全保存恢复码').check(); await press(page, '确认已保存并进入'); await page.getByLabel('选择进度文件').setInputFiles({ name: 'w3-m4-progress.json', mimeType: 'application/json', buffer: readFileSync(path!) }); await expect(page.getByText('导入成功：来源版本 V3。')).toBeVisible(); const restored = await stored(page); expect(restored.settings).toEqual(exported.settings); expect(restored.sessions['w3-m4']).toEqual(exported.sessions['w3-m4']); expect(restored.missionCompletionEvidence['w3-m4']).toEqual(exported.missionCompletionEvidence['w3-m4']); await press(page, '成长地图'); await expect(page.getByRole('button', { name: '高老庄总试炼', exact: true })).toBeEnabled(); });
  test('@w3-m4-cold cold closure and missing asset response are bounded', async ({ page, request }) => { const bodies: Array<Promise<number>> = []; page.on('response', (response) => { if (response.status() >= 200 && response.status() < 300) bodies.push(response.body().then((body) => body.length)); }); await gotoBajie(page); expect((await Promise.all(bodies)).reduce((sum, bytes) => sum + bytes, 0)).toBeLessThanOrEqual(WEEK_THREE_BAJIE_JOINING_COLD_LOAD_MAX_BYTES); expect((await request.get('/xiyou-programming-journey/assets/week-three-bajie-joining/not-found.webp', { headers: { accept: 'image/webp' } })).status()).toBe(404); });
  test('@w3-m4-asset-fault asset failure prevents completion until retry', async ({ page }) => { let failed = false; await page.route(/bajie-joining-background\.webp(?:\?.*)?$/, async (route) => { if (!failed) { failed = true; expectedFailureUrl = route.request().url(); await route.fulfill({ status: 503, body: 'synthetic asset failure' }); } else if (new URL(route.request().url()).searchParams.has('retry')) await route.continue(); else await route.abort(); }); await page.goto('./#/mission/w3-m4'); await expect.poll(() => failed).toBe(true); await expect(page.getByRole('alert').filter({ hasText: '场景图片没有加载成功' })).toBeVisible(); await setAnd(page); await run(page); await expect(page.getByRole('dialog', { name: '闯关成功' })).toHaveCount(0); await press(page, '重试加载场景图片'); await expect(page.locator('[aria-label="八戒归队故事画面"]')).toHaveAttribute('data-scene-ready', 'true'); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); expectedFailureUrl = null; });
  for (const boundary of [{ name: 'Experience', pattern: /WeekThreeBajieJoiningExperience-[^/]+\.js(?:\?.*)?$/, text: '八戒归队条件任务加载失败' }, { name: 'Scene', pattern: /WeekThreeBajieJoiningScene-[^/]+\.js(?:\?.*)?$/, text: '八戒归队场景加载失败' }, { name: 'Workspace', pattern: /WeekThreeBajieJoiningBlocklyWorkspace-[^/]+\.js(?:\?.*)?$/, text: '八戒归队积木加载失败' }]) test(`@w3-m4-lazy ${boundary.name} lazy failure has retry`, async ({ page }) => { let failed = false; await page.route(boundary.pattern, async (route) => { if (!failed) { failed = true; expectedFailureUrl = route.request().url(); await route.fulfill({ status: 503, body: 'synthetic' }); } else await route.continue(); }); await page.goto('./#/mission/w3-m4'); await expect(page.getByRole('alert')).toContainText(boundary.text); await page.getByRole('button', { name: '重新加载页面' }).click(); await expect(page.getByText('八戒归队：两个条件要一起核对')).toBeVisible(); await expect(page.getByRole('img', { name: '八戒归队故事画面' })).toHaveAttribute('data-scene-ready', 'true'); await expect(workspace(page).locator('.advanced-blockly-host svg.blocklySvg')).toBeVisible(); await setAnd(page); await run(page); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); expectedFailureUrl = null; });
});
