import { readFileSync } from 'node:fs';
import { expect, test, type Locator, type Page } from '@playwright/test';
import { formalW6M1Completion, formalW6M2Completion } from './support/w6m1Prerequisite';

const KEY='xiyou-programming-progress-v3',REV='xiyou-programming-progress-revision-v3',MODE='xiyou-test-storage-mode';
const saved=(page:Page)=>page.evaluate((key)=>JSON.parse(localStorage.getItem(key)!),KEY);
async function seed(page:Page,raw=formalW6M1Completion()){await page.addInitScript(({key,rev,raw})=>{if(localStorage.getItem(key)===null){localStorage.setItem(key,raw);localStorage.setItem(rev,'0');}},{key:KEY,rev:REV,raw});}
async function open(page:Page){await page.goto('./#/mission/w6-m2');await expect(page.getByRole('heading',{name:'真假扇证据分类台'})).toBeVisible();await expect(page.locator('[data-mission="w6-m2"]')).toHaveAttribute('data-assets-ready','true');await expect.poll(async()=>Boolean((await saved(page)).sessions['w6-m2'])).toBe(true);}
const card=(page:Page,attempt:'一调'|'二调'|'三调')=>page.getByLabel(`${attempt}分类卡`);
async function waitEditable(page:Page){await expect(page.getByRole('button',{name:'核验全部标签与依据'})).toBeEnabled();}
async function radio(page:Page,attempt:'一调'|'二调'|'三调',name:'真扇'|'假扇'|'已达成'|'未达成'){await card(page,attempt).getByRole('radio',{name,exact:true}).check();await waitEditable(page);}
async function evidence(page:Page,attempt:'一调'|'二调'|'三调',dimension:'扇子真假'|'灭火通行',value:string){await page.getByLabel(`${attempt}${dimension}依据`).selectOption(value);await waitEditable(page);}
async function fillAttempt(page:Page,attempt:'一调'|'二调'|'三调',fan:'真扇'|'假扇',fanEvidence:string,passage:'已达成'|'未达成',passageEvidence:string){await radio(page,attempt,fan);await evidence(page,attempt,'扇子真假',fanEvidence);await radio(page,attempt,passage);await evidence(page,attempt,'灭火通行',passageEvidence);}
async function fillSolvedLabels(page:Page){await fillAttempt(page,'一调','假扇','one-not-real','未达成','one-fire-worse');await fillAttempt(page,'二调','真扇','two-true-fan','未达成','two-stolen-back');await fillAttempt(page,'三调','真扇','three-true-fan','已达成','three-fire-cleared');}
async function choosePractice(page:Page,name:'真扇'|'假扇'|'证据不足'){await page.getByRole('region',{name:'材料不足练习'}).getByRole('radio',{name,exact:true}).check();await waitEditable(page);}
async function unlockParent(page:Page){const acknowledge=page.getByRole('button',{name:'我知道了',exact:true}),report=page.getByRole('button',{name:'导出进度',exact:true}),login=page.getByLabel('家长 PIN',{exact:true}),setup=page.getByLabel('设置 4 位家长 PIN',{exact:true});if(!(await saved(page)).privacy.localDataNoticeSeen){await expect(acknowledge).toBeVisible();await acknowledge.click();await expect.poll(async()=>(await saved(page)).privacy.localDataNoticeSeen).toBe(true);}await expect(page.getByTestId('app-background')).not.toHaveAttribute('inert','');await expect(report.or(login).or(setup)).toBeVisible();if(await report.isVisible())return;if(await login.isVisible()){await login.fill('4826');await page.getByRole('button',{name:'进入周报'}).click();await expect(report).toBeVisible();return;}const confirm=page.getByLabel('确认家长 PIN');await setup.fill('4826');await confirm.fill('4826');await expect(setup).toHaveValue('4826');await expect(confirm).toHaveValue('4826');await page.getByRole('button',{name:'创建家长 PIN'}).click();await page.getByLabel('我已安全保存恢复码').check();await page.getByRole('button',{name:'确认已保存并进入'}).click();await expect(report).toBeVisible();}

test('@w6-m2-full labels, independent evidence and insufficient material produce a durable readonly proof',async({page},info)=>{
  test.setTimeout(120_000);const errors:string[]=[];page.on('pageerror',(error)=>errors.push(error.message));await seed(page);await open(page);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'核验全部标签与依据'}).click();await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].totalChecks).toBe(1);await expect(page.getByLabel('证据分类核验结果')).toContainText('一调');
  await fillAttempt(page,'一调','假扇','one-not-real','未达成','one-fire-worse');await page.reload();await open(page);await expect(card(page,'一调').getByRole('radio',{name:'假扇',exact:true})).toBeChecked();
  await fillAttempt(page,'二调','假扇','two-true-fan','未达成','two-stolen-back');
  await page.getByRole('button',{name:'核验全部标签与依据'}).click();await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].totalChecks).toBe(2);await expect(page.getByText('首个需要处理的位置：二调 · 扇子真假')).toBeVisible();
  const groups=page.getByRole('region',{name:'孩子当前标签分组'});await expect(groups).toContainText('一调、二调');
  await radio(page,'二调','真扇');await evidence(page,'二调','扇子真假','two-stolen-back');
  await page.getByRole('button',{name:'核验全部标签与依据'}).click();await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].totalChecks).toBe(3);await expect(page.getByLabel('证据分类核验结果')).toContainText('依据');
  await evidence(page,'二调','扇子真假','two-true-fan');await fillAttempt(page,'三调','真扇','three-true-fan','已达成','three-fire-cleared');await choosePractice(page,'真扇');
  await page.getByRole('button',{name:'核验全部标签与依据'}).click();await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].totalChecks).toBe(4);await expect(page.getByText('首个需要处理的位置：材料练习 · 材料练习')).toBeVisible();
  await choosePractice(page,'证据不足');await page.getByRole('button',{name:'核验全部标签与依据'}).click();await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible({timeout:30_000});
  const completed=await saved(page);expect(completed.schemaRevision).toBe(22);expect(completed.sessions['w6-m2'].totalChecks).toBe(5);expect(completed.sessions['w6-m2'].lastRun.penalty).toEqual({livesLost:0,resourcesLost:0,starsLost:0});expect(completed.missionCompletionEvidence['w6-m2']).toMatchObject({kind:'formal-v3',workId:'w6-m2-fan-evidence-classification'});expect(completed.works['w6-m2-fan-evidence-classification'].run.completed).toBe(true);
  await page.reload();await open(page);await expect(page.locator('.week-six-selected-evidence')).toHaveCount(6);const before=await page.evaluate(({key,rev})=>[localStorage.getItem(key),localStorage.getItem(rev)],{key:KEY,rev:REV});await page.getByRole('button',{name:'重播已保存分类'}).click();await expect(page.getByLabel('证据分类核验结果')).toContainText('正式证明没有被改写');expect(await page.evaluate(({key,rev})=>[localStorage.getItem(key),localStorage.getItem(rev)],{key:KEY,rev:REV})).toEqual(before);await page.screenshot({path:info.outputPath(`w6m2-complete-${info.project.name}.png`),fullPage:true});expect(errors).toEqual([]);
});

test('@w6-m2-keyboard radio, select and check remain keyboard operable',async({page})=>{await seed(page);await open(page);const first=card(page,'一调');const genuine=first.getByRole('radio',{name:'真扇',exact:true});await genuine.focus();await genuine.press('ArrowRight');await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].input.labels[0].fanAuthenticity).toBe('false');await expect(first.getByRole('radio',{name:'假扇',exact:true})).toBeChecked();const select=page.getByLabel('一调扇子真假依据');await select.focus();await select.press('ArrowDown');await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].input.labels[0].fanEvidenceId).toBe('one-not-real');await expect(select).toHaveValue('one-not-real');const check=page.getByRole('button',{name:'核验全部标签与依据'});await check.focus();await check.press('Enter');await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].totalChecks).toBe(1);});

test('@w6-m2-touch radio and check accept touch taps without horizontal overflow',async({page})=>{await seed(page);await open(page);await card(page,'一调').getByRole('radio',{name:'假扇',exact:true}).tap();await waitEditable(page);await page.getByRole('button',{name:'核验全部标签与依据'}).tap();await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].totalChecks).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});

for(const stage of ['initial','draft','grouping','hint','check','completion'] as const)test(`@w6-m2-storage ${stage} write retries the exact transaction`,async({page})=>{
  await seed(page);
  if(stage==='initial')await page.addInitScript((mode)=>localStorage.setItem(mode,'fail-w6-m2-session'),MODE);
  if(stage==='initial'){await page.goto('./#/mission/w6-m2');await expect(page.getByRole('heading',{name:'真假扇证据分类台'})).toBeVisible();}else await open(page);
  if(stage!=='initial'){
    if(stage==='completion')await fillSolvedLabels(page),await choosePractice(page,'证据不足');
    await page.evaluate(({mode,stage})=>localStorage.setItem(mode,stage==='completion'?'fail-w6-m2-completion':'fail-w6-m2-session'),{mode:MODE,stage});
    if(stage==='draft')await card(page,'一调').getByRole('radio',{name:'假扇',exact:true}).check();
    else if(stage==='grouping')await page.getByRole('button',{name:'按通行结果'}).click();
    else if(stage==='hint')await page.getByRole('button',{name:/提示一/}).click();
    else await page.getByRole('button',{name:'核验全部标签与依据'}).click();
  }
  const retry=page.locator('.week-six-classification-feedback').getByRole('button',{name:'重试保存'});await expect(retry).toBeVisible({timeout:30_000});await expect(page.getByRole('button',{name:/核验全部标签与依据|重播已保存分类/})).toBeDisabled();await page.evaluate((mode)=>localStorage.removeItem(mode),MODE);await retry.click();
  if(stage==='completion')await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible({timeout:30_000});else await expect(retry).toBeHidden();
  const progress=await saved(page);if(stage==='draft')expect(progress.sessions['w6-m2'].input.labels[0].fanAuthenticity).toBe('false');if(stage==='grouping')expect(progress.sessions['w6-m2'].groupingDimension).toBe('passage');if(stage==='hint')expect(progress.sessions['w6-m2'].usedHintTiers).toContain('observe');if(stage==='check')expect(progress.sessions['w6-m2'].totalChecks).toBe(1);if(stage==='completion')expect(progress.sessions['w6-m2'].totalChecks).toBe(1);expect(progress.sessions['w6-m2']).toBeTruthy();
});

test('@w6-m2-storage a session retry that reaches a failed completion keeps the new recovery action',async({page})=>{await seed(page);await open(page);await fillSolvedLabels(page);await choosePractice(page,'证据不足');await page.evaluate((mode)=>localStorage.setItem(mode,'fail-w6-m2-session'),MODE);await page.getByRole('button',{name:'核验全部标签与依据'}).click();const retry=page.locator('.week-six-classification-feedback').getByRole('button',{name:'重试保存'});await expect(retry).toBeVisible();await page.evaluate((mode)=>localStorage.setItem(mode,'fail-w6-m2-completion'),MODE);await retry.click();await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].totalChecks).toBe(1);await expect(retry).toBeVisible();expect((await saved(page)).missions['w6-m2']).toBeUndefined();await page.evaluate((mode)=>localStorage.removeItem(mode),MODE);await retry.click();await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible({timeout:30_000});expect((await saved(page)).sessions['w6-m2'].totalChecks).toBe(1);});

test('@w6-m2-storage stale tabs preserve the newer draft and can load it explicitly',async({page,context})=>{await seed(page);await page.addInitScript(()=>window.addEventListener('storage',(event)=>event.stopImmediatePropagation(),true));await open(page);const second=await context.newPage();await open(second);await card(second,'一调').getByRole('radio',{name:'假扇',exact:true}).check();await waitEditable(second);await page.getByRole('button',{name:'按通行结果'}).click();await expect(page.getByRole('button',{name:'载入其他标签页进度'})).toBeVisible({timeout:30_000});await page.getByRole('button',{name:'载入其他标签页进度'}).click();await expect(card(page,'一调').getByRole('radio',{name:'假扇',exact:true})).toBeChecked();expect((await saved(page)).sessions['w6-m2'].input.labels[0].fanAuthenticity).toBe('false');});

test('@w6-m2-storage corrupt current data restores the last valid M1 source and M2 draft',async({page})=>{await seed(page);await open(page);await card(page,'一调').getByRole('radio',{name:'假扇',exact:true}).check();await waitEditable(page);await page.evaluate(({key})=>{const raw=localStorage.getItem(key)!;localStorage.setItem('xiyou-programming-progress-snapshot-v3',raw);localStorage.setItem(key,'{broken w6-m2 current');},{key:KEY});await page.reload();await expect(page.getByText('学习进度已经安全恢复')).toBeVisible();await page.goto('./#/mission/w6-m2');await expect(card(page,'一调').getByRole('radio',{name:'假扇',exact:true})).toBeChecked();const restored=await saved(page);expect(restored.missionCompletionEvidence['w6-m1']?.kind).toBe('formal-v3');expect(restored.works['w6-m1-structured-records-table']).toBeTruthy();});


test('@w6-m2-assets stale success cannot publish after an edit, and a fresh check finishes once',async({page})=>{await seed(page);await page.route(/flaming-mountain-background\.webp/,route=>route.fulfill({status:503,body:'unavailable'}));await page.goto('./#/mission/w6-m2');await expect(page.getByRole('heading',{name:'真假扇证据分类台'})).toBeVisible();await expect.poll(async()=>Boolean((await saved(page)).sessions['w6-m2'])).toBe(true);await fillSolvedLabels(page);await choosePractice(page,'证据不足');await page.getByRole('button',{name:'核验全部标签与依据'}).click();await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].lastRun?.completed).toBe(true);expect((await saved(page)).missions['w6-m2']).toBeUndefined();await choosePractice(page,'真扇');await page.unroute(/flaming-mountain-background\.webp/);await page.getByRole('button',{name:'重试加载火焰山场景'}).click();await expect(page.locator('.week-six-classification-feedback').getByRole('button',{name:'重试保存'})).toHaveCount(0);await expect(page.getByRole('button',{name:'核验全部标签与依据'})).toBeEnabled();expect((await saved(page)).missions['w6-m2']).toBeUndefined();await choosePractice(page,'证据不足');await page.getByRole('button',{name:'核验全部标签与依据'}).click();await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible({timeout:30_000});expect((await saved(page)).sessions['w6-m2'].totalChecks).toBe(2);});

test('@w6-m2-assets a saved successful check survives reload and seals once the scene recovers',async({page})=>{await seed(page);await page.route(/flaming-mountain-background\.webp/,route=>route.fulfill({status:503,body:'unavailable'}));await page.goto('./#/mission/w6-m2');await expect(page.getByRole('heading',{name:'真假扇证据分类台'})).toBeVisible();await expect.poll(async()=>Boolean((await saved(page)).sessions['w6-m2'])).toBe(true);await fillSolvedLabels(page);await choosePractice(page,'证据不足');await page.getByRole('button',{name:'核验全部标签与依据'}).click();await expect.poll(async()=>(await saved(page)).sessions['w6-m2'].lastRun?.completed).toBe(true);expect((await saved(page)).missions['w6-m2']).toBeUndefined();await page.reload();await expect(page.getByRole('heading',{name:'真假扇证据分类台'})).toBeVisible();await expect(page.getByLabel('证据分类核验结果')).toHaveText('上次核验已通过，正式作品尚未保存。');expect((await saved(page)).sessions['w6-m2'].totalChecks).toBe(1);await page.unroute(/flaming-mountain-background\.webp/);await page.getByRole('button',{name:'重试加载火焰山场景'}).click();await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible({timeout:30_000});const progress=await saved(page);expect(progress.sessions['w6-m2'].totalChecks).toBe(1);expect(progress.missionCompletionEvidence['w6-m2']).toMatchObject({kind:'formal-v3',workId:'w6-m2-fan-evidence-classification'});});

test('@w6-m2-lazy failed classification chunk retries locally',async({page})=>{await seed(page);let failed=false;await page.route(/WeekSixClassificationExperience-[^/]+\.js/,route=>{if(!failed){failed=true;return route.fulfill({status:503,body:'unavailable'});}return route.continue();});await page.goto('./#/mission/w6-m2');await expect(page.getByText('证据分类台体验加载失败')).toBeVisible({timeout:30_000});await page.unroute(/WeekSixClassificationExperience-[^/]+\.js/);await page.getByRole('button',{name:'重新加载页面'}).click();await expect(page.getByRole('heading',{name:'真假扇证据分类台'})).toBeVisible();});

test('@w6-m2-parent export, clear and import restore the proof chain and non-answer summary',async({page})=>{await seed(page,formalW6M2Completion());await page.goto('./#/parent');await unlockParent(page);const summary=page.getByRole('region',{name:'第六周证据分类学习摘要'});await expect(summary).toContainText('证据分类正式证明与作品已保存');await expect(summary).not.toContainText(/genuine|false|not-passed|one-not-real|sourceRows|workId/);const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出进度'}).click();const bytes=readFileSync((await(await download).path())!);await page.getByRole('button',{name:'清空学习数据'}).click();await page.getByLabel('输入“清空”以确认').fill('清空');const backup=page.waitForEvent('download');await page.getByRole('button',{name:'备份并清空'}).click();await backup;await expect.poll(async()=>(await saved(page)).missionCompletionEvidence['w6-m2']).toBeUndefined();await page.reload();await unlockParent(page);await page.getByLabel('选择进度文件').setInputFiles({name:'w6m2.json',mimeType:'application/json',buffer:bytes});await expect.poll(async()=>await saved(page)).toMatchObject({schemaRevision:22,missionCompletionEvidence:{'w6-m1':{kind:'formal-v3'},'w6-m2':{kind:'formal-v3'}},works:{'w6-m1-structured-records-table':{kind:'python-structured-records-v1'},'w6-m2-fan-evidence-classification':{kind:'ai-evidence-classification-v1'}}});await unlockParent(page);await expect(page.getByRole('region',{name:'第六周证据分类学习摘要'})).toContainText('证据分类正式证明与作品已保存');});
