import { expect, test, type Page, type TestInfo } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { completeMission, createInitialProgress, serializeProgress } from '../src/progress/progress';
import { createMissionSession, recordRun, updateWorkspaceDraft } from '../src/progress/session';
import { createDefaultManorHelpDraft, compileManorHelpDraft, runManorHelp } from '../src/blockly/weekThreeManorHelpContract';
import { compileCuilanBooleanDraft, runCuilanBooleanForDraft } from '../src/blockly/weekThreeCuilanBooleanContract';
import { createDefaultYunzhanDialogueDraft, compileYunzhanDialogueDraft, runYunzhanDialogueForDraft } from '../src/blockly/weekThreeYunzhanDialogueContract';
import { createDefaultBajieJoiningDraft, compileBajieJoiningDraft, runBajieJoiningForDraft } from '../src/blockly/weekThreeBajieJoiningContract';
import { WEEK_THREE_BOSS_COLD_LOAD_MAX_BYTES } from '../scripts/budget-limits.mjs';

const CURRENT_KEY = 'xiyou-programming-progress-v3'; const REVISION_KEY = 'xiyou-programming-progress-revision-v3'; const MODE_KEY = 'xiyou-test-storage-mode';
const W3_M4_PREREQUISITE_SHA256 = '53951559b118e62e8f75b4b84d970e13eb480e773f08022228e255bba086f320';
type HealthEvent = { kind: string; url: string; detail: string };
const healthEvents = new WeakMap<Page, HealthEvent[]>(); let expectedFailureUrl: string | null = null;

// The sole preload is a replayable formal W3-M4 proof, never W3-M5 state.
function formalW3M4Prerequisite(testInfo: TestInfo) {
  let progress = createInitialProgress(); const standard = /motion parity/i.test(testInfo.title);
  progress = { ...progress, settings: { ...progress.settings, muted: !standard, reducedMotion: !standard, reducedMotionOverride: !standard }, privacy: { localDataNoticeSeen: true } };
  for (const id of ['w1-m1', 'w1-m2', 'w1-m3', 'w1-m4', 'w1-m5', 'w2-m1', 'w2-m2', 'w2-m3', 'w2-m4', 'w2-m5'] as const) progress = completeMission(progress, id, { stars: 3, hintsUsed: 0 });
  const manor = createDefaultManorHelpDraft(); manor.blocks.find((block) => block.id === 'manor-condition')!.type = 'w3_manor_condition_explicit_demon_help'; const manorTrace = compileManorHelpDraft(manor); progress = { ...progress, sessions: { ...progress.sessions, 'w3-m1': recordRun(updateWorkspaceDraft(createMissionSession('w3-m1'), manor, '2026-08-30T00:00:00.000Z'), runManorHelp(manorTrace), manorTrace, '2026-08-30T00:00:01.000Z') } }; progress = completeMission(progress, 'w3-m1', { stars: 3, hintsUsed: 0 });
  const cuilan = createMissionSession('w3-m2'); const cuilanDraft = structuredClone(cuilan.workspace); cuilanDraft.blocks.find((block) => block.id === 'cuilan-identity-condition')!.type = 'w3_cuilan_condition_identity_is_cuilan'; const cuilanTrace = compileCuilanBooleanDraft(cuilanDraft); progress = { ...progress, sessions: { ...progress.sessions, 'w3-m2': recordRun(updateWorkspaceDraft(cuilan, cuilanDraft, '2026-08-30T00:00:02.000Z'), runCuilanBooleanForDraft(cuilanDraft, cuilanTrace), cuilanTrace, '2026-08-30T00:00:03.000Z') } }; progress = completeMission(progress, 'w3-m2', { stars: 3, hintsUsed: 0 });
  const yunzhan = createDefaultYunzhanDialogueDraft(); yunzhan.blocks.find((block) => block.id === 'yunzhan-condition')!.type = 'w3_yunzhan_condition_pilgrimage_explicit'; yunzhan.blocks.find((block) => block.id === 'yunzhan-then-action')!.type = 'w3_yunzhan_explain_guanyin_origin'; yunzhan.blocks.find((block) => block.id === 'yunzhan-else-action')!.type = 'w3_yunzhan_guard_cave'; const yunzhanTrace = compileYunzhanDialogueDraft(yunzhan); progress = { ...progress, sessions: { ...progress.sessions, 'w3-m3': recordRun(updateWorkspaceDraft(createMissionSession('w3-m3'), yunzhan, '2026-08-30T00:00:04.000Z'), runYunzhanDialogueForDraft(yunzhan, yunzhanTrace), yunzhanTrace, '2026-08-30T00:00:05.000Z') } }; progress = completeMission(progress, 'w3-m3', { stars: 3, hintsUsed: 0 });
  const bajie = createDefaultBajieJoiningDraft(); bajie.blocks.find((block) => block.id === 'bajie-boolean-operation')!.operator = 'and'; const bajieTrace = compileBajieJoiningDraft(bajie); progress = { ...progress, sessions: { ...progress.sessions, 'w3-m4': recordRun(updateWorkspaceDraft(createMissionSession('w3-m4'), bajie, '2026-08-30T00:00:06.000Z'), runBajieJoiningForDraft(bajie, bajieTrace), bajieTrace, '2026-08-30T00:00:07.000Z') } };
  return serializeProgress(completeMission(progress, 'w3-m4', { stars: 3, hintsUsed: 0 }));
}
function expectedFailure(value: string) { return expectedFailureUrl !== null && (value === expectedFailureUrl || value.includes(expectedFailureUrl)); }
function attachHealth(page: Page) { const events: HealthEvent[] = []; healthEvents.set(page, events); page.on('console', (message) => { if (message.type() === 'error' && !expectedFailure(message.location().url) && !expectedFailure(message.text())) events.push({ kind: 'console', url: message.location().url || page.url(), detail: message.text() }); }); page.on('pageerror', (error) => events.push({ kind: 'pageerror', url: page.url(), detail: error.message })); page.on('requestfailed', (request) => { const detail = request.failure()?.errorText ?? ''; if (!expectedFailure(request.url()) && !(request.url() === 'https://static.blockly.com/media/sprites.svg' && /ABORTED|cancelled/i.test(detail))) events.push({ kind: 'requestfailed', url: request.url(), detail }); }); page.on('response', (response) => { if (response.status() >= 400 && !expectedFailure(response.url())) events.push({ kind: 'response', url: response.url(), detail: `HTTP ${response.status()}` }); }); }
async function stored(page: Page) { return page.evaluate((key) => JSON.parse(localStorage.getItem(key)!), CURRENT_KEY); }
const workspace = (page: Page) => page.getByLabel('第三周总试炼 Blockly 工作区', { exact: true });
const scene = (page: Page) => page.getByRole('region', { name: '高老庄总试炼故事舞台' });
async function gotoBoss(page: Page) { await page.goto('./#/mission/w3-m5'); await expect(page.getByText('第三周总试炼：高老庄故事状态机')).toBeVisible(); await expect(scene(page)).toBeVisible(); await expect(workspace(page).locator('svg.blocklySvg')).toBeVisible(); await expect(page.getByRole('button', { name: '运行整套试炼', exact: true })).toBeEnabled(); }
async function press(page: Page, name: string, key: 'Enter' | 'Space' | null = null) { const button = page.getByRole('button', { name, exact: true }); await expect(button).toBeEnabled(); if (key) { await button.focus(); await button.press(key); } else await button.click(); }
async function run(page: Page, key: 'Enter' | 'Space' | null = null) { await press(page, '运行整套试炼', key); }
async function attach(page: Page, testInfo: TestInfo, name: string) { const path = testInfo.outputPath(`${name}-${testInfo.project.name}.png`); await page.screenshot({ path, fullPage: true }); await testInfo.attach(`${name}-${testInfo.project.name}.png`, { path, contentType: 'image/png' }); }
async function replaceConditionFromToolbox(page: Page, slot: '庄口条件候选' | '后宅条件候选', candidate: '候选一' | '候选二', key: 'Enter' | 'Space' | null = null, requirePersistence = true) { const button = page.getByRole('group', { name: slot }).getByRole('button', { name: candidate, exact: true }); if (key) { await button.focus(); await button.press(key); } else await button.click(); if (!requirePersistence) return; const target = slot === '庄口条件候选' ? 'manor-if' : 'cuilan-identity-if'; const type = candidate === '候选二' ? (slot === '庄口条件候选' ? 'w3_boss_condition_explicit_demon_help' : 'w3_boss_condition_identity_is_cuilan') : (slot === '庄口条件候选' ? 'w3_boss_condition_mentions_gaolao' : 'w3_boss_condition_appearance_matches_cuilan'); await expect.poll(async () => (await stored(page)).sessions['w3-m5']?.workspace.blocks.some((block: { parentBlockId: string; parentInputName: string; type: string }) => block.parentBlockId === target && block.parentInputName === 'CONDITION' && block.type === type)).toBe(true); }
async function swapYunzhanBranches(page: Page, key: 'Enter' | 'Space' | null = null) { await press(page, '交换云栈洞两个分支', key); await expect.poll(async () => (await stored(page)).sessions['w3-m5']?.workspace.blocks.find((block: { id: string }) => block.id === 'yunzhan-if')?.inputs.THEN).toBe('yunzhan-else-action'); }
async function selectBossOperator(page: Page, input: 'mouse' | 'touch' | 'keyboard' = 'mouse') { const control = page.getByRole('button', { name: '切换归队组合方式', exact: true }); if (input === 'touch') { try { await control.tap(); } catch { await control.click(); } } else if (input === 'keyboard') { await control.focus(); await control.press('Enter'); } else await control.click(); await expect.poll(async () => (await stored(page)).sessions['w3-m5']?.workspace.blocks.find((block: { id: string }) => block.id === 'joining-combine')?.fields.OPERATOR).toBe('and'); }
async function repairAll(page: Page, input: 'mouse' | 'touch' | 'keyboard' = 'mouse') { await replaceConditionFromToolbox(page, '庄口条件候选', '候选二', input === 'keyboard' ? 'Enter' : null); await replaceConditionFromToolbox(page, '后宅条件候选', '候选二', input === 'keyboard' ? 'Space' : null); await swapYunzhanBranches(page, input === 'keyboard' ? 'Enter' : null); await selectBossOperator(page, input); }
async function completeBoss(page: Page, input: 'mouse' | 'touch' | 'keyboard' = 'mouse') { await repairAll(page, input); await run(page, input === 'keyboard' ? 'Enter' : null); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); }

test.describe('W3-M5 高老庄总试炼真实 Blockly 证据', () => {
  test.beforeEach(async ({ page }, testInfo) => { expectedFailureUrl = null; attachHealth(page); await page.addInitScript(({ raw, current, revision }) => { if (localStorage.getItem(current) === null) { localStorage.setItem(current, raw); localStorage.setItem(revision, '0'); } }, { raw: formalW3M4Prerequisite(testInfo), current: CURRENT_KEY, revision: REVISION_KEY }); });
  test.afterEach(async ({ page }) => { expect(healthEvents.get(page), 'unexpected W3-M5 browser health events').toEqual([]); });

  test('@w3-m5-full @w3-m5-narrow default failure, public observation, four real repairs, success, proof, unlock, and refresh replay', async ({ page }, testInfo) => {
    await gotoBoss(page); const geometry = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth })); expect(geometry.scroll).toBeLessThanOrEqual(geometry.width); await attach(page, testInfo, 'w3m5-default');
    await run(page); await expect(page.getByRole('alert')).toContainText('庄口求助卡的判断过宽'); await expect(page.getByRole('region', { name: '高老庄总试炼故事舞台' }).getByRole('article')).toHaveCount(1); await expect(page.getByRole('button', { name: '火眼金睛：观察本次判断' })).toBeVisible(); await attach(page, testInfo, 'w3m5-failure');
    const beforeObservation = (await stored(page)).sessions['w3-m5'].workspace.blocks; await press(page, '火眼金睛：观察本次判断'); const observation = page.locator('.week-three-boss-experience > aside[role="status"]'); await expect(observation).toContainText('当前公开卡'); await expect(observation).toContainText('逻辑练习'); await expect(observation).not.toContainText('正确'); expect((await stored(page)).sessions['w3-m5'].workspace.blocks).toEqual(beforeObservation);
    await replaceConditionFromToolbox(page, '庄口条件候选', '候选二'); await run(page); await expect(page.getByRole('alert')).toContainText('后宅伪装把外形当成真实身份');
    await replaceConditionFromToolbox(page, '后宅条件候选', '候选二'); await run(page); await expect(page.getByRole('alert')).toContainText('云栈洞对话进入的分支');
    await swapYunzhanBranches(page); await run(page); await expect(page.getByRole('alert')).toContainText('归队练习卡没有同时满足两个条件');
    await selectBossOperator(page); await run(page); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); await attach(page, testInfo, 'w3m5-success');
    const after = await stored(page); expect(after.missionCompletionEvidence['w3-m5'].kind).toBe('formal-v3'); expect(after.sessions['w3-m5'].successfulFullRuns).toBeGreaterThan(0); await press(page, '回成长地图'); await expect(page.getByRole('button', { name: '积木变代码', exact: true })).toBeEnabled();
    await page.goto('./#/mission/w3-m5'); const runCount = (await stored(page)).sessions['w3-m5'].totalRuns; await press(page, '重播上次运行'); await expect(scene(page).getByRole('article')).toContainText('原著归队情境'); expect((await stored(page)).sessions['w3-m5'].totalRuns).toBe(runCount);
  });
  test('@w3-m5-keyboard keyboard operates the same helper connections and real FieldDropdown', async ({ page }) => { await gotoBoss(page); await workspace(page).focus(); await repairAll(page, 'keyboard'); await run(page, 'Enter'); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); });
  test('@w3-m5-mouse desktop mouse changes the real Blockly FieldDropdown through the visible accessibility control', async ({ page }) => { await gotoBoss(page); await selectBossOperator(page, 'mouse'); });
  test('@w3-m5-touch touch operates the same helper and real FieldDropdown', async ({ page }) => { await gotoBoss(page); await repairAll(page, 'touch'); await run(page); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); });
  test('@w3-m5-parity muted and reduced-motion replay keeps the same saved story result', async ({ page }) => { await gotoBoss(page); await expect(page.getByRole('region', { name: '高老庄总试炼故事舞台' })).toHaveAttribute('data-motion-mode', 'reduced'); await expect(page.getByRole('region', { name: '高老庄总试炼故事舞台' })).toHaveAttribute('data-muted', 'true'); await completeBoss(page); const completed = await stored(page); await page.reload(); await expect(page.getByRole('region', { name: '高老庄总试炼故事舞台' })).toHaveAttribute('data-motion-mode', 'reduced'); expect((await stored(page)).missionCompletionEvidence['w3-m5']).toEqual(completed.missionCompletionEvidence['w3-m5']); });

  for (const mode of ['draft', 'run', 'observation', 'completion'] as const) test(`@w3-m5-storage ${mode} fault fails closed and the visible retry preserves relevant evidence`, async ({ page }) => {
    await gotoBoss(page);
    if (mode === 'draft') { await page.evaluate((key) => localStorage.setItem(key, 'fail-week-three-boss-draft'), MODE_KEY); await replaceConditionFromToolbox(page, '庄口条件候选', '候选二', null, false); }
    else if (mode === 'run') { await page.evaluate((key) => localStorage.setItem(key, 'fail-week-three-boss-run'), MODE_KEY); await run(page); }
    else if (mode === 'observation') { await run(page); await page.evaluate((key) => localStorage.setItem(key, 'fail-week-three-boss-observation'), MODE_KEY); await press(page, '火眼金睛：观察本次判断'); }
    else { await page.evaluate((key) => localStorage.setItem(key, 'fail-week-three-boss-completion'), MODE_KEY); await repairAll(page); await run(page); }
    const recovery = page.getByRole('alert').filter({ hasText: /待重试|通关待保存/ }).first(); await expect(recovery).toBeVisible(); await page.evaluate((key) => localStorage.setItem(key, 'off'), MODE_KEY); if (mode === 'completion') await page.getByRole('button', { name: '重试保存通关', exact: true }).click(); else await recovery.getByRole('button', { name: '重试保存', exact: true }).click();
    if (mode === 'draft') await expect.poll(async () => (await stored(page)).sessions['w3-m5']?.workspace.blocks.some((block: { type: string }) => block.type === 'w3_boss_condition_explicit_demon_help')).toBe(true);
    else if (mode === 'run') await expect.poll(async () => (await stored(page)).sessions['w3-m5']?.totalRuns).toBe(1);
    else if (mode === 'observation') { await expect.poll(async () => (await stored(page)).sessions['w3-m5']?.conditionObservationUses.length).toBe(1); await page.reload(); await expect(page.getByRole('button', { name: '火眼金睛：观察本次判断' })).toBeVisible(); }
    else { await expect.poll(async () => (await stored(page)).missionCompletionEvidence['w3-m5']?.kind).toBe('formal-v3'); await page.goto('./#/'); await expect(page.getByRole('button', { name: '积木变代码', exact: true })).toBeEnabled(); }
  });
  test('@w3-m5-external two pages preserve a backup and require explicit external reload', async ({ page, context }) => { await gotoBoss(page); const stale = await context.newPage(); attachHealth(stale); try { await stale.goto('./#/mission/w3-m5'); await replaceConditionFromToolbox(page, '庄口条件候选', '候选二'); const externalAlert = stale.getByRole('alert').filter({ hasText: '其他标签页已有新的学习进度' }); await expect(externalAlert).toHaveCount(1); const download = stale.waitForEvent('download'); await externalAlert.getByRole('button', { name: '下载当前积木备份' }).click(); expect((await download).suggestedFilename()).toMatch(/backup|progress/i); await externalAlert.getByRole('button', { name: '载入其他标签页进度' }).click(); await expect.poll(async () => (await stored(stale)).sessions['w3-m5']?.workspace.blocks.some((block: { type: string }) => block.type === 'w3_boss_condition_explicit_demon_help')).toBe(true); } finally { try { expect(healthEvents.get(stale)).toEqual([]); } finally { await stale.close(); } } });
  test('@w3-m5-corrupt corrupt raw is downloadable and snapshot restores the completed proof', async ({ page }) => { await gotoBoss(page); await completeBoss(page); const before = await stored(page); await page.evaluate((key) => localStorage.setItem(key, 'corrupt-week-three-boss-current'), MODE_KEY); await page.reload(); await expect(page.getByText('学习进度已经安全恢复')).toBeVisible(); await page.goto('./#/parent'); await page.getByLabel('设置 4 位家长 PIN').fill('4826'); await page.getByLabel('确认家长 PIN').fill('4826'); await press(page, '创建家长 PIN'); await page.getByLabel('我已安全保存恢复码').check(); await press(page, '确认已保存并进入'); const corrupt = page.waitForEvent('download'); await press(page, '下载损坏原文'); expect((await corrupt).suggestedFilename()).toContain('corrupt'); const recovered = await stored(page); expect(recovered.sessions['w3-m5']).toEqual(before.sessions['w3-m5']); expect(recovered.missionCompletionEvidence['w3-m5']).toEqual(before.missionCompletionEvidence['w3-m5']); });
  test('@w3-m5-parent export-import restores the formal session, proof, and W4-M1 unlock', async ({ page }) => { await gotoBoss(page); await completeBoss(page); await press(page, '回成长地图'); await press(page, '家长周报'); await page.getByLabel('设置 4 位家长 PIN').fill('4826'); await page.getByLabel('确认家长 PIN').fill('4826'); await press(page, '创建家长 PIN'); await page.getByLabel('我已安全保存恢复码').check(); await press(page, '确认已保存并进入'); const exportDownload = page.waitForEvent('download'); await press(page, '导出进度'); const path = await (await exportDownload).path(); expect(path).not.toBeNull(); const exported = JSON.parse(readFileSync(path!, 'utf8')); expect(exported.missionCompletionEvidence['w3-m5'].kind).toBe('formal-v3'); await press(page, '清空学习数据'); await page.getByLabel('输入“清空”以确认').fill('清空'); const cleared = page.waitForEvent('download'); await press(page, '备份并清空'); await cleared; await press(page, '我知道了'); await page.goto('./#/parent'); await page.getByLabel('设置 4 位家长 PIN').fill('4826'); await page.getByLabel('确认家长 PIN').fill('4826'); await press(page, '创建家长 PIN'); await page.getByLabel('我已安全保存恢复码').check(); await press(page, '确认已保存并进入'); await page.getByLabel('选择进度文件').setInputFiles({ name: 'w3-m5-progress.json', mimeType: 'application/json', buffer: readFileSync(path!) }); await expect(page.getByText('导入成功：来源版本 V3。')).toBeVisible(); const restored = await stored(page); expect(restored.sessions['w3-m5']).toEqual(exported.sessions['w3-m5']); expect(restored.missionCompletionEvidence['w3-m5']).toEqual(exported.missionCompletionEvidence['w3-m5']); await press(page, '成长地图'); await expect(page.getByRole('button', { name: '积木变代码', exact: true })).toBeEnabled(); });
  test('@w3-m5-cold cold route is bounded and the missing asset remains a real 404', async ({ page, request }) => { const bodies: Array<Promise<number>> = []; page.on('response', (response) => { if (response.status() >= 200 && response.status() < 300) bodies.push(response.body().then((body) => body.length)); }); await gotoBoss(page); expect((await Promise.all(bodies)).reduce((sum, bytes) => sum + bytes, 0)).toBeLessThanOrEqual(WEEK_THREE_BOSS_COLD_LOAD_MAX_BYTES); expect((await request.get('/xiyou-programming-journey/assets/week-three-boss/not-found.webp', { headers: { accept: 'image/webp' } })).status()).toBe(404); });
  test('@w3-m5-asset-fault asset 503 blocks completion until visible retry', async ({ page }) => { let failed = false; let retried = false; await page.route(/week-three-boss-background\.webp(?:\?.*)?$/, async (route) => { if (new URL(route.request().url()).searchParams.has('retry')) { retried = true; await route.continue(); } else { failed = true; expectedFailureUrl = route.request().url(); await route.fulfill({ status: 503, body: 'synthetic asset failure' }); } }); await page.goto('./#/mission/w3-m5'); await expect.poll(() => failed).toBe(true); const retry = page.getByRole('alert').filter({ hasText: '场景图片没有加载成功' }).getByRole('button', { name: '重试加载场景图片', exact: true }); await expect(retry).toBeVisible(); await expect(retry).toBeEnabled(); await repairAll(page); await run(page); await expect(page.getByRole('dialog', { name: '闯关成功' })).toHaveCount(0); await retry.click({ force: true }); await expect.poll(() => retried).toBe(true); await expect(page.locator('.week-three-boss-scene')).toHaveAttribute('data-scene-ready', 'true'); await expect(page.getByRole('dialog', { name: '闯关成功' })).toBeVisible(); expectedFailureUrl = null; });
  for (const boundary of [{ name: 'Experience', pattern: /WeekThreeBossExperience-[^/]+\.js(?:\?.*)?$/, text: '高老庄总试炼加载失败' }, { name: 'Scene', pattern: /WeekThreeBossScene-[^/]+\.js(?:\?.*)?$/, text: '高老庄总试炼场景加载失败' }, { name: 'Workspace', pattern: /WeekThreeBossBlocklyWorkspace-[^/]+\.js(?:\?.*)?$/, text: '高老庄总试炼积木加载失败' }]) test(`@w3-m5-lazy ${boundary.name} chunk 503 has retry`, async ({ page }) => { let failed = false; await page.route(boundary.pattern, async (route) => { if (!failed) { failed = true; expectedFailureUrl = route.request().url(); await route.fulfill({ status: 503, body: 'synthetic lazy failure' }); } else await route.continue(); }); await page.goto('./#/mission/w3-m5'); await expect(page.getByRole('alert')).toContainText(boundary.text); await press(page, '重新加载页面'); await expect(page.getByText('第三周总试炼：高老庄故事状态机')).toBeVisible(); await expect(scene(page)).toBeVisible(); await expect(workspace(page).locator('svg.blocklySvg')).toBeVisible(); expectedFailureUrl = null; });
});
