import { expect,test,type Locator,type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { formalW6M3Completion,formalW6M4Completion } from './support/w6m1Prerequisite';

const KEY='xiyou-programming-progress-v3',REV='xiyou-programming-progress-revision-v3',MODE='xiyou-test-storage-mode',SEED='w6-m4-e2e-seeded';
async function seed(page:Page,raw=formalW6M3Completion()){await page.addInitScript(({key,rev,value,seed})=>{if(sessionStorage.getItem(seed)!=='1'){localStorage.setItem(key,value);localStorage.setItem(rev,'0');sessionStorage.setItem(seed,'1')}},{key:KEY,rev:REV,value:raw,seed:SEED})}
async function saved(page:Page){return page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),KEY)}
async function waitDraft(page:Page){await expect.poll(async()=>Boolean((await saved(page)).sessions['w6-m4'])).toBe(true)}
const evidence={fan:'第六十回转述：悟空变作牛魔王模样，取得真扇。',reclaimed:'第六十一回转述：牛魔王变作八戒模样，骗回真扇。',notPassed:'M2 正式作品：二调当次没有完成灭火通行。',scope:'本页核查范围：M3 正式作品与本页给出的第六十至六十一回有限转述均未提供具体分钟数。'} as const;
const group=(page:Page,index:number)=>page.locator(`[aria-label="第${index}句核验"]`);
async function choose(card:Locator,verdict:string,evidenceLabels:readonly string[],disposition:string){await card.getByLabel(verdict,{exact:true}).check();for(const label of evidenceLabels)await card.getByLabel(label,{exact:false}).check();await card.getByLabel(disposition,{exact:false}).check()}
async function solve(page:Page){await choose(group(page,1),'材料支持',[evidence.fan,evidence.reclaimed],'保留原句');await choose(group(page,2),'与材料冲突',[evidence.notPassed],'有据修订');await choose(group(page,3),'本页材料不足',[evidence.scope],'暂不能确认')}
async function unlockParent(page:Page){const acknowledge=page.getByRole('button',{name:'我知道了',exact:true}),report=page.getByRole('button',{name:'导出进度',exact:true}),login=page.getByLabel('家长 PIN',{exact:true}),setup=page.getByLabel('设置 4 位家长 PIN',{exact:true});if(!(await saved(page)).privacy.localDataNoticeSeen){await expect(acknowledge).toBeVisible();await acknowledge.click();await expect.poll(async()=>(await saved(page)).privacy.localDataNoticeSeen).toBe(true)}await expect(page.getByTestId('app-background')).not.toHaveAttribute('inert','');await expect(report.or(login).or(setup)).toBeVisible();if(await report.isVisible())return;if(await login.isVisible()){await login.fill('4826');await page.getByRole('button',{name:'进入周报'}).click();await expect(report).toBeVisible();return}const confirm=page.getByLabel('确认家长 PIN');await setup.fill('4826');await confirm.fill('4826');await page.getByRole('button',{name:'创建家长 PIN'}).click();await page.getByLabel('我已安全保存恢复码').check();await page.getByRole('button',{name:'确认已保存并进入'}).click();await expect(report).toBeVisible()}

test('@w6-m4-full blank review, first blocker, faithful report, M3 source and formal M5 unlock',async({page})=>{await seed(page);await page.goto('./#/mission/w6-m4');await expect(page.getByRole('heading',{name:'核验而非猜测·回答审校台'})).toBeVisible();await waitDraft(page);await expect(page.getByRole('region',{name:'人为编写的本地核验练习'})).toContainText('不是真实 AI 回答，也不是你上一关的输出');await expect(page.getByRole('region',{name:'我的 M3 正式说明书与输出'})).toContainText('按原著整理二调芭蕉扇的经过');for(let index=1;index<=3;index++){const card=group(page,index);for(const label of ['材料支持','与材料冲突','本页材料不足','保留原句'])await expect(card.getByRole('radio',{name:label,exact:true})).not.toBeChecked();for(const name of [/^有据修订：/,/^暂不能确认：/])await expect(card.getByRole('radio',{name})).not.toBeChecked()}await page.getByRole('button',{name:'提交逐句核验'}).click();await expect(page.getByLabel('回答审校结果')).toContainText('先为当前这句话');expect((await saved(page)).sessions['w6-m4'].lastRun.failureSnapshots).toHaveLength(1);await choose(group(page,1),'材料支持',[evidence.fan,evidence.reclaimed],'保留原句');await choose(group(page,2),'与材料冲突',[evidence.notPassed],'有据修订');await choose(group(page,3),'与材料冲突',[evidence.scope],'判为错误');await page.getByRole('button',{name:'提交逐句核验'}).click();const report=page.getByRole('region',{name:'逐句审校报告'});await expect(report).toContainText('二调取扇过程不是十分钟');await expect(report).not.toContainText('原著没有');await group(page,3).getByLabel('本页材料不足',{exact:true}).check();await group(page,3).getByLabel('暂不能确认',{exact:false}).check();await page.getByRole('button',{name:'提交逐句核验'}).click();await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible({timeout:30_000});const progress=await saved(page);expect(progress).toMatchObject({schemaRevision:22,missionCompletionEvidence:{'w6-m3':{kind:'formal-v3'},'w6-m4':{kind:'formal-v3',workId:'w6-m4-second-attempt-review'}},works:{'w6-m4-second-attempt-review':{kind:'ai-fact-check-report-v1',run:{completed:true}}}});expect(progress.missions['w6-m5']).toBeUndefined();await page.getByRole('button',{name:'继续下一关'}).click();await expect(page.getByRole('heading',{name:'三调芭蕉扇·取经档案总编'})).toBeVisible();await page.goto('./#/mission/w6-m4');await page.reload();await page.getByRole('button',{name:'重放已保存审校报告'}).click();await expect(page.getByLabel('回答审校结果')).toContainText('正式证明没有改写')});

test('@w6-m4-keyboard focus survives save and native arrows and Tab continue the review',async({page})=>{await seed(page);await page.goto('./#/mission/w6-m4');await waitDraft(page);const first=group(page,1).getByLabel('材料支持',{exact:true}),second=group(page,1).getByLabel('与材料冲突',{exact:true}),evidenceBox=group(page,1).getByLabel(evidence.fan,{exact:false});await first.focus();await page.keyboard.press('Space');await expect.poll(async()=>(await saved(page)).sessions['w6-m4'].input.reviews[0].verdict).toBe('supported');await expect(first).toBeFocused();await page.keyboard.press('ArrowDown');await expect.poll(async()=>(await saved(page)).sessions['w6-m4'].input.reviews[0].verdict).toBe('conflicting');await expect(second).toBeFocused();await page.keyboard.press('Tab');await expect(evidenceBox).toBeFocused();await page.keyboard.press('Space');await expect.poll(async()=>(await saved(page)).sessions['w6-m4'].input.reviews[0].evidenceIds).toContain('chapter-60-true-fan')});

test('@w6-m4-touch touch input changes the saved report without horizontal overflow',async({page})=>{await seed(page);await page.goto('./#/mission/w6-m4');await waitDraft(page);await group(page,1).getByLabel('材料支持',{exact:true}).tap();await group(page,1).getByLabel(evidence.fan,{exact:false}).tap();await expect.poll(async()=>(await saved(page)).sessions['w6-m4'].input.reviews[0].evidenceIds).toContain('chapter-60-true-fan');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)});

test('@w6-m4-external stale tabs preserve newer review and load it explicitly',async({page,context})=>{await seed(page);await page.addInitScript(()=>window.addEventListener('storage',event=>event.stopImmediatePropagation(),true));await page.goto('./#/mission/w6-m4');await waitDraft(page);const second=await context.newPage();await second.goto('./#/mission/w6-m4');await waitDraft(second);await group(second,1).getByLabel('材料支持',{exact:true}).check();await expect.poll(async()=>(await saved(second)).sessions['w6-m4'].input.reviews[0].verdict).toBe('supported');await group(page,1).getByLabel(evidence.fan,{exact:false}).check();await expect(page.getByRole('button',{name:'载入其他标签页进度'})).toBeVisible();await page.getByRole('button',{name:'载入其他标签页进度'}).click();await expect(group(page,1).getByLabel('材料支持',{exact:true})).toBeChecked();expect((await saved(page)).sessions['w6-m4'].input.reviews[0].evidenceIds).toEqual([]);await second.close()});

test('@w6-m4-corrupt corrupt current data restores the valid M3 source and M4 draft',async({page})=>{await seed(page);await page.goto('./#/mission/w6-m4');await waitDraft(page);await group(page,1).getByLabel('材料支持',{exact:true}).check();await expect.poll(async()=>(await saved(page)).sessions['w6-m4'].input.reviews[0].verdict).toBe('supported');await page.evaluate(key=>{const raw=localStorage.getItem(key)!;localStorage.setItem('xiyou-programming-progress-snapshot-v3',raw);localStorage.setItem(key,'{broken w6-m4 current')},KEY);await page.reload();await expect(page.getByText('学习进度已经安全恢复')).toBeVisible();await page.goto('./#/mission/w6-m4');await expect(group(page,1).getByLabel('材料支持',{exact:true})).toBeChecked();expect((await saved(page)).missionCompletionEvidence['w6-m3']?.kind).toBe('formal-v3')});

test('@w6-m4-storage session and completion failures retry exact transactions once',async({page})=>{await seed(page);await page.goto('./#/mission/w6-m4');await waitDraft(page);await page.evaluate(key=>localStorage.setItem(key,'fail-w6-m4-session'),MODE);await group(page,1).getByLabel('材料支持',{exact:true}).check();await expect(page.getByRole('button',{name:'重试保存'})).toBeVisible();await page.evaluate(key=>localStorage.setItem(key,'off'),MODE);await page.getByRole('button',{name:'重试保存'}).click();await solve(page);await page.evaluate(key=>localStorage.setItem(key,'fail-w6-m4-completion'),MODE);await page.getByRole('button',{name:'提交逐句核验'}).click();await expect(page.getByRole('button',{name:'重试保存'})).toBeVisible();expect((await saved(page)).sessions['w6-m4'].totalRuns).toBe(1);await page.evaluate(key=>localStorage.setItem(key,'off'),MODE);await page.getByRole('button',{name:'重试保存'}).click();await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible();expect((await saved(page)).sessions['w6-m4'].totalRuns).toBe(1)});

test('@w6-m4-assets successful saved review waits for scene and seals after retry',async({page})=>{await seed(page);await page.route(/flaming-mountain-background\.webp/,route=>route.fulfill({status:503,body:'unavailable'}));await page.goto('./#/mission/w6-m4');await waitDraft(page);await solve(page);await page.getByRole('button',{name:'提交逐句核验'}).click();await expect.poll(async()=>(await saved(page)).sessions['w6-m4'].lastRun?.completed).toBe(true);expect((await saved(page)).missions['w6-m4']).toBeUndefined();await page.unroute(/flaming-mountain-background\.webp/);await page.getByRole('button',{name:'重试加载火焰山场景'}).click();await expect(page.getByRole('dialog',{name:'闯关成功'})).toBeVisible({timeout:30_000});expect((await saved(page)).sessions['w6-m4'].totalRuns).toBe(1)});

test('@w6-m4-lazy failed fact-check chunk retries locally',async({page})=>{await seed(page);let failed=false;await page.route(/WeekSixFactCheckExperience-[^/]+\.js/,route=>{if(!failed){failed=true;return route.fulfill({status:503,body:'unavailable'})}return route.continue()});await page.goto('./#/mission/w6-m4');await expect(page.getByText('回答审校台体验加载失败')).toBeVisible({timeout:30_000});await page.unroute(/WeekSixFactCheckExperience-[^/]+\.js/);await page.getByRole('button',{name:'重新加载页面'}).click();await expect(page.getByRole('heading',{name:'核验而非猜测·回答审校台'})).toBeVisible()});

test('@w6-m4-parent export clear and import restore proof and non-answer summary',async({page})=>{await seed(page,formalW6M4Completion());await page.goto('./#/parent');await unlockParent(page);const summary=page.getByRole('region',{name:'第六周回答核验学习摘要'});await expect(summary).toContainText('回答审校正式证明与作品已保存');await expect(summary).not.toContainText(/chapter-60|provided-material-scope|gained-then-reclaimed|sourceWorkId/);const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出进度'}).click();const bytes=readFileSync((await(await download).path())!);await page.getByRole('button',{name:'清空学习数据'}).click();await page.getByLabel('输入“清空”以确认').fill('清空');const backup=page.waitForEvent('download');await page.getByRole('button',{name:'备份并清空'}).click();await backup;await expect.poll(async()=>(await saved(page)).missionCompletionEvidence['w6-m4']).toBeUndefined();await page.reload();await unlockParent(page);await page.getByLabel('选择进度文件').setInputFiles({name:'w6m4.json',mimeType:'application/json',buffer:bytes});await expect.poll(async()=>(await saved(page)).missionCompletionEvidence['w6-m4']?.kind).toBe('formal-v3');await unlockParent(page);await expect(page.getByRole('region',{name:'第六周回答核验学习摘要'})).toContainText('正式证明')});
