import { lazy, Suspense, useEffect, useMemo, useRef, useState, type ComponentType } from 'react';
import { runCuilanBooleanForDraft, type CuilanBooleanRunResult } from '../blockly/weekThreeCuilanBooleanContract';
import type { CuilanBooleanCompileResult } from '../blockly/weekThreeCuilanBooleanCompiler';
import { useProgress } from '../context/ProgressContext';
import { createMissionSession, recordCompileFailure, recordCuilanConditionObservationUse, recordRun, updateWorkspaceDraft } from '../progress/session';
import type { CuilanBooleanMissionSession } from '../progress/types';
import type { WeekThreeCuilanBooleanBlocklyWorkspace, WeekThreeCuilanBooleanBlocklyWorkspaceProps } from './WeekThreeCuilanBooleanBlocklyWorkspace';
import type { WeekThreeCuilanBooleanScene, WeekThreeCuilanBooleanSceneProps } from './WeekThreeCuilanBooleanScene';
import { downloadTextFile } from '../utils/download';
import { LazySectionBoundary } from './LazySectionBoundary';
import './WeekThreeCuilanBooleanExperience.css';

type WorkspaceComponent = typeof WeekThreeCuilanBooleanBlocklyWorkspace;
type SceneComponent = typeof WeekThreeCuilanBooleanScene;
const defaultWorkspaceLoader = () => import('./WeekThreeCuilanBooleanBlocklyWorkspace').then((module) => ({ default: module.WeekThreeCuilanBooleanBlocklyWorkspace }));
const defaultSceneLoader = () => import('./WeekThreeCuilanBooleanScene').then((module) => ({ default: module.WeekThreeCuilanBooleanScene }));
export interface WeekThreeCuilanBooleanExperienceProps { reducedMotion: boolean; muted: boolean; locked?: boolean; onComplete: (evidence: { stars: 1 | 2 | 3; hintsUsed: number }) => void | boolean | Promise<boolean>; onSessionPersistenceActiveChange?: (active: boolean) => void; onInteractionLockChange?: (locked: boolean, reason: 'idle' | 'playback' | 'session-pending' | 'session-recovery') => void; workspaceLoader?: () => Promise<{ default: ComponentType<WeekThreeCuilanBooleanBlocklyWorkspaceProps> }>; sceneLoader?: () => Promise<{ default: ComponentType<WeekThreeCuilanBooleanSceneProps> }>; reloadPage?: () => void; }
type Operation = 'idle' | 'draft' | 'run' | 'observation' | 'playback' | 'completion';
type SaveStatus = 'unsaved' | 'conflict';
type PendingPayload = { kind: 'draft'; draft: CuilanBooleanMissionSession['workspace'] } | { kind: 'run'; trace: CuilanBooleanMissionSession['lastTrace']; run: CuilanBooleanRunResult } | { kind: 'observation'; snapshotId: string } | { kind: 'completion'; evidence: { stars: 1 | 2 | 3; hintsUsed: number } };
const pendingText = (pending: PendingPayload, status: SaveStatus) => `${pending.kind === 'draft' ? '积木保存待重试' : pending.kind === 'run' ? '运行记录待重试' : pending.kind === 'observation' ? '观察记录待重试' : '通关待保存'}${status === 'conflict' ? '（其他标签页冲突）' : ''}`;
const feedback = (run: CuilanBooleanRunResult | null) => run?.failureSnapshot?.checkpointId === 'identity-reveal' ? '第二道检查进入了继续装作高翠兰分支，先观察这次判断的证据。' : run?.diagnostic ? '积木连接或执行顺序待修复。' : '';

export function WeekThreeCuilanBooleanExperience({ reducedMotion, muted, locked = false, onComplete, onSessionPersistenceActiveChange, onInteractionLockChange, workspaceLoader = defaultWorkspaceLoader, sceneLoader = defaultSceneLoader, reloadPage }: WeekThreeCuilanBooleanExperienceProps) {
  const context = useProgress(); const { progress, updateMissionSession } = context;
  const Workspace = useMemo(() => lazy(workspaceLoader), [workspaceLoader]); const Scene = useMemo(() => lazy(sceneLoader), [sceneLoader]);
  const initial = useMemo<CuilanBooleanMissionSession>(() => progress.sessions['w3-m2'] ?? createMissionSession('w3-m2'), []);
  const [session, setSession] = useState(initial); const [result, setResult] = useState<CuilanBooleanRunResult | null>(initial.lastRun); const [operation, setOperation] = useState<Operation>('idle'); const [pending, setPending] = useState<PendingPayload | null>(null); const [saveStatus, setSaveStatus] = useState<SaveStatus | null>(null); const [sceneReady, setSceneReady] = useState(false); const [replayToken, setReplayToken] = useState(0); const [observation, setObservation] = useState(false); const [isReplay, setIsReplay] = useState(false); const [externalPending, setExternalPending] = useState(false); const [workspaceGeneration, setWorkspaceGeneration] = useState(0);
  const mounted = useRef(true); const sessionRef = useRef(session); const sceneReadyRef = useRef(sceneReady); const ownWriteCount = useRef(0); sessionRef.current = session; sceneReadyRef.current = sceneReady;
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  useEffect(() => { if (context.saveStatus === 'conflict' && ownWriteCount.current === 0 && operation === 'idle' && pending === null) setExternalPending(true); }, [context.saveStatus, operation, pending]);
  const lockedNow = locked || operation !== 'idle' || pending !== null || externalPending;
  const lock = (next: boolean, reason: 'idle' | 'playback' | 'session-pending' | 'session-recovery') => { if (!mounted.current) return; onSessionPersistenceActiveChange?.(next); onInteractionLockChange?.(next, reason); };
  const save = async (update: (current: CuilanBooleanMissionSession) => CuilanBooleanMissionSession) => { ownWriteCount.current += 1; try { const value = await updateMissionSession('w3-m2', update); if (value.status === 'saved') { const next = value.progress.sessions['w3-m2'] ?? createMissionSession('w3-m2'); if (mounted.current) setSession(next); return { status: 'saved' as const, session: next }; } return { status: value.status as SaveStatus }; } finally { ownWriteCount.current -= 1; } };
  const finish = () => { if (mounted.current) { setPending(null); setSaveStatus(null); setOperation('idle'); } lock(false, 'idle'); };
  const fail = (payload: PendingPayload, status: SaveStatus) => { if (mounted.current) { setPending(payload); setSaveStatus(status); setOperation('idle'); } lock(true, 'session-recovery'); };
  const publish = (run: CuilanBooleanRunResult, replay = false) => { if (!mounted.current) return; setResult(run); setObservation(false); setSceneReady(false); setIsReplay(replay); setReplayToken((value) => value + 1); if (run.completed) { setOperation('playback'); lock(true, 'playback'); } else finish(); };
  const draft = async (value: CuilanBooleanMissionSession['workspace']) => { if (lockedNow) return { status: 'unsaved' as const }; setOperation('draft'); lock(true, 'session-pending'); const saved = await save((current) => updateWorkspaceDraft(current, value, new Date().toISOString())); if (!mounted.current) return { status: saved.status }; if (saved.status === 'saved') { setResult(saved.session.lastRun); setObservation(false); setIsReplay(false); finish(); return { status: 'saved' as const }; } fail({ kind: 'draft', draft: structuredClone(value) }, saved.status); return { status: saved.status }; };
  const run = async (compiled: CuilanBooleanCompileResult) => { if (lockedNow) return; setOperation('run'); lock(true, 'session-pending'); if (!compiled.ok) { const saved = await save((current) => recordCompileFailure(current, 'program-structure', new Date().toISOString())); if (!mounted.current) return; if (saved.status === 'saved') finish(); else fail({ kind: 'draft', draft: sessionRef.current.workspace }, saved.status); return; } const value = runCuilanBooleanForDraft(compiled.draft, compiled.trace); const saved = await save((current) => recordRun(current, value, compiled.trace, new Date().toISOString())); if (!mounted.current) return; if (saved.status === 'saved') publish(value); else fail({ kind: 'run', trace: structuredClone(compiled.trace), run: structuredClone(value) }, saved.status); };
  const observe = async () => { const snapshot = sessionRef.current.failureSnapshot; const stable = progress.abilities.conditionObservation.acquiredAt !== null && progress.abilities.conditionObservation.stableUnlockedAt !== null; if (!snapshot || !stable || lockedNow || sessionRef.current.conditionObservationUses.some((use) => use.snapshotId === snapshot.snapshotId)) return; setOperation('observation'); lock(true, 'session-pending'); const saved = await save((current) => recordCuilanConditionObservationUse(current, snapshot.snapshotId, new Date().toISOString())); if (!mounted.current) return; if (saved.status === 'saved') { setObservation(true); finish(); } else fail({ kind: 'observation', snapshotId: snapshot.snapshotId }, saved.status); };
  const complete = async () => { if (operation !== 'playback' || !sceneReadyRef.current || !result?.completed || pending) return; if (isReplay) { finish(); return; } const evidence = { stars: (sessionRef.current.usedHintTiers.length === 0 ? 3 : sessionRef.current.usedHintTiers.length === 1 ? 2 : 1) as 1 | 2 | 3, hintsUsed: sessionRef.current.usedHintTiers.length }; setOperation('completion'); try { if ((await onComplete(evidence)) === false) throw new Error('rejected'); if (mounted.current) finish(); } catch { if (mounted.current) fail({ kind: 'completion', evidence }, 'unsaved'); } };
  const retry = async () => { if (!pending || operation !== 'idle') return; const value = pending; setOperation(value.kind); lock(true, 'session-pending'); if (value.kind === 'draft') { const saved = await save((current) => updateWorkspaceDraft(current, value.draft, new Date().toISOString())); if (!mounted.current) return; if (saved.status === 'saved') { setResult(saved.session.lastRun); setObservation(false); finish(); } else fail(value, saved.status); return; } if (value.kind === 'run') { const saved = await save((current) => recordRun(current, value.run, value.trace, new Date().toISOString())); if (!mounted.current) return; if (saved.status === 'saved') publish(value.run); else fail(value, saved.status); return; } if (value.kind === 'observation') { const saved = await save((current) => recordCuilanConditionObservationUse(current, value.snapshotId, new Date().toISOString())); if (!mounted.current) return; if (saved.status === 'saved') { setObservation(true); finish(); } else fail(value, saved.status); return; } try { if ((await onComplete(value.evidence)) === false) throw new Error('rejected'); if (mounted.current) finish(); } catch { if (mounted.current) fail(value, 'unsaved'); } };
  const reloadExternal = () => { const external = context.reloadExternalProgress?.(); if (!external || !mounted.current) return; const next = external.sessions['w3-m2'] ?? createMissionSession('w3-m2'); setSession(next); setResult(null); setObservation(false); setPending(null); setSaveStatus(null); setOperation('idle'); setSceneReady(false); setIsReplay(false); setExternalPending(false); setWorkspaceGeneration((value) => value + 1); lock(false, 'idle'); };
  const downloadBackup = () => { const backup = context.createBackup?.(); if (backup) downloadTextFile(backup.filename, backup.contents, backup.mimeType); };
  const replay = () => { if (lockedNow || !session.lastRun || session.lastTrace.length === 0) return; publish(session.lastRun, true); };
  const stable = progress.abilities.conditionObservation.acquiredAt !== null && progress.abilities.conditionObservation.stableUnlockedAt !== null;
  const updateSceneReady = (ready: boolean) => { sceneReadyRef.current = ready; setSceneReady(ready); };
  return <section className="week-three-cuilan-experience"><LazySectionBoundary label="变化高翠兰场景" reloadPage={reloadPage}><Suspense fallback={<p role="status">变化高翠兰场景加载中，请稍候……</p>}><Scene events={result?.events ?? []} replayToken={replayToken} reducedMotion={reducedMotion} muted={muted} onResourceStateChange={updateSceneReady} onPlaybackComplete={() => void complete()} /></Suspense></LazySectionBoundary><LazySectionBoundary label="变化高翠兰积木" reloadPage={reloadPage}><Suspense fallback={<p role="status">变化高翠兰积木加载中，请稍候……</p>}><Workspace key={workspaceGeneration} draft={session.workspace} locked={lockedNow} focusBlockId={result?.diagnostic?.sourceBlockId ?? null} onFocusHandled={() => undefined} onDraftChange={draft} onRun={(compiled) => void run(compiled)} /></Suspense></LazySectionBoundary><p>本次错误不会扣除生命、资源或星级。</p><p role="alert">{feedback(result)}</p>{session.lastRun && operation === 'idle' && !pending && !externalPending ? <button type="button" onClick={replay}>重播上次运行</button> : null}{session.failureSnapshot && stable ? <button type="button" disabled={lockedNow} onClick={() => void observe()}>使用火眼金睛观察这次判断</button> : null}{observation && session.failureSnapshot ? <aside role="status"><p>{session.failureSnapshot.conditionLabel}</p><p>{session.failureSnapshot.observedValue ? '真' : '假'}</p><p>{session.failureSnapshot.evidenceTextKey === 'cuilan.identity.clue-observed' ? '已经取得姓名和云栈洞住处的线索。' : '变化后的外形已经和高翠兰相同。'}</p><p>{session.failureSnapshot.branch === 'then' ? '进入继续装作高翠兰分支' : '进入显出悟空本相分支'}</p></aside> : null}{externalPending ? <div role="alert">其他标签页已有新的学习进度，当前积木没有自动覆盖。<button type="button" onClick={downloadBackup}>下载当前积木备份</button><button type="button" onClick={reloadExternal}>载入其他标签页进度</button></div> : null}{pending && saveStatus ? <div role="alert">{pendingText(pending, saveStatus)}{saveStatus === 'conflict' ? <><button type="button" onClick={downloadBackup}>下载当前积木备份</button><button type="button" onClick={reloadExternal}>载入其他标签页进度</button></> : <button type="button" disabled={operation !== 'idle'} onClick={() => void retry()}>重试保存</button>}</div> : null}</section>;
}
