import { lazy, Suspense, useEffect, useMemo, useRef, useState, type ComponentType } from 'react';
import { runYunzhanDialogueForDraft, type YunzhanDialogueRunResult } from '../blockly/weekThreeYunzhanDialogueContract';
import type { YunzhanDialogueCompileResult } from '../blockly/weekThreeYunzhanDialogueCompiler';
import { useProgress } from '../context/ProgressContext';
import { createMissionSession, recordCompileFailure, recordConditionObservationUse, recordRun, updateWorkspaceDraft } from '../progress/session';
import type { WeekThreeYunzhanDialogueBlocklyWorkspaceProps } from './WeekThreeYunzhanDialogueBlocklyWorkspace';
import type { WeekThreeYunzhanDialogueSceneProps } from './WeekThreeYunzhanDialogueScene';
import { downloadTextFile } from '../utils/download';
import { LazySectionBoundary } from './LazySectionBoundary';
import './WeekThreeYunzhanDialogueExperience.css';
const Workspace = lazy(() => import('./WeekThreeYunzhanDialogueBlocklyWorkspace').then((module) => ({ default: module.WeekThreeYunzhanDialogueBlocklyWorkspace })));
const Scene = lazy(() => import('./WeekThreeYunzhanDialogueScene').then((module) => ({ default: module.WeekThreeYunzhanDialogueScene })));

export interface WeekThreeYunzhanDialogueExperienceProps { reducedMotion: boolean; muted: boolean; locked?: boolean; onComplete: (evidence: { stars: 1 | 2 | 3; hintsUsed: number }) => void | boolean | Promise<boolean>; onSessionPersistenceActiveChange?: (active: boolean) => void; onInteractionLockChange?: (locked: boolean, reason: 'idle' | 'playback' | 'session-pending' | 'session-recovery') => void; reloadPage?: () => void; }
export interface WeekThreeYunzhanDialogueExperienceProps { workspaceLoader?: () => Promise<{ default: ComponentType<WeekThreeYunzhanDialogueBlocklyWorkspaceProps> }>; sceneLoader?: () => Promise<{ default: ComponentType<WeekThreeYunzhanDialogueSceneProps> }>; }
export function WeekThreeYunzhanDialogueExperience({ reducedMotion, muted, locked = false, onComplete, onSessionPersistenceActiveChange, onInteractionLockChange, workspaceLoader, sceneLoader, reloadPage }: WeekThreeYunzhanDialogueExperienceProps) {
  const LoadedWorkspace = useMemo(() => workspaceLoader ? lazy(workspaceLoader) : Workspace, [workspaceLoader]); const LoadedScene = useMemo(() => sceneLoader ? lazy(sceneLoader) : Scene, [sceneLoader]); const context = useProgress(); const { progress, updateMissionSession, createBackup, reloadExternalProgress } = context; const initial = useMemo(() => progress.sessions['w3-m3'] ?? createMissionSession('w3-m3'), []); const [session, setSession] = useState(initial); const [run, setRun] = useState<YunzhanDialogueRunResult | null>(initial.lastRun); const [saving, setSaving] = useState(false); const [observation, setObservation] = useState(false); const [sceneReady, setSceneReady] = useState(false); const [replayToken, setReplayToken] = useState(0); const [isReplay, setIsReplay] = useState(false); const [saveError, setSaveError] = useState<string | null>(null); const [pendingKind, setPendingKind] = useState<'草稿' | '运行记录' | '观察记录' | '通关' | null>(null); const [pendingRun, setPendingRun] = useState<YunzhanDialogueCompileResult | null>(null); const [pendingDraft, setPendingDraft] = useState<typeof session.workspace | null>(null); const [pendingObservation, setPendingObservation] = useState<string | null>(null); const [pendingCompletion, setPendingCompletion] = useState<{ stars: 1 | 2 | 3; hintsUsed: number } | null>(null); const [externalPending, setExternalPending] = useState(false); const [workspaceGeneration, setWorkspaceGeneration] = useState(0); const ownWriteCount = useRef(0); const sceneReadyRef = useRef(sceneReady); sceneReadyRef.current = sceneReady;
  useEffect(() => { if (context.saveStatus === 'conflict' && ownWriteCount.current === 0 && !saving && pendingKind === null) setExternalPending(true); }, [context.saveStatus, saving, pendingKind]);
  const update = async (fn: (current: typeof session) => typeof session, kind: NonNullable<typeof pendingKind>) => { if (externalPending) return false; ownWriteCount.current += 1; setSaving(true); setSaveError(null); setPendingKind(null); onSessionPersistenceActiveChange?.(true); onInteractionLockChange?.(true, 'session-pending'); let result; try { result = await updateMissionSession('w3-m3', fn); } finally { ownWriteCount.current -= 1; setSaving(false); onSessionPersistenceActiveChange?.(false); onInteractionLockChange?.(false, 'idle'); } if (result!.status === 'saved') { const next = result!.progress.sessions['w3-m3'] ?? session; setSession(next); return true; } setPendingKind(kind); setSaveError(result!.status === 'conflict' ? '其他标签页已有新的学习进度，当前结果等待处理。' : `${kind}待重试`); return false; };
  const onDraftChange = async (draft: typeof session.workspace) => { const copy = structuredClone(draft); const saved = await update((current) => updateWorkspaceDraft(current, copy, new Date().toISOString()), '草稿'); if (!saved) setPendingDraft(copy); else setPendingDraft(null); return { status: saved ? 'saved' as const : 'unsaved' as const }; };
  const execute = async (compiled: YunzhanDialogueCompileResult) => { if (!compiled.ok) { await update((current) => recordCompileFailure(current, 'program-structure', new Date().toISOString()), '草稿'); return; } const result = runYunzhanDialogueForDraft(compiled.draft, compiled.trace); if (await update((current) => recordRun(current, result, compiled.trace, new Date().toISOString()), '运行记录')) { setPendingRun(null); setRun(result); setObservation(false); setReplayToken((value) => value + 1); } else setPendingRun(compiled); };
  const snapshot = session.failureSnapshot;
  const observe = async (snapshotId = snapshot?.snapshotId) => { if (!snapshotId || saving || externalPending || pendingKind !== null) return; if (await update((current) => recordConditionObservationUse(current, snapshotId, new Date().toISOString()), '观察记录')) { setPendingObservation(null); setObservation(true); } else setPendingObservation(snapshotId); };
  const complete = async (evidence: { stars: 1 | 2 | 3; hintsUsed: number } = { stars: 3, hintsUsed: session.usedHintTiers.length }) => { if (!run?.completed || !sceneReadyRef.current || saving || externalPending) return; if (isReplay) { setIsReplay(false); return; } try { if ((await onComplete(evidence)) === false) throw new Error('completion unsaved'); setPendingCompletion(null); } catch { setPendingKind('通关'); setPendingCompletion(evidence); setSaveError('通关待重试'); } };
  const retry = () => { if (pendingKind === '运行记录' && pendingRun) return void execute(pendingRun); if (pendingKind === '草稿' && pendingDraft) return void onDraftChange(pendingDraft); if (pendingKind === '观察记录' && pendingObservation) return void observe(pendingObservation); if (pendingKind === '通关' && pendingCompletion) return void complete(pendingCompletion); };
  const reloadExternal = () => { const external = reloadExternalProgress?.(); const next = external?.sessions['w3-m3']; if (!next) return; setSession(next); setRun(next.lastRun); setObservation(false); setSaveError(null); setPendingKind(null); setPendingRun(null); setPendingDraft(null); setPendingObservation(null); setPendingCompletion(null); setExternalPending(false); setWorkspaceGeneration((value) => value + 1); };
  const replay = () => { if (!session.lastRun || saving || externalPending || pendingKind !== null) return; setRun(session.lastRun); setIsReplay(true); setReplayToken((value) => value + 1); };
  const interactionLocked = locked || saving || externalPending || pendingKind !== null;
  const backup = () => { const current = createBackup?.(); if (current) downloadTextFile(current.filename, current.contents, current.mimeType); };
  const updateSceneReady = (ready: boolean) => { sceneReadyRef.current = ready; setSceneReady(ready); };
  return <section className="week-three-yunzhan-experience"><LazySectionBoundary label="云栈洞场景" reloadPage={reloadPage}><Suspense fallback={<p role="status">云栈洞场景加载中，请稍候……</p>}><LoadedScene events={run?.events ?? []} replayToken={replayToken} reducedMotion={reducedMotion} muted={muted} onResourceStateChange={updateSceneReady} onPlaybackComplete={() => void complete()} /></Suspense></LazySectionBoundary><LazySectionBoundary label="云栈洞积木" reloadPage={reloadPage}><Suspense fallback={<p role="status">云栈洞积木加载中，请稍候……</p>}><LoadedWorkspace key={workspaceGeneration} draft={session.workspace} locked={interactionLocked} onDraftChange={onDraftChange} onRun={(compiled) => void execute(compiled)} /></Suspense></LazySectionBoundary><p>本次错误不会扣除生命、资源或星级。</p>{session.lastRun && !externalPending ? <button type="button" disabled={interactionLocked} onClick={replay}>重播上次运行</button> : null}{snapshot ? <button type="button" disabled={interactionLocked} onClick={() => void observe()}>火眼金睛：观察本次判断</button> : null}{observation && snapshot ? <aside role="status"><p>{snapshot.conditionLabel}</p><p>{snapshot.observedValue ? '真' : '假'}</p><p>{snapshot.evidenceText}</p><p>实际进入{snapshot.branch === 'then' ? '成立' : '不成立'}分支，并执行了{snapshot.actionOpcode === 'guard-cave' ? '守洞动作' : '说明来历动作'}。</p></aside> : null}{externalPending ? <div role="alert">其他标签页已有新的学习进度，当前积木没有自动覆盖。<button type="button" onClick={backup}>下载当前积木备份</button><button type="button" onClick={reloadExternal}>载入其他标签页进度</button></div> : null}{saveError && !externalPending ? <div role="alert">{saveError}{pendingKind && saveError.includes('其他标签页') ? <><button type="button" onClick={backup}>下载当前积木备份</button><button type="button" onClick={reloadExternal}>载入其他标签页进度</button></> : <button type="button" onClick={retry}>重试保存</button>}</div> : null}</section>;
}
