import { lazy, Suspense, useEffect, useMemo, useRef, useState, type KeyboardEvent as ReactKeyboardEvent } from 'react';
import { useProgress } from '../context/ProgressContext';
import { runWeekSixClassification, type FanAuthenticityLabel, type PassageOutcomeLabel, type PracticeAuthenticityLabel, type WeekSixAttempt, type WeekSixClassificationInput, type WeekSixClassificationRunResult, type WeekSixEvidenceId } from '../engine/weekSixClassificationContract';
import { createWeekSixClassificationSession, recordWeekSixClassificationCheck, recordWeekSixClassificationHint, updateWeekSixClassificationGrouping, updateWeekSixClassificationInput, type WeekSixClassificationMissionSession } from '../progress/weekSixClassificationSession';
import { downloadTextFile } from '../utils/download';
import { LazySectionBoundary } from './LazySectionBoundary';
import { WEEK_SIX_CLASSIFICATION_EVIDENCE, weekSixClassificationFailureMessage } from './weekSixClassificationContent';
import './WeekSixClassificationExperience.css';

const Scene=lazy(()=>import('./WeekSixClassificationScene').then((module)=>({default:module.WeekSixClassificationScene})));
type LockReason='idle'|'playback'|'session-pending'|'session-recovery';
type RetryAction=()=>Promise<void>;
export interface WeekSixClassificationExperienceProps { reducedMotion:boolean;muted:boolean;locked:boolean;onComplete(input:{stars:number;hintsUsed:number}):Promise<boolean>;onSessionPersistenceActiveChange(active:boolean):void;onInteractionLockChange(active:boolean,reason:LockReason):void }
const hintTextFor=(tier:'observe'|'think'|'partial')=>tier==='observe'?'先看核验指出的是哪条记录、哪个分类维度。':tier==='think'?'扇子是真是假，与这次有没有完成灭火通行，是两个不同问题。':'回到当前记录，只选择能直接支持这个标签的依据。';

export function WeekSixClassificationExperience({reducedMotion,muted,locked,onComplete,onSessionPersistenceActiveChange,onInteractionLockChange}:WeekSixClassificationExperienceProps){
 const context=useProgress(),source=context.progress.works['w6-m1-structured-records-table'];
 if(!source)throw Error('W6-M2 缺少 W6-M1 正式来源作品');
 const created=useMemo(()=>createWeekSixClassificationSession({workId:source.workId,verifiedAt:source.verifiedAt,rows:source.run.rows},new Date().toISOString()),[source.workId,source.verifiedAt]);
 const initial=context.progress.sessions['w6-m2']??created;
 const[session,setSession]=useState(initial),sessionRef=useRef(initial);const[input,setInput]=useState(initial.input),inputRef=useRef(initial.input);const[message,setMessage]=useState(context.progress.missionCompletionEvidence['w6-m2']?.kind==='formal-v3'?'已载入保存的证据分类作品。':initial.lastRun?.completed?'上次核验已通过，正式作品尚未保存。':'先为每条记录选择两个标签，并分别选择支持它的依据。');
 const[run,setRun]=useState<WeekSixClassificationRunResult|null>(initial.lastRun),[busy,setBusy]=useState(false),[retryAction,setRetryAction]=useState<RetryAction|null>(null),[hintText,setHintText]=useState('');
 const[assetsReady,setAssetsReady]=useState(false),assetsReadyRef=useRef(false),[sceneError,setSceneError]=useState<string|null>(null),pendingCompletion=useRef(!!initial.lastRun?.completed&&context.progress.missionCompletionEvidence['w6-m2']?.kind!=='formal-v3'),recoveryActive=useRef(false),initialPersistStarted=useRef(false);
 const formal=context.progress.missionCompletionEvidence['w6-m2']?.kind==='formal-v3';
 const setLock=(active:boolean,reason:LockReason='session-pending')=>{setBusy(active);onInteractionLockChange(active,active?reason:'idle');onSessionPersistenceActiveChange(active);};
 const releaseLock=()=>{recoveryActive.current=false;setLock(false);};const holdRecoveryLock=()=>{recoveryActive.current=true;setBusy(false);onInteractionLockChange(true,'session-recovery');onSessionPersistenceActiveChange(true);};
 const accept=(next:WeekSixClassificationMissionSession)=>{sessionRef.current=next;inputRef.current=next.input;pendingCompletion.current=!!next.lastRun?.completed;setSession(next);setInput(next.input);return next;};
 const apply=async(update:(value:WeekSixClassificationMissionSession,now:string)=>WeekSixClassificationMissionSession)=>{const now=new Date().toISOString(),result=await context.updateMissionSession('w6-m2',(current)=>update(current,now));if(result.status!=='saved')throw Error(result.status);const saved=result.progress.sessions['w6-m2'];if(!saved)throw Error('W6-M2 session missing');return accept(saved);};
 const failWrite=(action:RetryAction,text:string)=>{setRetryAction(()=>action);setMessage(text);holdRecoveryLock();};
 const retryPending=async(after?:(saved:WeekSixClassificationMissionSession)=>void|Promise<void>)=>{const result=await context.retrySave();if(result.status!=='saved')throw Error(result.status);const saved=result.progress.sessions['w6-m2'];if(!saved)throw Error('W6-M2 session missing after retry');accept(saved);await after?.(saved);};
 const finishSolved=async()=>{const current=sessionRef.current,replayed=runWeekSixClassification(current.input,current.sourceRows);if(!pendingCompletion.current||formal||!current.lastRun?.completed||!replayed.completed||JSON.stringify(current.lastRun)!==JSON.stringify(replayed)||JSON.stringify(inputRef.current)!==JSON.stringify(current.input)){pendingCompletion.current=false;return;}const value={stars:3 as const,hintsUsed:current.usedHintTiers.length};setMessage('全部标签与依据已核对，正在保存正式分类作品。');
   const reveal=async(result:Awaited<ReturnType<typeof context.retrySave>>)=>{const proof=result.progress.missionCompletionEvidence['w6-m2'],work=result.progress.works['w6-m2-fan-evidence-classification'],saved=result.progress.sessions['w6-m2'];if(result.status!=='saved'||proof?.kind!=='formal-v3'||!work||!saved?.lastRun?.completed||proof.workId!==work.workId)throw Error('W6-M2 completion invalid');pendingCompletion.current=false;accept(saved);setRetryAction(null);const shown=await onComplete(value);if(!shown)setMessage('正式分类作品和证明已保存，可再次打开完成画面。');};
   let result;try{result=await context.complete('w6-m2',value);}catch{failWrite(async()=>reveal(await context.retrySave()),'正式分类作品和证明尚未保存，请重试。');return;}if(result.status!=='saved'){failWrite(async()=>reveal(await context.retrySave()),result.status==='conflict'?'其他标签页已有新进度，请先处理冲突。':'正式分类作品和证明尚未保存，请重试。');return;}try{await reveal(result);}catch{failWrite(finishSolved,'正式分类作品校验失败，请重试保存。');}
 };
 useEffect(()=>{if(formal||context.progress.sessions['w6-m2']||initialPersistStarted.current)return;initialPersistStarted.current=true;void apply((current)=>current).catch(()=>failWrite(()=>retryPending(),'初始空白分类草稿未保存，请重试。'));},[formal,context.progress.sessions['w6-m2']]);
 useEffect(()=>{const external=context.progress.sessions['w6-m2'];if(external&&external.savedAt>sessionRef.current.savedAt){accept(external);setRun(external.lastRun);}},[context.progress.sessions['w6-m2']]);
 useEffect(()=>()=>{onInteractionLockChange(false,'idle');onSessionPersistenceActiveChange(false);},[]);
 const persistInput=async(next:WeekSixClassificationInput)=>{if(formal)return;pendingCompletion.current=false;inputRef.current=next;setInput(next);setLock(true);try{const saved=await apply((current,now)=>updateWeekSixClassificationInput(current,next,now));setRun(saved.lastRun);setMessage('分类草稿已保存在这台电脑。');releaseLock();}catch{failWrite(()=>retryPending((saved)=>{setRun(saved.lastRun);setMessage('分类草稿已保存在这台电脑。');}),'分类草稿尚未保存，请重试。');}};
 const change=(attempt:WeekSixAttempt,field:'fanAuthenticity'|'fanEvidenceId'|'passageOutcome'|'passageEvidenceId',value:FanAuthenticityLabel|PassageOutcomeLabel|WeekSixEvidenceId|null)=>{const next=structuredClone(input),item=next.labels.find((label)=>label.attempt===attempt)!;(item as unknown as Record<string,unknown>)[field]=value;void persistInput(next);};
 const moveEvidence=(attempt:WeekSixAttempt,field:'fanEvidenceId'|'passageEvidenceId',ids:WeekSixEvidenceId[],current:WeekSixEvidenceId|null,event:ReactKeyboardEvent<HTMLSelectElement>)=>{if((event.key!=='ArrowDown'&&event.key!=='ArrowUp')||event.altKey||event.ctrlKey||event.metaKey)return;event.preventDefault();const values:[null,...WeekSixEvidenceId[]]=[null,...ids],index=Math.max(0,values.indexOf(current)),next=values[Math.max(0,Math.min(values.length-1,index+(event.key==='ArrowDown'?1:-1)))];if(next!==current)change(attempt,field,next);};
 const changePractice=(value:PracticeAuthenticityLabel)=>{const next=structuredClone(input);next.practiceAuthenticity=value;void persistInput(next);};
 const changeGrouping=async(dimension:'authenticity'|'passage')=>{if(formal){accept({...sessionRef.current,groupingDimension:dimension});return;}setLock(true);try{await apply((current,now)=>updateWeekSixClassificationGrouping(current,dimension,now));setMessage('分组视图已保存；分组仍来自你的标签。');releaseLock();}catch{failWrite(()=>retryPending(()=>setMessage('分组视图已保存；分组仍来自你的标签。')),'分组视图尚未保存，请重试。');}};
 const check=async()=>{if(busy||locked||retryAction)return;const actual=runWeekSixClassification(sessionRef.current.input,sessionRef.current.sourceRows);setRun(actual);if(formal){setMessage('已用保存的标签与依据重新核验；正式证明没有被改写。');return;}setLock(true);try{const saved=await apply((current,now)=>recordWeekSixClassificationCheck(current,current.input,actual,now));const result=saved.lastRun!;setRun(result);pendingCompletion.current=result.completed;if(!result.completed){setMessage(weekSixClassificationFailureMessage(result.failureSnapshots[0]));releaseLock();return;}if(!assetsReadyRef.current){setMessage('分类核验已通过；火焰山场景准备好后会保存正式作品。');releaseLock();return;}await finishSolved();if(!recoveryActive.current)releaseLock();}catch{failWrite(()=>retryPending(async(saved)=>{setRun(saved.lastRun);pendingCompletion.current=!!saved.lastRun?.completed;if(saved.lastRun?.completed&&assetsReadyRef.current)await finishSolved();else setMessage(saved.failureSnapshot?weekSixClassificationFailureMessage(saved.failureSnapshot):'本次核验已经保存。');}),'本次核验已完成，但结果尚未保存；请重试保存。');}};
 const showHint=async(tier:'observe'|'think'|'partial')=>{setLock(true);try{await apply((current,now)=>recordWeekSixClassificationHint(current,tier,now));setHintText(hintTextFor(tier));setMessage('提示已保存。');releaseLock();}catch{failWrite(()=>retryPending(()=>{setHintText(hintTextFor(tier));setMessage('提示已保存。');}),'提示尚未保存，暂不展示。');}};
 const retry=async()=>{if(!retryAction)return;setLock(true,'session-recovery');recoveryActive.current=false;try{await retryAction();if(recoveryActive.current)return;setRetryAction(null);releaseLock();}catch{setMessage('仍未保存，请稍后再试。');holdRecoveryLock();}};
 const reloadExternal=()=>{const external=context.reloadExternalProgress(),next=external?.sessions['w6-m2'];if(!next)return;accept(next);setRun(next.lastRun);setRetryAction(null);releaseLock();setMessage('已载入其他标签页保存的分类草稿。');};
 const disabled=locked||busy||!!retryAction||context.saveStatus==='conflict',groups=runWeekSixClassification(input,session.sourceRows).groups,shownGroups=session.groupingDimension==='authenticity'?groups.authenticity:groups.passage;
 return <section className="week-six-classification-experience" data-mission="w6-m2" data-reduced-motion={reducedMotion} data-muted={muted} data-assets-ready={assetsReady}>
  <header><p className="eyebrow">W6-M2 真假扇分类</p><h2>真假扇证据分类台</h2><p>这是本地数据标注实验：给记录贴标签，再用材料说明理由。你的输入不会发送给在线 AI。</p></header>
  <div className="week-six-classification-layout"><LazySectionBoundary label="三次借扇来源记录"><Suspense fallback={<p role="status">借扇记录加载中…</p>}><Scene rows={session.sourceRows} onAssetsReady={()=>{assetsReadyRef.current=true;setAssetsReady(true);setSceneError(null);void finishSolved();}} onAssetsError={(text)=>{assetsReadyRef.current=false;setAssetsReady(false);setSceneError(text);}}/></Suspense></LazySectionBoundary>
  <section className="week-six-classification-board" aria-label="真假扇证据分类台">{input.labels.map((label)=>{const evidence=WEEK_SIX_CLASSIFICATION_EVIDENCE.find((item)=>item.attempt===label.attempt)!.snippets;return <article key={label.attempt} aria-label={`${label.attempt}分类卡`}><h3>{label.attempt}</h3><p>{session.sourceRows.find((row)=>row.attempt===label.attempt)?.story}</p>
   <fieldset disabled={formal||disabled}><legend>扇子真假</legend><label><input type="radio" name={`${label.attempt}-fan`} checked={label.fanAuthenticity==='genuine'} onChange={()=>change(label.attempt,'fanAuthenticity','genuine')}/>真扇</label><label><input type="radio" name={`${label.attempt}-fan`} checked={label.fanAuthenticity==='false'} onChange={()=>change(label.attempt,'fanAuthenticity','false')}/>假扇</label><label>选择支持真假判断的依据<select aria-label={`${label.attempt}扇子真假依据`} value={label.fanEvidenceId??''} onKeyDown={(event)=>moveEvidence(label.attempt,'fanEvidenceId',evidence.map((snippet)=>snippet.id),label.fanEvidenceId,event)} onChange={(event)=>change(label.attempt,'fanEvidenceId',(event.target.value||null) as WeekSixEvidenceId|null)}><option value="">尚未选择</option>{evidence.map((snippet)=><option key={snippet.id} value={snippet.id}>{snippet.text}</option>)}</select></label>{label.fanEvidenceId?<p className="week-six-selected-evidence"><strong>已选依据：</strong>{evidence.find((snippet)=>snippet.id===label.fanEvidenceId)?.text}</p>:null}</fieldset>
   <fieldset disabled={formal||disabled}><legend>这次是否达成灭火通行</legend><label><input type="radio" name={`${label.attempt}-passage`} checked={label.passageOutcome==='passed'} onChange={()=>change(label.attempt,'passageOutcome','passed')}/>已达成</label><label><input type="radio" name={`${label.attempt}-passage`} checked={label.passageOutcome==='not-passed'} onChange={()=>change(label.attempt,'passageOutcome','not-passed')}/>未达成</label><label>选择支持通行判断的依据<select aria-label={`${label.attempt}灭火通行依据`} value={label.passageEvidenceId??''} onKeyDown={(event)=>moveEvidence(label.attempt,'passageEvidenceId',evidence.map((snippet)=>snippet.id),label.passageEvidenceId,event)} onChange={(event)=>change(label.attempt,'passageEvidenceId',(event.target.value||null) as WeekSixEvidenceId|null)}><option value="">尚未选择</option>{evidence.map((snippet)=><option key={snippet.id} value={snippet.id}>{snippet.text}</option>)}</select></label>{label.passageEvidenceId?<p className="week-six-selected-evidence"><strong>已选依据：</strong>{evidence.find((snippet)=>snippet.id===label.passageEvidenceId)?.text}</p>:null}</fieldset>
  </article>;})}</section></div>
  <section className="week-six-practice-card" aria-label="材料不足练习"><h3>材料不足练习</h3><p>练习材料只有：“悟空拿到一把扇子”。这不是原著第四次借扇，只判断这张卡提供的信息，不能借用其他记录补齐线索。</p><fieldset disabled={formal||disabled}><legend>这把扇子是真是假？</legend><label><input type="radio" name="practice-authenticity" checked={input.practiceAuthenticity==='genuine'} onChange={()=>changePractice('genuine')}/>真扇</label><label><input type="radio" name="practice-authenticity" checked={input.practiceAuthenticity==='false'} onChange={()=>changePractice('false')}/>假扇</label><label><input type="radio" name="practice-authenticity" checked={input.practiceAuthenticity==='insufficient'} onChange={()=>changePractice('insufficient')}/>证据不足</label></fieldset></section>
  <section className="week-six-classification-groups" aria-label="孩子当前标签分组"><h3>孩子当前标签分组</h3><div><button type="button" className="button button-ghost" aria-pressed={session.groupingDimension==='authenticity'} disabled={disabled} onClick={()=>void changeGrouping('authenticity')}>按扇子真假</button><button type="button" className="button button-ghost" aria-pressed={session.groupingDimension==='passage'} disabled={disabled} onClick={()=>void changeGrouping('passage')}>按通行结果</button></div><div className="week-six-group-columns">{Object.entries(shownGroups).map(([key,values])=><div key={key}><strong>{session.groupingDimension==='authenticity'?(key==='genuine'?'真扇':key==='false'?'假扇':'未选择'):(key==='passed'?'已达成':key==='notPassed'?'未达成':'未选择')}</strong><p>{values.length?values.join('、'):'暂无'}</p></div>)}</div><p>这里始终按你的当前标签分组；错误标签也会如实显示。</p></section>
  <section className="week-six-classification-feedback" data-state={retryAction?'unsaved':context.saveStatus} aria-live="polite"><p role={retryAction?'alert':'status'} aria-label="证据分类核验结果">{message}</p><button type="button" className="button button-primary" disabled={disabled} onClick={()=>void check()}>{formal?'重播已保存分类':'核验全部标签与依据'}</button>{!formal?<div aria-label="分类分层提示"><button type="button" className="button button-ghost" disabled={disabled} onClick={()=>void showHint('observe')}>提示一：先定位</button><button type="button" className="button button-ghost" disabled={disabled} onClick={()=>void showHint('think')}>提示二：分维度</button><button type="button" className="button button-ghost" disabled={disabled} onClick={()=>void showHint('partial')}>提示三：看依据</button>{hintText?<p role="note">{hintText}</p>:null}</div>:null}{retryAction?<button type="button" className="button button-primary" disabled={busy} onClick={()=>void retry()}>重试保存</button>:null}{context.saveStatus==='conflict'?<><button type="button" className="button button-ghost" onClick={()=>{const backup=context.createBackup();downloadTextFile(backup.filename,backup.contents,backup.mimeType);}}>下载当前分类备份</button><button type="button" className="button button-primary" onClick={reloadExternal}>载入其他标签页进度</button></>:null}{run?.failureSnapshots[0]?<p role="note">首个需要处理的位置：{run.failureSnapshots[0].attempt??'来源记录'} · {run.failureSnapshots[0].dimension==='fan-authenticity'?'扇子真假':run.failureSnapshots[0].dimension==='passage-outcome'?'灭火通行':run.failureSnapshots[0].dimension==='practice'?'材料练习':'分类输入'}</p>:null}{sceneError?<p role="alert">{sceneError}</p>:null}</section>
  <p>学习中的错误不会扣除生命、资源或星级。</p>
 </section>;
}
export default WeekSixClassificationExperience;
