import { useEffect, useState } from 'react';
import type { HeavenlySignalBossRuntimeEvent } from '../blockly/weekTwoHeavenlySignalBossContract';
import { assetUrl } from '../utils/assets';
const BACKGROUND = '/assets/week-two-heavenly-boss/signal-dispatch-background.webp'; const STATES = '/assets/week-two-heavenly-boss/heavenly-boss-states.webp';
export function WeekTwoHeavenlySignalBossScene({ events, replayToken, reducedMotion, muted, onPlaybackComplete, onResourceStateChange }: { events: HeavenlySignalBossRuntimeEvent[]; replayToken: number; reducedMotion: boolean; muted: boolean; onPlaybackComplete?: () => void; onResourceStateChange?: (ready: boolean) => void; }) {
  const [loaded, setLoaded] = useState({ background: false, states: false }); const [failed, setFailed] = useState(false); const [retry, setRetry] = useState(0); const ready = loaded.background && loaded.states && !failed; const source = (asset: string) => `${assetUrl(asset)}${retry ? `?retry=${retry}` : ''}`;
  useEffect(() => onResourceStateChange?.(ready), [onResourceStateChange, ready]); useEffect(() => { if (!ready || replayToken === 0) return; const timer = window.setTimeout(() => onPlaybackComplete?.(), reducedMotion ? 0 : 360); return () => window.clearTimeout(timer); }, [ready, replayToken, reducedMotion, onPlaybackComplete]);
  return <section role="img" aria-label="天宫总试炼代码执行场景" className="horse-care-scene heavenly-signal-boss-scene" data-scene-ready={String(ready)} data-motion-mode={reducedMotion ? 'reduced' : 'standard'} data-muted={String(muted)}><img key={`background-${retry}`} src={source(BACKGROUND)} alt="天宫信号调度台场景" onLoad={() => setLoaded((current) => ({ ...current, background: true }))} onError={() => setFailed(true)} /><img key={`states-${retry}`} src={source(STATES)} alt="天宫总试炼综合状态" onLoad={() => setLoaded((current) => ({ ...current, states: true }))} onError={() => setFailed(true)} />{failed ? <div role="alert">场景图片没有加载成功。<button type="button" onClick={() => { setLoaded({ background: false, states: false }); setFailed(false); setRetry((value) => value + 1); }}>重试加载场景图片</button></div> : <p role="status">{events.at(-1)?.type === 'canon-epilogue' ? '原著尾声：如来掌中赌赛后，悟空被压在五行山下。' : '五道天宫信号正在等待你的积木安排。'}</p>}</section>;
}
