import { useEffect, useRef, useState } from 'react';
import * as Blockly from 'blockly';
import { HEAVENLY_SIGNAL_BOSS_BLOCK_LABELS, registerHeavenlySignalBossBlocks } from '../blockly/weekTwoHeavenlySignalBossBlocks';
import type { HeavenlySignalBossCompileResult } from '../blockly/weekTwoHeavenlySignalBossCompiler';
import { compileHeavenlySignalBossWorkspace } from '../blockly/weekTwoHeavenlySignalBossCompiler';
import type { HeavenlySignalBossBlockType, HeavenlySignalBossWorkspaceDraftV1 } from '../blockly/weekTwoHeavenlySignalBossContract';

type SaveResult = { status: 'saved' | 'unsaved' | 'conflict' };
interface Props { draft: HeavenlySignalBossWorkspaceDraftV1; locked: boolean; focusBlockId: string | null; onFocusHandled: () => void; onDraftChange: (draft: HeavenlySignalBossWorkspaceDraftV1) => Promise<SaveResult>; onRun: (result: HeavenlySignalBossCompileResult) => void; }
const handler = (block: Blockly.Block | null) => { for (let current = block; current; current = current.getSurroundParent()) if (current.type.startsWith('xiyou_boss_on_')) return current; return null; };
const initialize = (block: Blockly.Block) => { const visual = block as Blockly.Block & { initSvg?: () => void; render?: () => void }; visual.initSvg?.(); visual.render?.(); };
const renderBlocks = (workspace: Blockly.Workspace) => workspace.getAllBlocks(false).forEach((block) => (block as Blockly.Block & { render?: () => void }).render?.());
function snapshot(workspace: Blockly.Workspace): HeavenlySignalBossWorkspaceDraftV1 {
  return { version: 1, missionId: 'w2-m5', blocks: workspace.getAllBlocks(false).map((block) => { const parent = block.getSurroundParent(); const owner = block.type.startsWith('xiyou_boss_on_') ? block : handler(parent); const previous = block.getPreviousBlock(); const point = block.getRelativeToSurfaceXY(); return { id: block.id, type: block.type as HeavenlySignalBossBlockType, previousId: previous && previous.id !== parent?.id ? previous.id : null, nextId: block.getNextBlock()?.id ?? null, parentBlockId: parent?.id ?? null, handlerBlockId: owner?.id ?? '', repeatCount: block.type === 'xiyou_boss_repeat_horse_care' ? Number(block.getFieldValue('TIMES')) : null, conditionBlockId: block.type === 'xiyou_boss_repeat_until_furnace_ready' ? block.getInputTargetBlock('CONDITION')?.id ?? null : null, x: point.x, y: point.y }; }) };
}
function restore(workspace: Blockly.Workspace, draft: HeavenlySignalBossWorkspaceDraftV1) {
  Blockly.Events.disable();
  try { workspace.clear(); const blocks = new Map<string, Blockly.Block>(); for (const item of draft.blocks) { const block = workspace.newBlock(item.type, item.id); block.moveBy(item.x, item.y); if (item.type === 'xiyou_boss_repeat_horse_care') block.setFieldValue(String(item.repeatCount), 'TIMES'); initialize(block); blocks.set(item.id, block); }
    for (const item of draft.blocks) if (item.nextId) blocks.get(item.id)?.nextConnection?.connect(blocks.get(item.nextId)?.previousConnection!);
    for (const item of draft.blocks) { const child = blocks.get(item.id)!; if (item.type.startsWith('xiyou_boss_on_')) continue; const parent = item.parentBlockId ? blocks.get(item.parentBlockId) : undefined; if (parent && item.previousId === null && item.type !== 'xiyou_boss_condition_red_eyes' && item.type !== 'xiyou_boss_condition_furnace_open' && item.type !== 'xiyou_boss_condition_smoke_clears') parent.getInput(parent.type.startsWith('xiyou_boss_on_') ? 'HANDLER' : 'CHILDREN')?.connection?.connect(child.previousConnection!); if (item.type === 'xiyou_boss_repeat_until_furnace_ready' && item.conditionBlockId) child.getInput('CONDITION')?.connection?.connect(blocks.get(item.conditionBlockId)?.outputConnection!); }
    renderBlocks(workspace);
  } finally { Blockly.Events.enable(); }
}
export function WeekTwoHeavenlySignalBossBlocklyWorkspace({ draft, locked, focusBlockId, onFocusHandled, onDraftChange, onRun }: Props) {
  const host = useRef<HTMLDivElement>(null); const workspaceRef = useRef<Blockly.Workspace | null>(null); const applying = useRef(false); const onDraftChangeRef = useRef(onDraftChange); const saveQueuedRef = useRef(false); const saveInFlightRef = useRef<{ serialized: string; promise: Promise<SaveResult> } | null>(null); const lastSyncedDraftRef = useRef<string | null>(null); const [version, setVersion] = useState(0); const [saveState, setSaveState] = useState<'idle' | 'unsaved' | 'conflict'>('idle'); onDraftChangeRef.current = onDraftChange;
  const save = async (): Promise<SaveResult> => { const workspace = workspaceRef.current; if (!workspace) return { status: 'unsaved' }; const nextDraft = snapshot(workspace); const serialized = JSON.stringify(nextDraft); if (lastSyncedDraftRef.current === serialized) return { status: 'saved' }; const inFlight = saveInFlightRef.current; if (inFlight) { if (inFlight.serialized === serialized) return inFlight.promise; await inFlight.promise; return save(); } const promise = (async () => { const result = await onDraftChangeRef.current(nextDraft); if (result.status === 'saved') lastSyncedDraftRef.current = serialized; setSaveState(result.status === 'saved' ? 'idle' : result.status); return result; })(); saveInFlightRef.current = { serialized, promise }; try { return await promise; } finally { if (saveInFlightRef.current?.promise === promise) saveInFlightRef.current = null; } };
  const scheduleSave = () => { if (saveQueuedRef.current) return; saveQueuedRef.current = true; queueMicrotask(() => { saveQueuedRef.current = false; void save(); }); };
  useEffect(() => { registerHeavenlySignalBossBlocks(); const workspace = navigator.userAgent.includes('jsdom') ? new Blockly.Workspace() : Blockly.inject(host.current!, { trashcan: true, sounds: false, renderer: 'zelos' }); workspaceRef.current = workspace; const changed = (event: Blockly.Events.Abstract) => { if (!applying.current && !event.isUiEvent) { setVersion((value) => value + 1); scheduleSave(); } }; workspace.addChangeListener(changed); return () => { workspace.removeChangeListener(changed); workspace.dispose(); workspaceRef.current = null; }; }, []);
  useEffect(() => { const workspace = workspaceRef.current; if (!workspace) return; const incoming = JSON.stringify(draft); if (lastSyncedDraftRef.current === incoming) return; applying.current = true; restore(workspace, draft); applying.current = false; lastSyncedDraftRef.current = incoming; setVersion((value) => value + 1); }, [draft]);
  useEffect(() => { if (!focusBlockId) return; const block = workspaceRef.current?.getBlockById(focusBlockId) as (Blockly.Block & { select?: () => void; getSvgRoot?: () => SVGElement }) | null; block?.select?.(); block?.getSvgRoot?.()?.focus(); onFocusHandled(); }, [focusBlockId, onFocusHandled]);
  const act = (operation: (workspace: Blockly.Workspace) => void) => { const workspace = workspaceRef.current; if (!workspace || locked) return; operation(workspace); renderBlocks(workspace); setVersion((value) => value + 1); scheduleSave(); };
  const increase = () => act((workspace) => workspace.getBlockById('stable-repeat')?.setFieldValue('3', 'TIMES'));
  const swapEvents = () => act((workspace) => { const returned = workspace.getBlockById('return-handler')!; const title = workspace.getBlockById('title-handler')!; const accept = workspace.getBlockById('accept-title')!; const flag = workspace.getBlockById('raise-flag')!; const residence = workspace.getBlockById('build-residence')!; returned.getInput('HANDLER')!.connection!.targetBlock()?.previousConnection?.disconnect(); title.getInput('HANDLER')!.connection!.targetBlock()?.previousConnection?.disconnect(); flag.nextConnection?.disconnect(); returned.getInput('HANDLER')!.connection!.connect(flag.previousConnection!); title.getInput('HANDLER')!.connection!.connect(accept.previousConnection!); accept.nextConnection!.connect(residence.previousConnection!); });
  const moveElixir = () => act((workspace) => { const drink = workspace.getBlockById('drink-banquet')!; const elixir = workspace.getBlockById('eat-elixir')!; const stumble = workspace.getBlockById('stumble-tusita')!; drink.nextConnection?.disconnect(); elixir.nextConnection?.disconnect(); drink.nextConnection!.connect(stumble.previousConnection!); stumble.nextConnection!.connect(elixir.previousConnection!); });
  const replaceCondition = (type: 'xiyou_boss_condition_red_eyes' | 'xiyou_boss_condition_furnace_open' | 'xiyou_boss_condition_smoke_clears') => act((workspace) => { const loop = workspace.getBlockById('furnace-loop')!; const old = loop.getInputTargetBlock('CONDITION'); old?.outputConnection?.disconnect(); old?.dispose(false); const sensor = workspace.newBlock(type); initialize(sensor); loop.getInput('CONDITION')!.connection!.connect(sensor.outputConnection!); renderBlocks(workspace); });
  const visible = workspaceRef.current?.getAllBlocks(false) ?? [];
  return <section className="advanced-week-one-workspace heavenly-signal-boss-workspace" aria-label="天宫总试炼 Blockly 工作区"><div className="advanced-week-one-palette" aria-label="天宫总试炼修复工具"><button type="button" disabled={locked} onClick={increase}>增加天马循环次数</button><button type="button" disabled={locked} onClick={swapEvents}>交换齐天事件动作</button><button type="button" disabled={locked} onClick={moveElixir}>把金丹放到误入兜率宫之后</button>{(['xiyou_boss_condition_red_eyes', 'xiyou_boss_condition_furnace_open', 'xiyou_boss_condition_smoke_clears'] as const).map((type) => <button key={type} type="button" disabled={locked} onClick={() => replaceCondition(type)}>换成：{HEAVENLY_SIGNAL_BOSS_BLOCK_LABELS[type]}</button>)}</div><div ref={host} className="advanced-blockly-host" aria-label="天宫总试炼可连接积木图" /><ol key={version} className="advanced-program-tree" aria-label="天宫总试炼真实积木连接">{visible.map((block) => <li key={block.id}>{HEAVENLY_SIGNAL_BOSS_BLOCK_LABELS[block.type as HeavenlySignalBossBlockType] ?? '积木'}</li>)}</ol>{saveState !== 'idle' ? <div role="alert">{saveState === 'conflict' ? '其他标签页已经更新，这次积木更改暂停保存。' : '这次积木更改还没有保存。'}{saveState === 'unsaved' ? <button type="button" onClick={() => void save()}>重试保存积木</button> : null}</div> : null}<div className="workspace-actions"><button type="button" className="button button-primary" disabled={locked} onClick={() => void (async () => { const saved = await save(); if (saved.status === 'saved' && workspaceRef.current) onRun(compileHeavenlySignalBossWorkspace(workspaceRef.current)); })()}>执行天宫总试炼</button></div></section>;
}
