import { lazy, Suspense, useMemo, useRef, useState, type ComponentType } from 'react';
import './AdvancedWeekOneExperience.css';
import { runHeavenlySignalBoss, type HeavenlySignalBossDiagnostic, type HeavenlySignalBossRunResult, type HeavenlySignalBossRuntimeEvent } from '../blockly/weekTwoHeavenlySignalBossContract';
import type { HeavenlySignalBossCompileResult } from '../blockly/weekTwoHeavenlySignalBossCompiler';
import { useProgress } from '../context/ProgressContext';
import { createMissionSession, recordCompileFailure, recordRun, updateWorkspaceDraft } from '../progress/session';
import type { HeavenlySignalBossMissionSession } from '../progress/types';
import { downloadTextFile } from '../utils/download';
import { LazySectionBoundary } from './LazySectionBoundary';
import type { WeekTwoHeavenlySignalBossBlocklyWorkspace } from './WeekTwoHeavenlySignalBossBlocklyWorkspace';
import type { WeekTwoHeavenlySignalBossScene } from './WeekTwoHeavenlySignalBossScene';
type WorkspaceComponent = typeof WeekTwoHeavenlySignalBossBlocklyWorkspace;
type SceneComponent = typeof WeekTwoHeavenlySignalBossScene;
const defaultWorkspaceLoader = () => import('./WeekTwoHeavenlySignalBossBlocklyWorkspace').then((module) => ({ default: module.WeekTwoHeavenlySignalBossBlocklyWorkspace }));
const defaultSceneLoader = () => import('./WeekTwoHeavenlySignalBossScene').then((module) => ({ default: module.WeekTwoHeavenlySignalBossScene }));
type LockReason = 'idle' | 'playback' | 'session-pending' | 'session-recovery'; type Recovery = 'none' | 'unsaved' | 'conflict';
export interface WeekTwoHeavenlySignalBossExperienceProps { reducedMotion: boolean; muted: boolean; locked?: boolean; onComplete: (evidence: { stars: 1 | 2 | 3; hintsUsed: number }) => void | boolean | Promise<boolean>; onSessionPersistenceActiveChange?: (active: boolean) => void; onInteractionLockChange?: (locked: boolean, reason: LockReason) => void; workspaceLoader?: () => Promise<{ default: ComponentType<Parameters<WorkspaceComponent>[0]> }>; sceneLoader?: () => Promise<{ default: ComponentType<Parameters<SceneComponent>[0]> }>; reloadPage?: () => void; }
const stars = (session: HeavenlySignalBossMissionSession): 1 | 2 | 3 => session.usedHintTiers.length === 0 ? 3 : session.usedHintTiers.length === 1 ? 2 : 1;
function message(diagnostic: HeavenlySignalBossDiagnostic | null) { if (!diagnostic) return ''; if (diagnostic.concept === 'loop-count') return '还有一匹天马没有照料。检查循环次数。'; if (diagnostic.concept === 'event-routing') return '这个动作接在了不属于它的天宫信号下。'; if (diagnostic.concept === 'sequence-precondition') return '这块金丹积木跑得太早：悟空还没有误入兜率宫。'; if (diagnostic.concept === 'loop-condition') return '眼睛变红只说明烟很大，炉门还没有打开。'; if (diagnostic.concept === 'condition-never-met') return '这个条件一直没有发生，循环已安全停下。'; return '积木连接还不完整，请检查当前信号下的动作。'; }
export function WeekTwoHeavenlySignalBossExperience({ reducedMotion, muted, locked = false, onComplete, onSessionPersistenceActiveChange, onInteractionLockChange, workspaceLoader = defaultWorkspaceLoader, sceneLoader = defaultSceneLoader, reloadPage }: WeekTwoHeavenlySignalBossExperienceProps) {
  const { progress, updateMissionSession, retrySave, createBackup, reloadExternalProgress } = useProgress(); const session = progress.sessions['w2-m5'] ?? createMissionSession('w2-m5'); const Workspace = useMemo(() => lazy(workspaceLoader), [workspaceLoader]); const Scene = useMemo(() => lazy(sceneLoader), [sceneLoader]); const [events, setEvents] = useState<HeavenlySignalBossRuntimeEvent[]>(session.lastRun?.events ?? []); const [result, setResult] = useState<HeavenlySignalBossRunResult | null>(session.lastRun); const [feedback, setFeedback] = useState(message(session.lastRun?.diagnostic ?? null)); const [focusBlockId, setFocusBlockId] = useState<string | null>(session.lastRun?.diagnostic?.sourceBlockId ?? null); const [pending, setPending] = useState(false); const [recovery, setRecovery] = useState<Recovery>('none'); const [eligible, setEligible] = useState(false); const [sceneReady, setSceneReady] = useState(false); const [replayToken, setReplayToken] = useState(0); const pendingRun = useRef<HeavenlySignalBossRunResult | null>(null); const completed = useRef(false);
  const setLock = (next: boolean, reason: LockReason) => { onSessionPersistenceActiveChange?.(next); onInteractionLockChange?.(next, reason); };
  const persist = async (update: (current: HeavenlySignalBossMissionSession) => HeavenlySignalBossMissionSession) => { setPending(true); setLock(true, 'session-pending'); const saved = await updateMissionSession('w2-m5', update); setPending(false); if (saved.status === 'saved') { setLock(false, 'idle'); return saved.status; } setRecovery(saved.status); setLock(true, 'session-recovery'); return saved.status; };
  const publish = (next: HeavenlySignalBossRunResult) => { setResult(next); setEvents(next.events); setFeedback(message(next.diagnostic)); setFocusBlockId(next.diagnostic?.sourceBlockId ?? null); setEligible(next.completed); setReplayToken((token) => token + 1); setLock(true, 'playback'); };
  const run = async (compiled: HeavenlySignalBossCompileResult) => { if (locked || pending || recovery !== 'none') return; if (!compiled.ok) { setFeedback('积木连接还不完整，请检查当前信号下的动作。'); setFocusBlockId(compiled.diagnostics[0]?.sourceBlockId ?? null); await persist((current) => recordCompileFailure(current, 'program-structure', new Date().toISOString())); return; } const next = runHeavenlySignalBoss(compiled.trace); pendingRun.current = next; if (await persist((current) => recordRun(current, next, compiled.trace, new Date().toISOString())) !== 'saved') return; pendingRun.current = null; publish(next); };
  const finish = async () => { setLock(false, 'idle'); if (!sceneReady || !eligible || !result?.completed || completed.current) return; completed.current = true; await onComplete({ stars: stars(session), hintsUsed: session.usedHintTiers.length }); };
  const retry = async () => { setPending(true); setRecovery('none'); const saved = await retrySave(); setPending(false); if (saved.status === 'saved') { const next = pendingRun.current; if (next) { pendingRun.current = null; publish(next); } else setLock(false, 'idle'); return; } setRecovery(saved.status === 'conflict' ? 'conflict' : 'unsaved'); };
  const lockedNow = locked || pending || recovery !== 'none';
  return <section className="advanced-week-one-experience heavenly-signal-boss-experience"><LazySectionBoundary label="天宫信号调度场景" reloadPage={reloadPage}><Suspense fallback={<p role="status">天宫信号调度场景加载中，请稍候……</p>}><Scene events={events} replayToken={replayToken} reducedMotion={reducedMotion} muted={muted} onResourceStateChange={setSceneReady} onPlaybackComplete={() => void finish()} /></Suspense></LazySectionBoundary><LazySectionBoundary label="天宫总试炼积木" reloadPage={reloadPage}><Suspense fallback={<p role="status">天宫总试炼积木加载中，请稍候……</p>}><Workspace draft={session.workspace} locked={lockedNow} focusBlockId={focusBlockId} onFocusHandled={() => setFocusBlockId(null)} onRun={(compiled) => void run(compiled)} onDraftChange={async (draft) => ({ status: await persist((current) => updateWorkspaceDraft(current, draft, new Date().toISOString())) })} /></Suspense></LazySectionBoundary>{feedback ? <div role="alert" className="battle-feedback">{feedback}</div> : null}<p>本次错误不会扣除生命、资源或星级。</p><div className="workspace-actions"><button type="button" className="button button-ghost" disabled={lockedNow || !session.lastRun} onClick={() => { setEligible(false); setEvents(session.lastRun?.events ?? []); setReplayToken((token) => token + 1); setLock(true, 'playback'); }}>重播最近一次</button></div>{recovery !== 'none' ? <div role="alert" className="unsaved-session"><p>{recovery === 'conflict' ? '本次记录与其他标签页冲突。' : '本次学习记录尚未保存，请重试。'}</p>{recovery === 'unsaved' ? <button type="button" onClick={() => void retry()}>重试保存本次记录</button> : <><button type="button" onClick={() => { const backup = createBackup(); downloadTextFile(backup.filename, backup.contents, backup.mimeType); }}>下载本页备份</button><button type="button" onClick={() => { pendingRun.current = null; reloadExternalProgress(); setRecovery('none'); setLock(false, 'idle'); }}>载入其他标签页版本</button></>}</div> : null}</section>;
}
