import * as Blockly from 'blockly';
import { useEffect, useRef, useState } from 'react';
import { registerYunzhanDialogueBlocks } from '../blockly/weekThreeYunzhanDialogueBlocks';
import { compileYunzhanDialogueWorkspace, restoreYunzhanDialogueWorkspace, type YunzhanDialogueCompileResult } from '../blockly/weekThreeYunzhanDialogueCompiler';
import type { YunzhanDialogueWorkspaceDraftV1 } from '../blockly/weekThreeYunzhanDialogueContract';

export interface WeekThreeYunzhanDialogueBlocklyWorkspaceProps { draft: YunzhanDialogueWorkspaceDraftV1; locked: boolean; onDraftChange: (draft: YunzhanDialogueWorkspaceDraftV1) => Promise<{ status: 'saved' | 'unsaved' | 'conflict' }>; onRun: (result: YunzhanDialogueCompileResult) => void; }
const serial = (draft: YunzhanDialogueWorkspaceDraftV1) => JSON.stringify(draft);
const renderYunzhanBlocks = (workspace: Blockly.Workspace) => { for (const block of workspace.getAllBlocks(false)) (block as Blockly.Block & { initSvg?: () => void }).initSvg?.(); for (const block of workspace.getTopBlocks(false)) (block as Blockly.Block & { render?: () => void }).render?.(); };
const restoreVisibleYunzhanWorkspace = (workspace: Blockly.Workspace, draft: YunzhanDialogueWorkspaceDraftV1) => { Blockly.Events.disable(); try { restoreYunzhanDialogueWorkspace(workspace, draft); renderYunzhanBlocks(workspace); } finally { Blockly.Events.enable(); } };
const fitWorkspace = (workspace: Blockly.Workspace, host: HTMLElement | null) => { const visual = workspace as Blockly.WorkspaceSvg & { getBlocksBoundingBox(): { getWidth(): number }; setScale(scale: number): void; scrollX: number; scrollY: number; translate(x: number, y: number): void }; if (typeof visual.zoomToFit !== 'function') return; window.requestAnimationFrame(() => { const hostWidth = host?.getBoundingClientRect().width || host?.clientWidth || 0; const narrow = hostWidth > 0 && hostWidth <= 600; if (narrow) { const root = visual.getTopBlocks(false)[0]; if (root) { Blockly.Events.disable(); try { const point = root.getRelativeToSurfaceXY(); root.moveBy(12 - point.x, 10 - point.y); } finally { Blockly.Events.enable(); } } } Blockly.svgResize(visual); visual.resizeContents(); if (visual.getAllBlocks(false).length) visual.zoomToFit(); if (narrow) { const available = Math.max(0, hostWidth - 24); const rendered = visual.getBlocksBoundingBox().getWidth() * visual.scale; if (available > 0 && rendered > available) visual.setScale(visual.scale * available / rendered); visual.scrollX = 0; visual.scrollY = 0; visual.translate(0, 0); } }); };
export function WeekThreeYunzhanDialogueBlocklyWorkspace({ draft, locked, onDraftChange, onRun }: WeekThreeYunzhanDialogueBlocklyWorkspaceProps) {
  const host = useRef<HTMLDivElement>(null); const ref = useRef<Blockly.Workspace | null>(null); const applying = useRef(false); const lastSynced = useRef<string | null>(null); const [message, setMessage] = useState('');
  const save = async () => { const workspace = ref.current; if (!workspace) return; const compiled = compileYunzhanDialogueWorkspace(workspace); if (!compiled.ok) { setMessage('积木连接待修复；这不是一次运行。'); return; } const incoming = serial(compiled.draft); if (incoming === lastSynced.current) { setMessage(''); return; } const result = await onDraftChange(compiled.draft); if (result.status === 'saved') lastSynced.current = incoming; setMessage(result.status === 'saved' ? '' : '积木尚未保存，请稍后重试。'); };
  useEffect(() => { registerYunzhanDialogueBlocks(); const workspace = navigator.userAgent.includes('jsdom') ? new Blockly.Workspace() : Blockly.inject(host.current!, { renderer: 'zelos', trashcan: true, sounds: false }); ref.current = workspace; const changed = (event: Blockly.Events.Abstract) => { if (!applying.current && !event.isUiEvent) void save(); }; workspace.addChangeListener(changed); const observer = typeof ResizeObserver === 'undefined' || !host.current ? null : new ResizeObserver(() => fitWorkspace(workspace, host.current)); if (host.current) observer?.observe(host.current); return () => { observer?.disconnect(); workspace.removeChangeListener(changed); workspace.dispose(); ref.current = null; }; }, []);
  useEffect(() => { const workspace = ref.current; if (!workspace) return; const incoming = serial(draft); if (incoming === lastSynced.current) return; applying.current = true; try { restoreVisibleYunzhanWorkspace(workspace, draft); lastSynced.current = incoming; fitWorkspace(workspace, host.current); } catch { setMessage('已保存的积木无法恢复。'); } finally { applying.current = false; } }, [draft]);
  const swap = () => { const workspace = ref.current; if (!workspace || locked) return; const gate = workspace.getBlockById('yunzhan-if'); const then = gate?.getInputTargetBlock('THEN'); const otherwise = gate?.getInputTargetBlock('ELSE'); if (!gate || !then || !otherwise) { setMessage('积木连接待修复；这不是一次运行。'); return; } then.previousConnection!.disconnect(); otherwise.previousConnection!.disconnect(); gate.getInput('THEN')!.connection!.connect(otherwise.previousConnection!); gate.getInput('ELSE')!.connection!.connect(then.previousConnection!); renderYunzhanBlocks(workspace); fitWorkspace(workspace, host.current); void save(); };
  return <section className="advanced-week-one-workspace" aria-label="云栈洞对话 Blockly 工作区"><div className="advanced-week-one-palette"><button className="button" type="button" disabled={locked} onClick={swap}>交换两个分支里的动作</button></div><div ref={host} className="advanced-blockly-host" aria-label="云栈洞可连接积木图" /><p role="status">{message}</p><div className="workspace-actions"><button className="button button-primary" type="button" disabled={locked} onClick={() => onRun(ref.current ? compileYunzhanDialogueWorkspace(ref.current) : { ok: false, draft: null, trace: [], diagnostics: [{ code: 'empty-workspace', sourceBlockId: null, concept: 'program-structure' }] })}>执行两轮对话</button></div></section>;
}
