import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { createMissionSession } from '../progress/session';
import { compileYunzhanDialogueDraft, runYunzhanDialogueForDraft } from '../blockly/weekThreeYunzhanDialogueContract';
let api: any;
vi.mock('../context/ProgressContext', () => ({ useProgress: () => api }));
import { WeekThreeYunzhanDialogueExperience } from './WeekThreeYunzhanDialogueExperience';

const Workspace = (props: any) => <><button onClick={() => void props.onDraftChange(props.draft)}>保存草稿</button><button onClick={() => props.onRun({ ok: true, draft: props.draft, trace: compileYunzhanDialogueDraft(props.draft) })}>运行</button></>;
const Scene = (props: any) => <><button onClick={() => props.onResourceStateChange(true)}>场景就绪</button><button onClick={props.onPlaybackComplete}>播放结束</button></>;
const setup = (statuses: Array<'saved' | 'unsaved' | 'conflict'>, saveStatus: 'idle' | 'conflict' = 'idle') => { const session = createMissionSession('w3-m3', '2026-08-27T00:00:00.000Z'); api = { saveStatus, progress: { sessions: { 'w3-m3': session }, abilities: { conditionObservation: { acquiredAt: 'x', stableUnlockedAt: 'x' } } }, updateMissionSession: vi.fn(async (_id: string, update: any) => { const next = update(session); const status = statuses.shift() ?? 'saved'; if (status === 'saved') Object.assign(session, next); return { status, progress: { sessions: { 'w3-m3': session } } }; }), createBackup: () => ({ filename: 'backup.json', contents: '{}', mimeType: 'application/json' }), reloadExternalProgress: () => api.progress }; return session; };
describe('W3-M3 保存优先 Experience', () => {
  it('CAS conflict presents backup and explicit external reload instead of silent overwrite', async () => { setup(['conflict']); render(<WeekThreeYunzhanDialogueExperience reducedMotion muted onComplete={() => true} workspaceLoader={async () => ({ default: Workspace })} sceneLoader={async () => ({ default: Scene })} />); fireEvent.click(await screen.findByText('保存草稿')); expect(await screen.findByText('下载当前积木备份')).toBeInTheDocument(); expect(screen.getByText('载入其他标签页进度')).toBeInTheDocument(); });
  it('草稿保存失败时按原草稿 payload 重试', async () => { setup(['unsaved', 'saved']); render(<WeekThreeYunzhanDialogueExperience reducedMotion muted onComplete={() => true} workspaceLoader={async () => ({ default: Workspace })} sceneLoader={async () => ({ default: Scene })} />); fireEvent.click(await screen.findByText('保存草稿')); expect(await screen.findByRole('alert')).toHaveTextContent('草稿待重试'); fireEvent.click(screen.getByText('重试保存')); await waitFor(() => expect(screen.queryByRole('alert')).toBeNull()); });
  it('运行保存失败时不播放失败结果，并按 run payload 重试', async () => { setup(['unsaved', 'saved']); render(<WeekThreeYunzhanDialogueExperience reducedMotion muted onComplete={() => true} workspaceLoader={async () => ({ default: Workspace })} sceneLoader={async () => ({ default: Scene })} />); fireEvent.click(await screen.findByText('运行')); expect(await screen.findByRole('alert')).toHaveTextContent('运行记录待重试'); fireEvent.click(screen.getByText('重试保存')); await waitFor(() => expect(screen.queryByRole('alert')).toBeNull()); });
  it('completion waits for scene readiness and retries failed completion separately', async () => { const session = setup(['saved', 'unsaved', 'saved']); const d = structuredClone(session.workspace); const a = d.blocks.find((x: any) => x.id === 'yunzhan-then-action')!; const b = d.blocks.find((x: any) => x.id === 'yunzhan-else-action')!; [a.branch, b.branch] = [b.branch, a.branch]; session.workspace = d; render(<WeekThreeYunzhanDialogueExperience reducedMotion muted onComplete={() => true} workspaceLoader={async () => ({ default: Workspace })} sceneLoader={async () => ({ default: Scene })} />); fireEvent.click(await screen.findByText('运行')); fireEvent.click(screen.getByText('播放结束')); expect(api.updateMissionSession).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByText('场景就绪')); fireEvent.click(screen.getByText('播放结束')); });
  it('external CAS blocks writes and exposes backup or explicit reload', async () => { setup([], 'conflict'); render(<WeekThreeYunzhanDialogueExperience reducedMotion muted onComplete={() => true} workspaceLoader={async () => ({ default: Workspace })} sceneLoader={async () => ({ default: Scene })} />); expect(await screen.findByRole('alert')).toHaveTextContent('其他标签页已有新的学习进度'); expect(screen.getByText('下载当前积木备份')).toBeInTheDocument(); expect(screen.getByText('载入其他标签页进度')).toBeInTheDocument(); });
  it('scene and workspace lazy failures stay in their own visible recovery boundaries', async () => { setup([]); render(<WeekThreeYunzhanDialogueExperience reducedMotion muted onComplete={() => true} workspaceLoader={async () => { throw new Error('workspace chunk'); }} sceneLoader={async () => { throw new Error('scene chunk'); }} />); const alerts = await screen.findAllByRole('alert'); expect(alerts.map((alert) => alert.textContent).join(' ')).toContain('云栈洞场景加载失败'); expect(alerts.map((alert) => alert.textContent).join(' ')).toContain('云栈洞积木加载失败'); });
});
