import * as Blockly from 'blockly';
import { compileWeekThreeBossDraft, type WeekThreeBossCompileResult } from './weekThreeBossCompiler';
import { WEEK_THREE_BOSS_COORDINATE_LIMIT, WEEK_THREE_BOSS_MISSION_ID, type WeekThreeBossWorkspaceBlock, type WeekThreeBossWorkspaceDraftV1 } from './weekThreeBossContract';
import { registerWeekThreeBossBlocks } from './weekThreeBossBlocks';

const fields = (block: Blockly.Block) => Object.fromEntries(block.inputList.flatMap((input) => input.fieldRow).filter((field): field is Blockly.Field => typeof field.name === 'string' && field.name.length > 0).map((field) => [field.name, field.getValue()]));
const clamp = (value: number) => Math.max(-WEEK_THREE_BOSS_COORDINATE_LIMIT, Math.min(WEEK_THREE_BOSS_COORDINATE_LIMIT, Math.round(value)));
export function serializeWeekThreeBossWorkspace(workspace: Blockly.Workspace): WeekThreeBossWorkspaceDraftV1 { const blocks = workspace.getAllBlocks(false); const root = blocks.find((block) => block.type === 'w3_boss_root'); const owner = new Map<string, { parent: string | null; input: string | null }>(); const visit = (block: Blockly.Block, parent: string | null, input: string | null) => { if (owner.has(block.id)) return; owner.set(block.id, { parent, input }); for (const part of block.inputList) { const child = part.connection?.targetBlock(); if (child) visit(child, block.id, part.name); } const next = block.nextConnection?.targetBlock(); if (next) visit(next, parent, input); }; if (root) visit(root, null, null); return { version: 1, missionId: WEEK_THREE_BOSS_MISSION_ID, blocks: blocks.map((block) => { const point = block.getRelativeToSurfaceXY(); const relation = owner.get(block.id); const previous = block.previousConnection?.targetBlock() ?? null; return { id: block.id, type: block.type as WeekThreeBossWorkspaceBlock['type'], fields: fields(block), inputs: Object.fromEntries(block.inputList.filter((input) => input.name).map((input) => [input.name, input.connection?.targetBlock()?.id ?? null])), parentBlockId: relation?.parent ?? null, parentInputName: relation?.input ?? null, previousId: previous?.id === relation?.parent ? null : previous?.id ?? null, nextId: block.nextConnection?.targetBlock()?.id ?? null, x: point.x, y: point.y }; }) }; }
export function restoreWeekThreeBossWorkspace(workspace: Blockly.Workspace, draft: WeekThreeBossWorkspaceDraftV1): WeekThreeBossCompileResult { const compiled = compileWeekThreeBossDraft(draft); if (!compiled.ok) return compiled; registerWeekThreeBossBlocks(); workspace.clear(); const map = new Map<string, Blockly.Block>(); for (const item of compiled.draft.blocks) { const block = workspace.newBlock(item.type, item.id); for (const [name, value] of Object.entries(item.fields)) block.setFieldValue(value, name); block.moveBy(clamp(item.x), clamp(item.y)); map.set(item.id, block); } for (const item of compiled.draft.blocks) { const block = map.get(item.id)!; for (const [name, target] of Object.entries(item.inputs)) if (target) { const child = map.get(target)!; block.getInput(name)!.connection!.connect(child.outputConnection ?? child.previousConnection!); } if (item.nextId) block.nextConnection!.connect(map.get(item.nextId)!.previousConnection!); } return compiled; }
export function compileWeekThreeBossWorkspace(workspace: Blockly.Workspace): WeekThreeBossCompileResult { return compileWeekThreeBossDraft(serializeWeekThreeBossWorkspace(workspace)); }
